package builtins
        
import GDW "shared:GDWrapper"
import GDE "shared:GDWrapper/gdAPI/gdextension"


int_Methods_list :: struct {
  Create0: GDE.PtrConstructor,
  Create1: GDE.PtrConstructor,
  Create2: GDE.PtrConstructor,
  Create3: GDE.PtrConstructor,
  Create4: GDE.PtrConstructor,
  VARIANT_OP_NEGATE_: GDE.PtrOperatorEvaluator,
  VARIANT_OP_POSITIVE_: GDE.PtrOperatorEvaluator,
  VARIANT_OP_BIT_NEGATE_: GDE.PtrOperatorEvaluator,
  VARIANT_OP_NOT_: GDE.PtrOperatorEvaluator,
  VARIANT_OP_AND_bool: GDE.PtrOperatorEvaluator,
  VARIANT_OP_OR_bool: GDE.PtrOperatorEvaluator,
  VARIANT_OP_XOR_bool: GDE.PtrOperatorEvaluator,
  VARIANT_OP_EQUAL_int: GDE.PtrOperatorEvaluator,
  VARIANT_OP_NOT_EQUAL_int: GDE.PtrOperatorEvaluator,
  VARIANT_OP_LESS_int: GDE.PtrOperatorEvaluator,
  VARIANT_OP_LESS_EQUAL_int: GDE.PtrOperatorEvaluator,
  VARIANT_OP_GREATER_int: GDE.PtrOperatorEvaluator,
  VARIANT_OP_GREATER_EQUAL_int: GDE.PtrOperatorEvaluator,
  VARIANT_OP_ADD_int: GDE.PtrOperatorEvaluator,
  VARIANT_OP_SUBTRACT_int: GDE.PtrOperatorEvaluator,
  VARIANT_OP_MULTIPLY_int: GDE.PtrOperatorEvaluator,
  VARIANT_OP_DIVIDE_int: GDE.PtrOperatorEvaluator,
  VARIANT_OP_MODULE_int: GDE.PtrOperatorEvaluator,
  VARIANT_OP_POWER_int: GDE.PtrOperatorEvaluator,
  VARIANT_OP_SHIFT_LEFT_int: GDE.PtrOperatorEvaluator,
  VARIANT_OP_SHIFT_RIGHT_int: GDE.PtrOperatorEvaluator,
  VARIANT_OP_BIT_AND_int: GDE.PtrOperatorEvaluator,
  VARIANT_OP_BIT_OR_int: GDE.PtrOperatorEvaluator,
  VARIANT_OP_BIT_XOR_int: GDE.PtrOperatorEvaluator,
  VARIANT_OP_AND_int: GDE.PtrOperatorEvaluator,
  VARIANT_OP_OR_int: GDE.PtrOperatorEvaluator,
  VARIANT_OP_XOR_int: GDE.PtrOperatorEvaluator,
  VARIANT_OP_EQUAL_float: GDE.PtrOperatorEvaluator,
  VARIANT_OP_NOT_EQUAL_float: GDE.PtrOperatorEvaluator,
  VARIANT_OP_LESS_float: GDE.PtrOperatorEvaluator,
  VARIANT_OP_LESS_EQUAL_float: GDE.PtrOperatorEvaluator,
  VARIANT_OP_GREATER_float: GDE.PtrOperatorEvaluator,
  VARIANT_OP_GREATER_EQUAL_float: GDE.PtrOperatorEvaluator,
  VARIANT_OP_ADD_float: GDE.PtrOperatorEvaluator,
  VARIANT_OP_SUBTRACT_float: GDE.PtrOperatorEvaluator,
  VARIANT_OP_MULTIPLY_float: GDE.PtrOperatorEvaluator,
  VARIANT_OP_DIVIDE_float: GDE.PtrOperatorEvaluator,
  VARIANT_OP_POWER_float: GDE.PtrOperatorEvaluator,
  VARIANT_OP_AND_float: GDE.PtrOperatorEvaluator,
  VARIANT_OP_OR_float: GDE.PtrOperatorEvaluator,
  VARIANT_OP_XOR_float: GDE.PtrOperatorEvaluator,
  VARIANT_OP_MULTIPLY_Vector2: GDE.PtrOperatorEvaluator,
  VARIANT_OP_MULTIPLY_Vector2i: GDE.PtrOperatorEvaluator,
  VARIANT_OP_MULTIPLY_Vector3: GDE.PtrOperatorEvaluator,
  VARIANT_OP_MULTIPLY_Vector3i: GDE.PtrOperatorEvaluator,
  VARIANT_OP_MULTIPLY_Vector4: GDE.PtrOperatorEvaluator,
  VARIANT_OP_MULTIPLY_Vector4i: GDE.PtrOperatorEvaluator,
  VARIANT_OP_MULTIPLY_Quaternion: GDE.PtrOperatorEvaluator,
  VARIANT_OP_MULTIPLY_Color: GDE.PtrOperatorEvaluator,
  VARIANT_OP_AND_Object: GDE.PtrOperatorEvaluator,
  VARIANT_OP_OR_Object: GDE.PtrOperatorEvaluator,
  VARIANT_OP_XOR_Object: GDE.PtrOperatorEvaluator,
  VARIANT_OP_IN_Dictionary: GDE.PtrOperatorEvaluator,
  VARIANT_OP_IN_Array: GDE.PtrOperatorEvaluator,
  VARIANT_OP_IN_PackedByteArray: GDE.PtrOperatorEvaluator,
  VARIANT_OP_IN_PackedInt32Array: GDE.PtrOperatorEvaluator,
  VARIANT_OP_IN_PackedInt64Array: GDE.PtrOperatorEvaluator,
  VARIANT_OP_IN_PackedFloat32Array: GDE.PtrOperatorEvaluator,
  VARIANT_OP_IN_PackedFloat64Array: GDE.PtrOperatorEvaluator,
}
