extends type_test


var boo = get_Bool()
var i = get_Int()
var f = get_float()
var vec2 = get_Vector2()
var vec2i = get_Vector2i()
var rect2 = get_Rect2()
var rect2i = get_Rect2i()
var vec3 = get_Vector3()
var vec3i = get_Vector3i()
var vec4 = get_Vector4()
var vect4i = get_Vector4i()
var plane = get_Plane()
var color = get_Color()
var quat = get_Quaternion()
var stri = get_gdstring()
var str_n = get_StringName()
var npath = get_NodePath()
var rid = get_RID()
var obj = get_Object()
var cllbl= get_Callable()
var sig = get_Signal()
var dict = get_Dictionary()
var trans2d = get_Transform2D()
var aabb = get_AABB()
var basis = get_Basis()
var trans3d = get_Transform3D()
var proj = get_Projection()
var arr = get_Array()
var pbytearr = get_PackedByteArray()
var pintarr = get_PackedInt32Array()
var pint64arr = get_PackedInt64Array()
var pf32arr = get_PackedFloat32Array()
var pf64arr = get_PackedFloat64Array()
var pstrarr = get_PackedStringArray()
var pvec2arr = get_PackedVector2Array()
var pvec3arr = get_PackedVector3Array()
var pcolorarr = get_PackedColorArray()
var pvec4arr = get_PackedVector4Array()

func _ready():
	


	print("get_Bool ",get_Bool())
	print("get_Int ",get_Int())
	print("get_float ",get_float())
	print("get_Vector2 ",get_Vector2())
	print("get_Vector2i ",get_Vector2i())
	print("get_Rect2 ",get_Rect2())
	print("get_Rect2i ",get_Rect2i())
	print("get_Vector3 ",get_Vector3())
	print("get_Vector3i ",get_Vector3i())
	print("get_Vector4 ",get_Vector4())
	print("get_Vector4i ",get_Vector4i())
	print("get_Plane ",get_Plane())
	print("get_Color ",get_Color())
	print("get_Quaternion ",get_Quaternion())
	print("get_gdstring ",get_gdstring())
	print("get_StringName ",get_StringName())#?
	print("get_NodePath ",get_NodePath())#?
	print("get_RID ",get_RID())
	print("get_Object ",get_Object())
	print("get_Callable ",get_Callable())
	print("get_Signal ",get_Signal())
	print("get_Dictionary ",get_Dictionary())
	print("get_Transform2D ",get_Transform2D())
	print("get_AABB ",get_AABB())
	print("get_Basis ",get_Basis())
	print("get_Transform3D ",get_Transform3D())
	print("get_Projection ",get_Projection())
	#print("get_Array ",get_Array())
	print("get_PackedByteArray ",get_PackedByteArray())
	print("get_PackedInt32Array ",get_PackedInt32Array())
	print("get_PackedInt64Array ",get_PackedInt64Array())
	print("get_PackedFloat32Array ",get_PackedFloat32Array())
	print("get_PackedFloat64Array ",get_PackedFloat64Array())
	print("get_PackedStringArray ",get_PackedStringArray())
	print("get_PackedVector2Array ",get_PackedVector2Array())
	print("get_PackedVector3Array ",get_PackedVector3Array())
	print("get_PackedColorArray ",get_PackedColorArray())
	print("get_PackedVector4Array ",get_PackedVector4Array())


	set_Bool(true)
	set_Int(3.5)
	set_float(3)
	set_Vector2(Vector2(3.66666,3.5))
	set_Vector2i(Vector2i(3,3))
	set_Rect2(Rect2(3.666, 6.999, 4.333, 22))
	set_Rect2i(Rect2(3, 6, 4, 22))
	set_Vector3(Vector3(1,2,3))
	set_Vector3i(Vector3i(1,2,3))
	set_Vector4(Vector4(1,2,3,4))
	set_Vector4i(Vector4i(1,2,3,4))
	set_Plane(Plane(1,2,3,4))
	set_Color(Color(1,2,3,4))
	set_Quaternion(Quaternion())
	#set_gdstring("3 I am robot")
	#set_StringName("broohaha")
	#set_NodePath("res://icon.svg")
	set_RID(RID())
	#obj=Node.new()
	#set_Object(obj)
	##set_Callable()
	##set_Signal()
	set_Dictionary({"entry": 1})
	set_Transform2D(Transform2D(1,Vector2(2,3),5,Vector2(6,7)))
	set_AABB(AABB(Vector3(1,2,3),Vector3(4,5,6)))
	set_Basis(Basis(Vector3(1,2,3),Vector3(4,5,6),Vector3(7,8,9)))
	set_Transform3D(Transform3D(Basis(Vector3(1,2,3),Vector3(4,5,6),Vector3(7,8,9)),Vector3(10,11,12)))
	set_Projection(Projection(Transform3D(Basis(Vector3(1,2,3),Vector3(4,5,6),Vector3(7,8,9)),Vector3(10,11,12))))
	##set_Array([1,2,3,4])
	set_PackedByteArray([8,3,23])
	set_PackedInt32Array([3,4])
	set_PackedInt64Array([64])
	set_PackedFloat32Array([32.32])
	set_PackedFloat64Array([64.64])
	set_PackedStringArray(["I'm a little teapot"])
	set_PackedVector2Array(PackedVector2Array())
	var pv3 = PackedVector3Array()
	pv3.append(Vector3(1,2,3))
	set_PackedVector3Array(pv3)
	var pca = PackedColorArray()
	pca.append(Color(1,2,3,4))
	set_PackedColorArray(pca)
	#set_PackedColorArray([1,2,3,4])
	set_PackedVector4Array([Vector4(1,2,3,4),3,12])

	print("get_Bool ",get_Bool())
	print("get_Int ",get_Int())
	print("get_float ",get_float())
	print("get_Vector2 ",get_Vector2())
	print("get_Vector2i ",get_Vector2i())
	print("get_Rect2 ",get_Rect2())
	print("get_Rect2i ",get_Rect2i())
	print("get_Vector3 ",get_Vector3())
	print("get_Vector3i ",get_Vector3i())
	print("get_Vector4 ",get_Vector4())
	print("get_Vector4i ",get_Vector4i())
	print("get_Plane ",get_Plane())
	print("get_Color ",get_Color())
	print("get_Quaternion ",get_Quaternion())
	print("get_gdstring ",get_gdstring())
	print("get_StringName ",get_StringName())#?
	print("get_NodePath ",get_NodePath())#?
	print("get_RID ",get_RID())
	print("get_Object ",get_Object())
	print("get_Callable ",get_Callable())
	print("get_Signal ",get_Signal())
	print("get_Dictionary ",get_Dictionary())
	print("get_Transform2D ",get_Transform2D())
	print("get_AABB ",get_AABB())
	print("get_Basis ",get_Basis())
	print("get_Transform3D ",get_Transform3D())
	print("get_Projection ",get_Projection())
	#print("get_Array ",get_Array())
	print("get_PackedByteArray ",get_PackedByteArray())
	print("get_PackedInt32Array ",get_PackedInt32Array())
	print("get_PackedInt64Array ",get_PackedInt64Array())
	print("get_PackedFloat32Array ",get_PackedFloat32Array())
	print("get_PackedFloat64Array ",get_PackedFloat64Array())
	print("get_PackedStringArray ",get_PackedStringArray())
	print("get_PackedVector2Array ",get_PackedVector2Array())
	print("get_PackedVector3Array ",get_PackedVector3Array())
	print("get_PackedColorArray ",get_PackedColorArray())
	print("get_PackedVector4Array ",get_PackedVector4Array())

var printonce = false
func _process(delta):
	if printonce == false :
		print("get_Bool ",get_Bool())
		print("get_Int ",get_Int())
		print("get_float ",get_float())
		print("get_Vector2 ",get_Vector2())
		print("get_Vector2i ",get_Vector2i())
		print("get_Rect2 ",get_Rect2())
		print("get_Rect2i ",get_Rect2i())
		print("get_Vector3 ",get_Vector3())
		print("get_Vector3i ",get_Vector3i())
		print("get_Vector4 ",get_Vector4())
		print("get_Vector4i ",get_Vector4i())
		print("get_Plane ",get_Plane())
		print("get_Color ",get_Color())
		print("get_Quaternion ",get_Quaternion())
		#print("get_gdstring ",get_gdstring())
		print("get_StringName ",get_StringName())#?
		print("get_NodePath ",get_NodePath())#?
		print("get_RID ",get_RID())
		print("get_Object ",get_Object())
		#print("get_Callable ",get_Callable())
		print("get_Signal ",get_Signal())
		#print("get_Dictionary ",get_Dictionary())
		print("get_Transform2D ",get_Transform2D())
		print("get_AABB ",get_AABB())
		print("get_Basis ",get_Basis())
		print("get_Transform3D ",get_Transform3D())
		print("get_Projection ",get_Projection())
		#print("get_Array ",get_Array())
		print("get_PackedByteArray ",get_PackedByteArray())
		print("get_PackedInt32Array ",get_PackedInt32Array())
		print("get_PackedInt64Array ",get_PackedInt64Array())
		print("get_PackedFloat32Array ",get_PackedFloat32Array())
		print("get_PackedFloat64Array ",get_PackedFloat64Array())
		print("get_PackedStringArray ",get_PackedStringArray())
		print("get_PackedVector2Array ",get_PackedVector2Array())
		print("get_PackedVector3Array ",get_PackedVector3Array())
		print("get_PackedColorArray ",get_PackedColorArray())
		print("get_PackedVector4Array ",get_PackedVector4Array())
		printonce = true
