extends Node


#var boo = calss_obj.get_Bool()
#var i = calss_obj.get_Int()
#var f = calss_obj.get_float()
#var vec2 = calss_obj.get_Vector2()
#var vec2i = calss_obj.get_Vector2i()
#var rect2 = calss_obj.get_Rect2()
#var rect2i = calss_obj.get_Rect2i()
#var vec3 = calss_obj.get_Vector3()
#var vec3i = calss_obj.get_Vector3i()
#var vec4 = calss_obj.get_Vector4()
#var vect4i = calss_obj.get_Vector4i()
#var plane = calss_obj.get_Plane()
#var color = calss_obj.get_Color()
#var quat = calss_obj.get_Quaternion()
#var stri = calss_obj.get_gdstring()
#var str_n = calss_obj.get_StringName()
#var npath = calss_obj.get_NodePath()
#var rid = calss_obj.get_RID()
#var obj = calss_obj.get_Object()
#var cllbl= calss_obj.get_Callable()
#var sig = calss_obj.get_Signal()
#var dict = calss_obj.get_Dictionary()
#var trans2d = calss_obj.get_Transform2D()
#var aabb = calss_obj.get_AABB()
#var basis = calss_obj.get_Basis()
#var trans3d = calss_obj.get_Transform3D()
#var proj = calss_obj.get_Projection()
#var arr = calss_obj.get_Array()
#var pbytearr = calss_obj.get_PackedByteArray()
#var pintarr = calss_obj.get_PackedInt32Array()
#var pint64arr = calss_obj.get_PackedInt64Array()
#var pf32arr = calss_obj.get_PackedFloat32Array()
#var pf64arr = calss_obj.get_PackedFloat64Array()
#var pstrarr = calss_obj.get_PackedStringArray()
#var pvec2arr = calss_obj.get_PackedVector2Array()
#var pvec3arr = calss_obj.get_PackedVector3Array()
#var pcolorarr = calss_obj.get_PackedColorArray()
#var pvec4arr = calss_obj.get_PackedVector4Array()

func _ready():
	

	var calss_obj = type_test_defaults.new()

	print("get_Bool ",calss_obj.get_Bool())
	print("get_Int ",calss_obj.get_Int())
	print("get_float ",calss_obj.get_float())
	print("get_Vector2 ",calss_obj.get_Vector2())
	print("get_Vector2i ",calss_obj.get_Vector2i())
	print("get_Rect2 ",calss_obj.get_Rect2())
	print("get_Rect2i ",calss_obj.get_Rect2i())
	print("get_Vector3 ",calss_obj.get_Vector3())
	print("get_Vector3i ",calss_obj.get_Vector3i())
	print("get_Vector4 ",calss_obj.get_Vector4())
	print("get_Vector4i ",calss_obj.get_Vector4i())
	print("get_Plane ",calss_obj.get_Plane())
	print("get_Color ",calss_obj.get_Color())
	print("get_Quaternion ",calss_obj.get_Quaternion())
	print("get_gdstring ",calss_obj.get_gdstring())
	print("get_StringName ",calss_obj.get_StringName())
	print("get_NodePath ",calss_obj.get_NodePath())
	print("get_RID ",calss_obj.get_RID())
	print("get_Object ",calss_obj.get_Object())
	print("get_Callable ",calss_obj.get_Callable())
	print("get_Signal ",calss_obj.get_Signal())
	print("get_Dictionary ",calss_obj.get_Dictionary())
	print("get_Transform2D ",calss_obj.get_Transform2D())
	print("get_AABB ",calss_obj.get_AABB())
	print("get_Basis ",calss_obj.get_Basis())
	print("get_Transform3D ",calss_obj.get_Transform3D())
	print("get_Projection ",calss_obj.get_Projection())
	#print("get_Array ",calss_obj.get_Array())
	print("get_PackedByteArray ",calss_obj.get_PackedByteArray())
	print("get_PackedInt32Array ",calss_obj.get_PackedInt32Array())
	print("get_PackedInt64Array ",calss_obj.get_PackedInt64Array())
	print("get_PackedFloat32Array ",calss_obj.get_PackedFloat32Array())
	print("get_PackedFloat64Array ",calss_obj.get_PackedFloat64Array())
	print("get_PackedStringArray ",calss_obj.get_PackedStringArray())
	print("get_PackedVector2Array ",calss_obj.get_PackedVector2Array())
	print("get_PackedVector3Array ",calss_obj.get_PackedVector3Array())
	print("get_PackedColorArray ",calss_obj.get_PackedColorArray())
	print("get_PackedVector4Array ",calss_obj.get_PackedVector4Array())


	calss_obj.set_Bool(true)
	calss_obj.set_Int(3.5)
	calss_obj.set_float(3)
	calss_obj.set_Vector2(Vector2(3.66666,3.5))
	calss_obj.set_Vector2i(Vector2i(3,3))
	calss_obj.set_Rect2(Rect2(3.666, 6.999, 4.333, 22))
	calss_obj.set_Rect2i(Rect2(3, 6, 4, 22))
	calss_obj.set_Vector3(Vector3(1,2,3))
	calss_obj.set_Vector3i(Vector3i(1,2,3))
	calss_obj.set_Vector4(Vector4(1,2,3,4))
	calss_obj.set_Vector4i(Vector4i(1,2,3,4))
	calss_obj.set_Plane(Plane(1,2,3,4))
	calss_obj.set_Color(Color(1,2,3,4))
	calss_obj.set_Quaternion(Quaternion())
	#calss_obj.set_gdstring("3 I am robot")
	#calss_obj.set_StringName("broohaha")
	#calss_obj.set_NodePath("res://icon.svg")
	calss_obj.set_RID(RID())
	#calss_obj.obj=Node.new()
	#calss_obj.set_Object(obj)
	##calss_obj.set_Callable()
	##calss_obj.set_Signal()
	calss_obj.set_Dictionary({"entry": 1})
	calss_obj.set_Transform2D(Transform2D(1,Vector2(2,3),5,Vector2(6,7)))
	calss_obj.set_AABB(AABB(Vector3(1,2,3),Vector3(4,5,6)))
	calss_obj.set_Basis(Basis(Vector3(1,2,3),Vector3(4,5,6),Vector3(7,8,9)))
	calss_obj.set_Transform3D(Transform3D(Basis(Vector3(1,2,3),Vector3(4,5,6),Vector3(7,8,9)),Vector3(10,11,12)))
	calss_obj.set_Projection(Projection(Transform3D(Basis(Vector3(1,2,3),Vector3(4,5,6),Vector3(7,8,9)),Vector3(10,11,12))))
	##calss_obj.set_Array([1,2,3,4])
	calss_obj.set_PackedByteArray([8,3,23])
	calss_obj.set_PackedInt32Array([3,4])
	calss_obj.set_PackedInt64Array([64])
	calss_obj.set_PackedFloat32Array([32.32])
	calss_obj.set_PackedFloat64Array([64.64])
	calss_obj.set_PackedStringArray(["I'm a little teapot"])
	calss_obj.set_PackedVector2Array(PackedVector2Array())
	var pv3 = PackedVector3Array()
	pv3.append(Vector3(1,2,3))
	calss_obj.set_PackedVector3Array(pv3)
	var pca = PackedColorArray()
	pca.append(Color(1,2,3,4))
	calss_obj.set_PackedColorArray(pca)
	#calss_obj.set_PackedColorArray([1,2,3,4])
	calss_obj.set_PackedVector4Array([Vector4(1,2,3,4),3,12])

	print("get_Bool ",calss_obj.get_Bool())
	print("get_Int ",calss_obj.get_Int())
	print("get_float ",calss_obj.get_float())
	print("get_Vector2 ",calss_obj.get_Vector2())
	print("get_Vector2i ",calss_obj.get_Vector2i())
	print("get_Rect2 ",calss_obj.get_Rect2())
	print("get_Rect2i ",calss_obj.get_Rect2i())
	print("get_Vector3 ",calss_obj.get_Vector3())
	print("get_Vector3i ",calss_obj.get_Vector3i())
	print("get_Vector4 ",calss_obj.get_Vector4())
	print("get_Vector4i ",calss_obj.get_Vector4i())
	print("get_Plane ",calss_obj.get_Plane())
	print("get_Color ",calss_obj.get_Color())
	print("get_Quaternion ",calss_obj.get_Quaternion())
	print("get_gdstring ",calss_obj.get_gdstring())
	print("get_StringName ",calss_obj.get_StringName())#?
	print("get_NodePath ",calss_obj.get_NodePath())#?
	print("get_RID ",calss_obj.get_RID())
	print("get_Object ",calss_obj.get_Object())
	print("get_Callable ",calss_obj.get_Callable())
	print("get_Signal ",calss_obj.get_Signal())
	print("get_Dictionary ",calss_obj.get_Dictionary())
	print("get_Transform2D ",calss_obj.get_Transform2D())
	print("get_AABB ",calss_obj.get_AABB())
	print("get_Basis ",calss_obj.get_Basis())
	print("get_Transform3D ",calss_obj.get_Transform3D())
	print("get_Projection ",calss_obj.get_Projection())
	#print("get_Array ",calss_obj.get_Array())
	print("get_PackedByteArray ",calss_obj.get_PackedByteArray())
	print("get_PackedInt32Array ",calss_obj.get_PackedInt32Array())
	print("get_PackedInt64Array ",calss_obj.get_PackedInt64Array())
	print("get_PackedFloat32Array ",calss_obj.get_PackedFloat32Array())
	print("get_PackedFloat64Array ",calss_obj.get_PackedFloat64Array())
	print("get_PackedStringArray ",calss_obj.get_PackedStringArray())
	print("get_PackedVector2Array ",calss_obj.get_PackedVector2Array())
	print("get_PackedVector3Array ",calss_obj.get_PackedVector3Array())
	print("get_PackedColorArray ",calss_obj.get_PackedColorArray())
	print("get_PackedVector4Array ",calss_obj.get_PackedVector4Array())

var printonce = false
func _process(delta):
	if printonce == false :
		var calss_obj = type_test_defaults.new()
		print("get_Bool ",calss_obj.get_Bool())
		print("get_Int ",calss_obj.get_Int())
		print("get_float ",calss_obj.get_float())
		print("get_Vector2 ",calss_obj.get_Vector2())
		print("get_Vector2i ",calss_obj.get_Vector2i())
		print("get_Rect2 ",calss_obj.get_Rect2())
		print("get_Rect2i ",calss_obj.get_Rect2i())
		print("get_Vector3 ",calss_obj.get_Vector3())
		print("get_Vector3i ",calss_obj.get_Vector3i())
		print("get_Vector4 ",calss_obj.get_Vector4())
		print("get_Vector4i ",calss_obj.get_Vector4i())
		print("get_Plane ",calss_obj.get_Plane())
		print("get_Color ",calss_obj.get_Color())
		print("get_Quaternion ",calss_obj.get_Quaternion())
		#print("get_gdstring ",calss_obj.get_gdstring())
		print("get_StringName ",calss_obj.get_StringName())#?
		print("get_NodePath ",calss_obj.get_NodePath())#?
		print("get_RID ",calss_obj.get_RID())
		print("get_Object ",calss_obj.get_Object())
		#print("get_Callable ",calss_obj.get_Callable())
		print("get_Signal ",calss_obj.get_Signal())
		#print("get_Dictionary ",calss_obj.get_Dictionary())
		print("get_Transform2D ",calss_obj.get_Transform2D())
		print("get_AABB ",calss_obj.get_AABB())
		print("get_Basis ",calss_obj.get_Basis())
		print("get_Transform3D ",calss_obj.get_Transform3D())
		print("get_Projection ",calss_obj.get_Projection())
		#print("get_Array ",calss_obj.get_Array())
		print("get_PackedByteArray ",calss_obj.get_PackedByteArray())
		print("get_PackedInt32Array ",calss_obj.get_PackedInt32Array())
		print("get_PackedInt64Array ",calss_obj.get_PackedInt64Array())
		print("get_PackedFloat32Array ",calss_obj.get_PackedFloat32Array())
		print("get_PackedFloat64Array ",calss_obj.get_PackedFloat64Array())
		print("get_PackedStringArray ",calss_obj.get_PackedStringArray())
		print("get_PackedVector2Array ",calss_obj.get_PackedVector2Array())
		print("get_PackedVector3Array ",calss_obj.get_PackedVector3Array())
		print("get_PackedColorArray ",calss_obj.get_PackedColorArray())
		print("get_PackedVector4Array ",calss_obj.get_PackedVector4Array())
		printonce = true
