package GDWrapper

//Just the whole list of all the class names that appear in the api json.
//No idea, I just copy/pasted.
//Should be useful for:
// * Declaring the class in your custom class
// * Hints
// * ??
//Mainly want to get away from using raw strings.
//Name is very long. Yes.

ClassNameString :: string

ClassNameStrings :: [GodotClasses][?]string {
    .AESContext = "AESContext",
    .AStar2D = "AStar2D",
    .AStar2D = "AStar2D",
    .AStar3D = "AStar3D",
    .AStar3D = "AStar3D",
    .AStarGrid2D = "AStarGrid2D",
    .AcceptDialog = "AcceptDialog",
    .AnimatableBody2D = "AnimatableBody2D",
    .AnimatableBody3D = "AnimatableBody3D",
    .AnimatedSprite2D = "AnimatedSprite2D",
    .AnimatedSprite3D = "AnimatedSprite3D",
    .AnimatedTexture = "AnimatedTexture",
    .Animation = "Animation",
    .AnimationLibrary = "AnimationLibrary",
    .AnimationMixer = "AnimationMixer",
    .AnimationNode = "AnimationNode",
    .AnimationNodeAdd2 = "AnimationNodeAdd2",
    .AnimationNodeAdd3 = "AnimationNodeAdd3",
    .AnimationNodeAnimation = "AnimationNodeAnimation",
    .AnimationNodeBlend2 = "AnimationNodeBlend2",
    .AnimationNodeBlend3 = "AnimationNodeBlend3",
    .AnimationNodeBlendSpace1D = "AnimationNodeBlendSpace1D",
    .AnimationNodeBlendSpace2D = "AnimationNodeBlendSpace2D",
    .AnimationNodeBlendTree = "AnimationNodeBlendTree",
    .AnimationNodeExtension = "AnimationNodeExtension",
    .AnimationNodeOneShot = "AnimationNodeOneShot",
    .AnimationNodeOutput = "AnimationNodeOutput",
    .AnimationNodeStateMachine = "AnimationNodeStateMachine",
    .AnimationNodeStateMachinePlayback = "AnimationNodeStateMachinePlayback",
    .AnimationNodeStateMachineTransition = "AnimationNodeStateMachineTransition",
    .AnimationNodeSub2 = "AnimationNodeSub2",
    .AnimationNodeSync = "AnimationNodeSync",
    .AnimationNodeTimeScale = "AnimationNodeTimeScale",
    .AnimationNodeTimeSeek = "AnimationNodeTimeSeek",
    .AnimationNodeTransition = "AnimationNodeTransition",
    .AnimationPlayer = "AnimationPlayer",
    .AnimationRootNode = "AnimationRootNode",
    .AnimationTree = "AnimationTree",
    .Area2D = "Area2D",
    .Area3D = "Area3D",
    .ArrayMesh = "ArrayMesh",
    .ArrayOccluder3D = "ArrayOccluder3D",
    .AspectRatioContainer = "AspectRatioContainer",
    .AtlasTexture = "AtlasTexture",
    .AudioBusLayout = "AudioBusLayout",
    .AudioEffect = "AudioEffect",
    .AudioEffectAmplify = "AudioEffectAmplify",
    .AudioEffectBandLimitFilter = "AudioEffectBandLimitFilter",
    .AudioEffectBandPassFilter = "AudioEffectBandPassFilter",
    .AudioEffectCapture = "AudioEffectCapture",
    .AudioEffectChorus = "AudioEffectChorus",
    .AudioEffectCompressor = "AudioEffectCompressor",
    .AudioEffectDelay = "AudioEffectDelay",
    .AudioEffectDistortion = "AudioEffectDistortion",
    .AudioEffectEQ = "AudioEffectEQ",
    .AudioEffectEQ10 = "AudioEffectEQ10",
    .AudioEffectEQ21 = "AudioEffectEQ21",
    .AudioEffectEQ6 = "AudioEffectEQ6",
    .AudioEffectFilter = "AudioEffectFilter",
    .AudioEffectHardLimiter = "AudioEffectHardLimiter",
    .AudioEffectHighPassFilter = "AudioEffectHighPassFilter",
    .AudioEffectHighShelfFilter = "AudioEffectHighShelfFilter",
    .AudioEffectInstance = "AudioEffectInstance",
    .AudioEffectLimiter = "AudioEffectLimiter",
    .AudioEffectLowPassFilter = "AudioEffectLowPassFilter",
    .AudioEffectLowShelfFilter = "AudioEffectLowShelfFilter",
    .AudioEffectNotchFilter = "AudioEffectNotchFilter",
    .AudioEffectPanner = "AudioEffectPanner",
    .AudioEffectPhaser = "AudioEffectPhaser",
    .AudioEffectPitchShift = "AudioEffectPitchShift",
    .AudioEffectRecord = "AudioEffectRecord",
    .AudioEffectReverb = "AudioEffectReverb",
    .AudioEffectSpectrumAnalyzer = "AudioEffectSpectrumAnalyzer",
    .AudioEffectSpectrumAnalyzerInstance = "AudioEffectSpectrumAnalyzerInstance",
    .AudioEffectStereoEnhance = "AudioEffectStereoEnhance",
    .AudioListener2D = "AudioListener2D",
    .AudioListener3D = "AudioListener3D",
    .AudioSample = "AudioSample",
    .AudioSamplePlayback = "AudioSamplePlayback",
    .AudioServer = "AudioServer",
    .AudioStream = "AudioStream",
    .AudioStreamGenerator = "AudioStreamGenerator",
    .AudioStreamGeneratorPlayback = "AudioStreamGeneratorPlayback",
    .AudioStreamInteractive = "AudioStreamInteractive",
    .AudioStreamMP3 = "AudioStreamMP3",
    .AudioStreamMicrophone = "AudioStreamMicrophone",
    .AudioStreamOggVorbis = "AudioStreamOggVorbis",
    .AudioStreamPlayback = "AudioStreamPlayback",
    .AudioStreamPlaybackInteractive = "AudioStreamPlaybackInteractive",
    .AudioStreamPlaybackOggVorbis = "AudioStreamPlaybackOggVorbis",
    .AudioStreamPlaybackPlaylist = "AudioStreamPlaybackPlaylist",
    .AudioStreamPlaybackPolyphonic = "AudioStreamPlaybackPolyphonic",
    .AudioStreamPlaybackResampled = "AudioStreamPlaybackResampled",
    .AudioStreamPlaybackSynchronized = "AudioStreamPlaybackSynchronized",
    .AudioStreamPlayer = "AudioStreamPlayer",
    .AudioStreamPlayer2D = "AudioStreamPlayer2D",
    .AudioStreamPlayer3D = "AudioStreamPlayer3D",
    .AudioStreamPlaylist = "AudioStreamPlaylist",
    .AudioStreamPolyphonic = "AudioStreamPolyphonic",
    .AudioStreamRandomizer = "AudioStreamRandomizer",
    .AudioStreamSynchronized = "AudioStreamSynchronized",
    .AudioStreamWAV = "AudioStreamWAV",
    .BackBufferCopy = "BackBufferCopy",
    .BaseButton = "BaseButton",
    .BaseMaterial3D = "BaseMaterial3D",
    .BitMap = "BitMap",
    .Bone2D = "Bone2D",
    .BoneAttachment3D = "BoneAttachment3D",
    .BoneMap = "BoneMap",
    .BoxContainer = "BoxContainer",
    .BoxMesh = "BoxMesh",
    .BoxOccluder3D = "BoxOccluder3D",
    .BoxShape3D = "BoxShape3D",
    .Button = "Button",
    .ButtonGroup = "ButtonGroup",
    .CPUParticles2D = "CPUParticles2D",
    .CPUParticles3D = "CPUParticles3D",
    .CSGBox3D = "CSGBox3D",
    .CSGCombiner3D = "CSGCombiner3D",
    .CSGCylinder3D = "CSGCylinder3D",
    .CSGMesh3D = "CSGMesh3D",
    .CSGPolygon3D = "CSGPolygon3D",
    .CSGPrimitive3D = "CSGPrimitive3D",
    .CSGShape3D = "CSGShape3D",
    .CSGSphere3D = "CSGSphere3D",
    .CSGTorus3D = "CSGTorus3D",
    .CallbackTweener = "CallbackTweener",
    .Camera2D = "Camera2D",
    .Camera3D = "Camera3D",
    .CameraAttributes = "CameraAttributes",
    .CameraAttributesPhysical = "CameraAttributesPhysical",
    .CameraAttributesPractical = "CameraAttributesPractical",
    .CameraFeed = "CameraFeed",
    .CameraServer = "CameraServer",
    .CameraTexture = "CameraTexture",
    .CanvasGroup = "CanvasGroup",
    .CanvasItem = "CanvasItem",
    .CanvasItemMaterial = "CanvasItemMaterial",
    .CanvasLayer = "CanvasLayer",
    .CanvasModulate = "CanvasModulate",
    .CanvasTexture = "CanvasTexture",
    .CapsuleMesh = "CapsuleMesh",
    .CapsuleShape2D = "CapsuleShape2D",
    .CapsuleShape3D = "CapsuleShape3D",
    .CenterContainer = "CenterContainer",
    .CharFXTransform = "CharFXTransform",
    .CharacterBody2D = "CharacterBody2D",
    .CharacterBody3D = "CharacterBody3D",
    .CheckBox = "CheckBox",
    .CheckButton = "CheckButton",
    .CircleShape2D = "CircleShape2D",
    .ClassDB = "ClassDB",
    .CodeEdit = "CodeEdit",
    .CodeHighlighter = "CodeHighlighter",
    .CollisionObject2D = "CollisionObject2D",
    .CollisionObject3D = "CollisionObject3D",
    .CollisionPolygon2D = "CollisionPolygon2D",
    .CollisionPolygon3D = "CollisionPolygon3D",
    .CollisionShape2D = "CollisionShape2D",
    .CollisionShape3D = "CollisionShape3D",
    .ColorPalette = "ColorPalette",
    .ColorPicker = "ColorPicker",
    .ColorPickerButton = "ColorPickerButton",
    .ColorRect = "ColorRect",
    .Compositor = "Compositor",
    .CompositorEffect = "CompositorEffect",
    .CompressedCubemap = "CompressedCubemap",
    .CompressedCubemapArray = "CompressedCubemapArray",
    .CompressedTexture2D = "CompressedTexture2D",
    .CompressedTexture2DArray = "CompressedTexture2DArray",
    .CompressedTexture3D = "CompressedTexture3D",
    .CompressedTextureLayered = "CompressedTextureLayered",
    .ConcavePolygonShape2D = "ConcavePolygonShape2D",
    .ConcavePolygonShape3D = "ConcavePolygonShape3D",
    .ConeTwistJoint3D = "ConeTwistJoint3D",
    .ConfigFile = "ConfigFile",
    .ConfirmationDialog = "ConfirmationDialog",
    .Container = "Container",
    .Control = "Control",
    .ConvexPolygonShape2D = "ConvexPolygonShape2D",
    .ConvexPolygonShape3D = "ConvexPolygonShape3D",
    .Crypto = "Crypto",
    .CryptoKey = "CryptoKey",
    .Cubemap = "Cubemap",
    .CubemapArray = "CubemapArray",
    .Curve = "Curve",
    .Curve2D = "Curve2D",
    .Curve3D = "Curve3D",
    .CurveTexture = "CurveTexture",
    .CurveXYZTexture = "CurveXYZTexture",
    .CylinderMesh = "CylinderMesh",
    .CylinderShape3D = "CylinderShape3D",
    .DTLSServer = "DTLSServer",
    .DampedSpringJoint2D = "DampedSpringJoint2D",
    .Decal = "Decal",
    .DirAccess = "DirAccess",
    .DirectionalLight2D = "DirectionalLight2D",
    .DirectionalLight3D = "DirectionalLight3D",
    .DisplayServer = "DisplayServer",
    .ENetConnection = "ENetConnection",
    .ENetMultiplayerPeer = "ENetMultiplayerPeer",
    .ENetPacketPeer = "ENetPacketPeer",
    .EditorCommandPalette = "EditorCommandPalette",
    .EditorContextMenuPlugin = "EditorContextMenuPlugin",
    .EditorDebuggerPlugin = "EditorDebuggerPlugin",
    .EditorDebuggerSession = "EditorDebuggerSession",
    .EditorExportPlatform = "EditorExportPlatform",
    .EditorExportPlatformAndroid = "EditorExportPlatformAndroid",
    .EditorExportPlatformExtension = "EditorExportPlatformExtension",
    .EditorExportPlatformIOS = "EditorExportPlatformIOS",
    .EditorExportPlatformLinuxBSD = "EditorExportPlatformLinuxBSD",
    .EditorExportPlatformMacOS = "EditorExportPlatformMacOS",
    .EditorExportPlatformPC = "EditorExportPlatformPC",
    .EditorExportPlatformWeb = "EditorExportPlatformWeb",
    .EditorExportPlatformWindows = "EditorExportPlatformWindows",
    .EditorExportPlugin = "EditorExportPlugin",
    .EditorExportPreset = "EditorExportPreset",
    .EditorFeatureProfile = "EditorFeatureProfile",
    .EditorFileDialog = "EditorFileDialog",
    .EditorFileSystem = "EditorFileSystem",
    .EditorFileSystemDirectory = "EditorFileSystemDirectory",
    .EditorFileSystemImportFormatSupportQuery = "EditorFileSystemImportFormatSupportQuery",
    .EditorImportPlugin = "EditorImportPlugin",
    .EditorInspector = "EditorInspector",
    .EditorInspectorPlugin = "EditorInspectorPlugin",
    .EditorInterface = "EditorInterface",
    .EditorNode3DGizmo = "EditorNode3DGizmo",
    .EditorNode3DGizmoPlugin = "EditorNode3DGizmoPlugin",
    .EditorPaths = "EditorPaths",
    .EditorPlugin = "EditorPlugin",
    .EditorProperty = "EditorProperty",
    .EditorResourceConversionPlugin = "EditorResourceConversionPlugin",
    .EditorResourcePicker = "EditorResourcePicker",
    .EditorResourcePreview = "EditorResourcePreview",
    .EditorResourcePreviewGenerator = "EditorResourcePreviewGenerator",
    .EditorResourceTooltipPlugin = "EditorResourceTooltipPlugin",
    .EditorSceneFormatImporter = "EditorSceneFormatImporter",
    .EditorSceneFormatImporterBlend = "EditorSceneFormatImporterBlend",
    .EditorSceneFormatImporterFBX2GLTF = "EditorSceneFormatImporterFBX2GLTF",
    .EditorSceneFormatImporterGLTF = "EditorSceneFormatImporterGLTF",
    .EditorSceneFormatImporterUFBX = "EditorSceneFormatImporterUFBX",
    .EditorScenePostImport = "EditorScenePostImport",
    .EditorScenePostImportPlugin = "EditorScenePostImportPlugin",
    .EditorScript = "EditorScript",
    .EditorScriptPicker = "EditorScriptPicker",
    .EditorSelection = "EditorSelection",
    .EditorSettings = "EditorSettings",
    .EditorSpinSlider = "EditorSpinSlider",
    .EditorSyntaxHighlighter = "EditorSyntaxHighlighter",
    .EditorToaster = "EditorToaster",
    .EditorTranslationParserPlugin = "EditorTranslationParserPlugin",
    .EditorUndoRedoManager = "EditorUndoRedoManager",
    .EditorVCSInterface = "EditorVCSInterface",
    .EncodedObjectAsID = "EncodedObjectAsID",
    .Engine = "Engine",
    .EngineDebugger = "EngineDebugger",
    .EngineProfiler = "EngineProfiler",
    .Environment = "Environment",
    .Expression = "Expression",
    .ExternalTexture = "ExternalTexture",
    .FBXDocument = "FBXDocument",
    .FBXState = "FBXState",
    .FastNoiseLite = "FastNoiseLite",
    .FileAccess = "FileAccess",
    .FileDialog = "FileDialog",
    .FileSystemDock = "FileSystemDock",
    .FlowContainer = "FlowContainer",
    .FogMaterial = "FogMaterial",
    .FogVolume = "FogVolume",
    .Font = "Font",
    .FontFile = "FontFile",
    .FontVariation = "FontVariation",
    .FramebufferCacheRD = "FramebufferCacheRD",
    .GDExtension = "GDExtension",
    .GDExtensionManager = "GDExtensionManager",
    .GDScript = "GDScript",
    .GDScriptSyntaxHighlighter = "GDScriptSyntaxHighlighter",
    .GLTFAccessor = "GLTFAccessor",
    .GLTFAnimation = "GLTFAnimation",
    .GLTFBufferView = "GLTFBufferView",
    .GLTFCamera = "GLTFCamera",
    .GLTFDocument = "GLTFDocument",
    .GLTFDocumentExtension = "GLTFDocumentExtension",
    .GLTFDocumentExtensionConvertImporterMesh = "GLTFDocumentExtensionConvertImporterMesh",
    .GLTFLight = "GLTFLight",
    .GLTFMesh = "GLTFMesh",
    .GLTFNode = "GLTFNode",
    .GLTFObjectModelProperty = "GLTFObjectModelProperty",
    .GLTFPhysicsBody = "GLTFPhysicsBody",
    .GLTFPhysicsShape = "GLTFPhysicsShape",
    .GLTFSkeleton = "GLTFSkeleton",
    .GLTFSkin = "GLTFSkin",
    .GLTFSpecGloss = "GLTFSpecGloss",
    .GLTFState = "GLTFState",
    .GLTFTexture = "GLTFTexture",
    .GLTFTextureSampler = "GLTFTextureSampler",
    .GPUParticles2D = "GPUParticles2D",
    .GPUParticles3D = "GPUParticles3D",
    .GPUParticlesAttractor3D = "GPUParticlesAttractor3D",
    .GPUParticlesAttractorBox3D = "GPUParticlesAttractorBox3D",
    .GPUParticlesAttractorSphere3D = "GPUParticlesAttractorSphere3D",
    .GPUParticlesAttractorVectorField3D = "GPUParticlesAttractorVectorField3D",
    .GPUParticlesCollision3D = "GPUParticlesCollision3D",
    .GPUParticlesCollisionBox3D = "GPUParticlesCollisionBox3D",
    .GPUParticlesCollisionHeightField3D = "GPUParticlesCollisionHeightField3D",
    .GPUParticlesCollisionSDF3D = "GPUParticlesCollisionSDF3D",
    .GPUParticlesCollisionSphere3D = "GPUParticlesCollisionSphere3D",
    .Generic6DOFJoint3D = "Generic6DOFJoint3D",
    .Geometry2D = "Geometry2D",
    .Geometry3D = "Geometry3D",
    .GeometryInstance3D = "GeometryInstance3D",
    .Gradient = "Gradient",
    .GradientTexture1D = "GradientTexture1D",
    .GradientTexture2D = "GradientTexture2D",
    .GraphEdit = "GraphEdit",
    .GraphElement = "GraphElement",
    .GraphFrame = "GraphFrame",
    .GraphNode = "GraphNode",
    .GridContainer = "GridContainer",
    .GridMap = "GridMap",
    .GridMapEditorPlugin = "GridMapEditorPlugin",
    .GrooveJoint2D = "GrooveJoint2D",
    .HBoxContainer = "HBoxContainer",
    .HFlowContainer = "HFlowContainer",
    .HMACContext = "HMACContext",
    .HScrollBar = "HScrollBar",
    .HSeparator = "HSeparator",
    .HSlider = "HSlider",
    .HSplitContainer = "HSplitContainer",
    .HTTPClient = "HTTPClient",
    .HTTPRequest = "HTTPRequest",
    .HashingContext = "HashingContext",
    .HeightMapShape3D = "HeightMapShape3D",
    .HingeJoint3D = "HingeJoint3D",
    .IP = "IP",
    .Image = "Image",
    .ImageFormatLoader = "ImageFormatLoader",
    .ImageFormatLoaderExtension = "ImageFormatLoaderExtension",
    .ImageTexture = "ImageTexture",
    .ImageTexture3D = "ImageTexture3D",
    .ImageTextureLayered = "ImageTextureLayered",
    .ImmediateMesh = "ImmediateMesh",
    .ImporterMesh = "ImporterMesh",
    .ImporterMeshInstance3D = "ImporterMeshInstance3D",
    .Input = "Input",
    .InputEvent = "InputEvent",
    .InputEventAction = "InputEventAction",
    .InputEventFromWindow = "InputEventFromWindow",
    .InputEventGesture = "InputEventGesture",
    .InputEventJoypadButton = "InputEventJoypadButton",
    .InputEventJoypadMotion = "InputEventJoypadMotion",
    .InputEventKey = "InputEventKey",
    .InputEventMIDI = "InputEventMIDI",
    .InputEventMagnifyGesture = "InputEventMagnifyGesture",
    .InputEventMouse = "InputEventMouse",
    .InputEventMouseButton = "InputEventMouseButton",
    .InputEventMouseMotion = "InputEventMouseMotion",
    .InputEventPanGesture = "InputEventPanGesture",
    .InputEventScreenDrag = "InputEventScreenDrag",
    .InputEventScreenTouch = "InputEventScreenTouch",
    .InputEventShortcut = "InputEventShortcut",
    .InputEventWithModifiers = "InputEventWithModifiers",
    .InputMap = "InputMap",
    .InstancePlaceholder = "InstancePlaceholder",
    .IntervalTweener = "IntervalTweener",
    .ItemList = "ItemList",
    .JNISingleton = "JNISingleton",
    .JSON = "JSON",
    .JSONRPC = "JSONRPC",
    .JavaClass = "JavaClass",
    .JavaClassWrapper = "JavaClassWrapper",
    .JavaObject = "JavaObject",
    .JavaScriptBridge = "JavaScriptBridge",
    .JavaScriptObject = "JavaScriptObject",
    .Joint2D = "Joint2D",
    .Joint3D = "Joint3D",
    .KinematicCollision2D = "KinematicCollision2D",
    .KinematicCollision3D = "KinematicCollision3D",
    .Label = "Label",
    .Label3D = "Label3D",
    .LabelSettings = "LabelSettings",
    .Light2D = "Light2D",
    .Light3D = "Light3D",
    .LightOccluder2D = "LightOccluder2D",
    .LightmapGI = "LightmapGI",
    .LightmapGIData = "LightmapGIData",
    .LightmapProbe = "LightmapProbe",
    .Lightmapper = "Lightmapper",
    .LightmapperRD = "LightmapperRD",
    .Line2D = "Line2D",
    .LineEdit = "LineEdit",
    .LinkButton = "LinkButton",
    .LookAtModifier3D = "LookAtModifier3D",
    .MainLoop = "MainLoop",
    .MarginContainer = "MarginContainer",
    .Marker2D = "Marker2D",
    .Marker3D = "Marker3D",
    .Marshalls = "Marshalls",
    .Material = "Material",
    .MenuBar = "MenuBar",
    .MenuButton = "MenuButton",
    .Mesh = "Mesh",
    .MeshConvexDecompositionSettings = "MeshConvexDecompositionSettings",
    .MeshDataTool = "MeshDataTool",
    .MeshInstance2D = "MeshInstance2D",
    .MeshInstance3D = "MeshInstance3D",
    .MeshLibrary = "MeshLibrary",
    .MeshTexture = "MeshTexture",
    .MethodTweener = "MethodTweener",
    .MissingNode = "MissingNode",
    .MissingResource = "MissingResource",
    .MobileVRInterface = "MobileVRInterface",
    .MovieWriter = "MovieWriter",
    .MultiMesh = "MultiMesh",
    .MultiMeshInstance2D = "MultiMeshInstance2D",
    .MultiMeshInstance3D = "MultiMeshInstance3D",
    .MultiplayerAPI = "MultiplayerAPI",
    .MultiplayerAPIExtension = "MultiplayerAPIExtension",
    .MultiplayerPeer = "MultiplayerPeer",
    .MultiplayerPeerExtension = "MultiplayerPeerExtension",
    .MultiplayerSpawner = "MultiplayerSpawner",
    .MultiplayerSynchronizer = "MultiplayerSynchronizer",
    .Mutex = "Mutex",
    .NativeMenu = "NativeMenu",
    .NavigationAgent2D = "NavigationAgent2D",
    .NavigationAgent3D = "NavigationAgent3D",
    .NavigationLink2D = "NavigationLink2D",
    .NavigationLink3D = "NavigationLink3D",
    .NavigationMesh = "NavigationMesh",
    .NavigationMeshGenerator = "NavigationMeshGenerator",
    .NavigationMeshSourceGeometryData2D = "NavigationMeshSourceGeometryData2D",
    .NavigationMeshSourceGeometryData3D = "NavigationMeshSourceGeometryData3D",
    .NavigationObstacle2D = "NavigationObstacle2D",
    .NavigationObstacle3D = "NavigationObstacle3D",
    .NavigationPathQueryParameters2D = "NavigationPathQueryParameters2D",
    .NavigationPathQueryParameters3D = "NavigationPathQueryParameters3D",
    .NavigationPathQueryResult2D = "NavigationPathQueryResult2D",
    .NavigationPathQueryResult3D = "NavigationPathQueryResult3D",
    .NavigationPolygon = "NavigationPolygon",
    .NavigationRegion2D = "NavigationRegion2D",
    .NavigationRegion3D = "NavigationRegion3D",
    .NavigationServer2D = "NavigationServer2D",
    .NavigationServer3D = "NavigationServer3D",
    .NinePatchRect = "NinePatchRect",
    .Node = "Node",
    .Node2D = "Node2D",
    .Node3D = "Node3D",
    .Node3DGizmo = "Node3DGizmo",
    .Noise = "Noise",
    .NoiseTexture2D = "NoiseTexture2D",
    .NoiseTexture3D = "NoiseTexture3D",
    .ORMMaterial3D = "ORMMaterial3D",
    .OS = "OS",
    .Object = "Object",
    .Occluder3D = "Occluder3D",
    .OccluderInstance3D = "OccluderInstance3D",
    .OccluderPolygon2D = "OccluderPolygon2D",
    .OfflineMultiplayerPeer = "OfflineMultiplayerPeer",
    .OggPacketSequence = "OggPacketSequence",
    .OggPacketSequencePlayback = "OggPacketSequencePlayback",
    .OmniLight3D = "OmniLight3D",
    .OpenXRAPIExtension = "OpenXRAPIExtension",
    .OpenXRAction = "OpenXRAction",
    .OpenXRActionBindingModifier = "OpenXRActionBindingModifier",
    .OpenXRActionMap = "OpenXRActionMap",
    .OpenXRActionSet = "OpenXRActionSet",
    .OpenXRAnalogThresholdModifier = "OpenXRAnalogThresholdModifier",
    .OpenXRBindingModifier = "OpenXRBindingModifier",
    .OpenXRBindingModifierEditor = "OpenXRBindingModifierEditor",
    .OpenXRCompositionLayer = "OpenXRCompositionLayer",
    .OpenXRCompositionLayerCylinder = "OpenXRCompositionLayerCylinder",
    .OpenXRCompositionLayerEquirect = "OpenXRCompositionLayerEquirect",
    .OpenXRCompositionLayerQuad = "OpenXRCompositionLayerQuad",
    .OpenXRDpadBindingModifier = "OpenXRDpadBindingModifier",
    .OpenXRExtensionWrapperExtension = "OpenXRExtensionWrapperExtension",
    .OpenXRHand = "OpenXRHand",
    .OpenXRHapticBase = "OpenXRHapticBase",
    .OpenXRHapticVibration = "OpenXRHapticVibration",
    .OpenXRIPBinding = "OpenXRIPBinding",
    .OpenXRIPBindingModifier = "OpenXRIPBindingModifier",
    .OpenXRInteractionProfile = "OpenXRInteractionProfile",
    .OpenXRInteractionProfileEditor = "OpenXRInteractionProfileEditor",
    .OpenXRInteractionProfileEditorBase = "OpenXRInteractionProfileEditorBase",
    .OpenXRInteractionProfileMetadata = "OpenXRInteractionProfileMetadata",
    .OpenXRInterface = "OpenXRInterface",
    .OpenXRVisibilityMask = "OpenXRVisibilityMask",
    .OptimizedTranslation = "OptimizedTranslation",
    .OptionButton = "OptionButton",
    .PCKPacker = "PCKPacker",
    .PackedDataContainer = "PackedDataContainer",
    .PackedDataContainerRef = "PackedDataContainerRef",
    .PackedScene = "PackedScene",
    .PacketPeer = "PacketPeer",
    .PacketPeerDTLS = "PacketPeerDTLS",
    .PacketPeerExtension = "PacketPeerExtension",
    .PacketPeerStream = "PacketPeerStream",
    .PacketPeerUDP = "PacketPeerUDP",
    .Panel = "Panel",
    .PanelContainer = "PanelContainer",
    .PanoramaSkyMaterial = "PanoramaSkyMaterial",
    .Parallax2D = "Parallax2D",
    .ParallaxBackground = "ParallaxBackground",
    .ParallaxLayer = "ParallaxLayer",
    .ParticleProcessMaterial = "ParticleProcessMaterial",
    .Path2D = "Path2D",
    .Path3D = "Path3D",
    .PathFollow2D = "PathFollow2D",
    .PathFollow3D = "PathFollow3D",
    .Performance = "Performance",
    .PhysicalBone2D = "PhysicalBone2D",
    .PhysicalBone3D = "PhysicalBone3D",
    .PhysicalBoneSimulator3D = "PhysicalBoneSimulator3D",
    .PhysicalSkyMaterial = "PhysicalSkyMaterial",
    .PhysicsBody2D = "PhysicsBody2D",
    .PhysicsBody3D = "PhysicsBody3D",
    .PhysicsDirectBodyState2D = "PhysicsDirectBodyState2D",
    .PhysicsDirectBodyState2DExtension = "PhysicsDirectBodyState2DExtension",
    .PhysicsDirectBodyState3D = "PhysicsDirectBodyState3D",
    .PhysicsDirectBodyState3DExtension = "PhysicsDirectBodyState3DExtension",
    .PhysicsDirectSpaceState2D = "PhysicsDirectSpaceState2D",
    .PhysicsDirectSpaceState2DExtension = "PhysicsDirectSpaceState2DExtension",
    .PhysicsDirectSpaceState3D = "PhysicsDirectSpaceState3D",
    .PhysicsDirectSpaceState3DExtension = "PhysicsDirectSpaceState3DExtension",
    .PhysicsMaterial = "PhysicsMaterial",
    .PhysicsPointQueryParameters2D = "PhysicsPointQueryParameters2D",
    .PhysicsPointQueryParameters3D = "PhysicsPointQueryParameters3D",
    .PhysicsRayQueryParameters2D = "PhysicsRayQueryParameters2D",
    .PhysicsRayQueryParameters3D = "PhysicsRayQueryParameters3D",
    .PhysicsServer2D = "PhysicsServer2D",
    .PhysicsServer2DExtension = "PhysicsServer2DExtension",
    .PhysicsServer2DManager = "PhysicsServer2DManager",
    .PhysicsServer3D = "PhysicsServer3D",
    .PhysicsServer3DExtension = "PhysicsServer3DExtension",
    .PhysicsServer3DManager = "PhysicsServer3DManager",
    .PhysicsServer3DRenderingServerHandler = "PhysicsServer3DRenderingServerHandler",
    .PhysicsShapeQueryParameters2D = "PhysicsShapeQueryParameters2D",
    .PhysicsShapeQueryParameters3D = "PhysicsShapeQueryParameters3D",
    .PhysicsTestMotionParameters2D = "PhysicsTestMotionParameters2D",
    .PhysicsTestMotionParameters3D = "PhysicsTestMotionParameters3D",
    .PhysicsTestMotionResult2D = "PhysicsTestMotionResult2D",
    .PhysicsTestMotionResult3D = "PhysicsTestMotionResult3D",
    .PinJoint2D = "PinJoint2D",
    .PinJoint3D = "PinJoint3D",
    .PlaceholderCubemap = "PlaceholderCubemap",
    .PlaceholderCubemapArray = "PlaceholderCubemapArray",
    .PlaceholderMaterial = "PlaceholderMaterial",
    .PlaceholderMesh = "PlaceholderMesh",
    .PlaceholderTexture2D = "PlaceholderTexture2D",
    .PlaceholderTexture2DArray = "PlaceholderTexture2DArray",
    .PlaceholderTexture3D = "PlaceholderTexture3D",
    .PlaceholderTextureLayered = "PlaceholderTextureLayered",
    .PlaneMesh = "PlaneMesh",
    .PointLight2D = "PointLight2D",
    .PointMesh = "PointMesh",
    .Polygon2D = "Polygon2D",
    .PolygonOccluder3D = "PolygonOccluder3D",
    .PolygonPathFinder = "PolygonPathFinder",
    .Popup = "Popup",
    .PopupMenu = "PopupMenu",
    .PopupPanel = "PopupPanel",
    .PortableCompressedTexture2D = "PortableCompressedTexture2D",
    .PrimitiveMesh = "PrimitiveMesh",
    .PrismMesh = "PrismMesh",
    .ProceduralSkyMaterial = "ProceduralSkyMaterial",
    .ProgressBar = "ProgressBar",
    .ProjectSettings = "ProjectSettings",
    .PropertyTweener = "PropertyTweener",
    .QuadMesh = "QuadMesh",
    .QuadOccluder3D = "QuadOccluder3D",
    .RDAttachmentFormat = "RDAttachmentFormat",
    .RDFramebufferPass = "RDFramebufferPass",
    .RDPipelineColorBlendState = "RDPipelineColorBlendState",
    .RDPipelineColorBlendStateAttachment = "RDPipelineColorBlendStateAttachment",
    .RDPipelineDepthStencilState = "RDPipelineDepthStencilState",
    .RDPipelineMultisampleState = "RDPipelineMultisampleState",
    .RDPipelineRasterizationState = "RDPipelineRasterizationState",
    .RDPipelineSpecializationConstant = "RDPipelineSpecializationConstant",
    .RDSamplerState = "RDSamplerState",
    .RDShaderFile = "RDShaderFile",
    .RDShaderSPIRV = "RDShaderSPIRV",
    .RDShaderSource = "RDShaderSource",
    .RDTextureFormat = "RDTextureFormat",
    .RDTextureView = "RDTextureView",
    .RDUniform = "RDUniform",
    .RDVertexAttribute = "RDVertexAttribute",
    .RandomNumberGenerator = "RandomNumberGenerator",
    .Range = "Range",
    .RayCast2D = "RayCast2D",
    .RayCast3D = "RayCast3D",
    .RectangleShape2D = "RectangleShape2D",
    .RefCounted = "RefCounted",
    .ReferenceRect = "ReferenceRect",
    .ReflectionProbe = "ReflectionProbe",
    .RegEx = "RegEx",
    .RegExMatch = "RegExMatch",
    .RemoteTransform2D = "RemoteTransform2D",
    .RemoteTransform3D = "RemoteTransform3D",
    .RenderData = "RenderData",
    .RenderDataExtension = "RenderDataExtension",
    .RenderDataRD = "RenderDataRD",
    .RenderSceneBuffers = "RenderSceneBuffers",
    .RenderSceneBuffersConfiguration = "RenderSceneBuffersConfiguration",
    .RenderSceneBuffersExtension = "RenderSceneBuffersExtension",
    .RenderSceneBuffersRD = "RenderSceneBuffersRD",
    .RenderSceneData = "RenderSceneData",
    .RenderSceneDataExtension = "RenderSceneDataExtension",
    .RenderSceneDataRD = "RenderSceneDataRD",
    .RenderingDevice = "RenderingDevice",
    .RenderingServer = "RenderingServer",
    .Resource = "Resource",
    .ResourceFormatLoader = "ResourceFormatLoader",
    .ResourceFormatSaver = "ResourceFormatSaver",
    .ResourceImporter = "ResourceImporter",
    .ResourceImporterBMFont = "ResourceImporterBMFont",
    .ResourceImporterBitMap = "ResourceImporterBitMap",
    .ResourceImporterCSVTranslation = "ResourceImporterCSVTranslation",
    .ResourceImporterDynamicFont = "ResourceImporterDynamicFont",
    .ResourceImporterImage = "ResourceImporterImage",
    .ResourceImporterImageFont = "ResourceImporterImageFont",
    .ResourceImporterLayeredTexture = "ResourceImporterLayeredTexture",
    .ResourceImporterMP3 = "ResourceImporterMP3",
    .ResourceImporterOBJ = "ResourceImporterOBJ",
    .ResourceImporterOggVorbis = "ResourceImporterOggVorbis",
    .ResourceImporterScene = "ResourceImporterScene",
    .ResourceImporterShaderFile = "ResourceImporterShaderFile",
    .ResourceImporterTexture = "ResourceImporterTexture",
    .ResourceImporterTextureAtlas = "ResourceImporterTextureAtlas",
    .ResourceImporterWAV = "ResourceImporterWAV",
    .ResourceLoader = "ResourceLoader",
    .ResourcePreloader = "ResourcePreloader",
    .ResourceSaver = "ResourceSaver",
    .ResourceUID = "ResourceUID",
    .RetargetModifier3D = "RetargetModifier3D",
    .RibbonTrailMesh = "RibbonTrailMesh",
    .RichTextEffect = "RichTextEffect",
    .RichTextLabel = "RichTextLabel",
    .RigidBody2D = "RigidBody2D",
    .RigidBody3D = "RigidBody3D",
    .RootMotionView = "RootMotionView",
    .SceneMultiplayer = "SceneMultiplayer",
    .SceneReplicationConfig = "SceneReplicationConfig",
    .SceneState = "SceneState",
    .SceneTree = "SceneTree",
    .SceneTreeTimer = "SceneTreeTimer",
    .Script = "Script",
    .ScriptCreateDialog = "ScriptCreateDialog",
    .ScriptEditor = "ScriptEditor",
    .ScriptEditorBase = "ScriptEditorBase",
    .ScriptExtension = "ScriptExtension",
    .ScriptLanguage = "ScriptLanguage",
    .ScriptLanguageExtension = "ScriptLanguageExtension",
    .ScrollBar = "ScrollBar",
    .ScrollContainer = "ScrollContainer",
    .SegmentShape2D = "SegmentShape2D",
    .Semaphore = "Semaphore",
    .SeparationRayShape2D = "SeparationRayShape2D",
    .SeparationRayShape3D = "SeparationRayShape3D",
    .Separator = "Separator",
    .Shader = "Shader",
    .ShaderGlobalsOverride = "ShaderGlobalsOverride",
    .ShaderInclude = "ShaderInclude",
    .ShaderIncludeDB = "ShaderIncludeDB",
    .ShaderMaterial = "ShaderMaterial",
    .Shape2D = "Shape2D",
    .Shape3D = "Shape3D",
    .ShapeCast2D = "ShapeCast2D",
    .ShapeCast3D = "ShapeCast3D",
    .Shortcut = "Shortcut",
    .Skeleton2D = "Skeleton2D",
    .Skeleton3D = "Skeleton3D",
    .SkeletonIK3D = "SkeletonIK3D",
    .SkeletonModification2D = "SkeletonModification2D",
    .SkeletonModification2DCCDIK = "SkeletonModification2DCCDIK",
    .SkeletonModification2DFABRIK = "SkeletonModification2DFABRIK",
    .SkeletonModification2DJiggle = "SkeletonModification2DJiggle",
    .SkeletonModification2DLookAt = "SkeletonModification2DLookAt",
    .SkeletonModification2DPhysicalBones = "SkeletonModification2DPhysicalBones",
    .SkeletonModification2DStackHolder = "SkeletonModification2DStackHolder",
    .SkeletonModification2DTwoBoneIK = "SkeletonModification2DTwoBoneIK",
    .SkeletonModificationStack2D = "SkeletonModificationStack2D",
    .SkeletonModifier3D = "SkeletonModifier3D",
    .SkeletonProfile = "SkeletonProfile",
    .SkeletonProfileHumanoid = "SkeletonProfileHumanoid",
    .Skin = "Skin",
    .SkinReference = "SkinReference",
    .Sky = "Sky",
    .Slider = "Slider",
    .SliderJoint3D = "SliderJoint3D",
    .SoftBody3D = "SoftBody3D",
    .SphereMesh = "SphereMesh",
    .SphereOccluder3D = "SphereOccluder3D",
    .SphereShape3D = "SphereShape3D",
    .SpinBox = "SpinBox",
    .SplitContainer = "SplitContainer",
    .SpotLight3D = "SpotLight3D",
    .SpringArm3D = "SpringArm3D",
    .SpringBoneCollision3D = "SpringBoneCollision3D",
    .SpringBoneCollisionCapsule3D = "SpringBoneCollisionCapsule3D",
    .SpringBoneCollisionPlane3D = "SpringBoneCollisionPlane3D",
    .SpringBoneCollisionSphere3D = "SpringBoneCollisionSphere3D",
    .SpringBoneSimulator3D = "SpringBoneSimulator3D",
    .Sprite2D = "Sprite2D",
    .Sprite3D = "Sprite3D",
    .SpriteBase3D = "SpriteBase3D",
    .SpriteFrames = "SpriteFrames",
    .StandardMaterial3D = "StandardMaterial3D",
    .StaticBody2D = "StaticBody2D",
    .StaticBody3D = "StaticBody3D",
    .StatusIndicator = "StatusIndicator",
    .StreamPeer = "StreamPeer",
    .StreamPeerBuffer = "StreamPeerBuffer",
    .StreamPeerExtension = "StreamPeerExtension",
    .StreamPeerGZIP = "StreamPeerGZIP",
    .StreamPeerTCP = "StreamPeerTCP",
    .StreamPeerTLS = "StreamPeerTLS",
    .StyleBox = "StyleBox",
    .StyleBoxEmpty = "StyleBoxEmpty",
    .StyleBoxFlat = "StyleBoxFlat",
    .StyleBoxLine = "StyleBoxLine",
    .StyleBoxTexture = "StyleBoxTexture",
    .SubViewport = "SubViewport",
    .SubViewportContainer = "SubViewportContainer",
    .SubtweenTweener = "SubtweenTweener",
    .SurfaceTool = "SurfaceTool",
    .SyntaxHighlighter = "SyntaxHighlighter",
    .SystemFont = "SystemFont",
    .TCPServer = "TCPServer",
    .TLSOptions = "TLSOptions",
    .TabBar = "TabBar",
    .TabContainer = "TabContainer",
    .TextEdit = "TextEdit",
    .TextLine = "TextLine",
    .TextMesh = "TextMesh",
    .TextParagraph = "TextParagraph",
    .TextServer = "TextServer",
    .TextServerAdvanced = "TextServerAdvanced",
    .TextServerDummy = "TextServerDummy",
    .TextServerExtension = "TextServerExtension",
    .TextServerManager = "TextServerManager",
    .Texture = "Texture",
    .Texture2D = "Texture2D",
    .Texture2DArray = "Texture2DArray",
    .Texture2DArrayRD = "Texture2DArrayRD",
    .Texture2DRD = "Texture2DRD",
    .Texture3D = "Texture3D",
    .Texture3DRD = "Texture3DRD",
    .TextureButton = "TextureButton",
    .TextureCubemapArrayRD = "TextureCubemapArrayRD",
    .TextureCubemapRD = "TextureCubemapRD",
    .TextureLayered = "TextureLayered",
    .TextureLayeredRD = "TextureLayeredRD",
    .TextureProgressBar = "TextureProgressBar",
    .TextureRect = "TextureRect",
    .Theme = "Theme",
    .ThemeDB = "ThemeDB",
    .Thread = "Thread",
    .TileData = "TileData",
    .TileMap = "TileMap",
    .TileMapLayer = "TileMapLayer",
    .TileMapPattern = "TileMapPattern",
    .TileSet = "TileSet",
    .TileSetAtlasSource = "TileSetAtlasSource",
    .TileSetScenesCollectionSource = "TileSetScenesCollectionSource",
    .TileSetSource = "TileSetSource",
    .Time = "Time",
    .Timer = "Timer",
    .TorusMesh = "TorusMesh",
    .TouchScreenButton = "TouchScreenButton",
    .Translation = "Translation",
    .TranslationDomain = "TranslationDomain",
    .TranslationServer = "TranslationServer",
    .Tree = "Tree",
    .TreeItem = "TreeItem",
    .TriangleMesh = "TriangleMesh",
    .TubeTrailMesh = "TubeTrailMesh",
    .Tween = "Tween",
    .Tweener = "Tweener",
    .UDPServer = "UDPServer",
    .UPNP = "UPNP",
    .UPNPDevice = "UPNPDevice",
    .UndoRedo = "UndoRedo",
    .UniformSetCacheRD = "UniformSetCacheRD",
    .VBoxContainer = "VBoxContainer",
    .VFlowContainer = "VFlowContainer",
    .VScrollBar = "VScrollBar",
    .VSeparator = "VSeparator",
    .VSlider = "VSlider",
    .VSplitContainer = "VSplitContainer",
    .VehicleBody3D = "VehicleBody3D",
    .VehicleWheel3D = "VehicleWheel3D",
    .VideoStream = "VideoStream",
    .VideoStreamPlayback = "VideoStreamPlayback",
    .VideoStreamPlayer = "VideoStreamPlayer",
    .VideoStreamTheora = "VideoStreamTheora",
    .Viewport = "Viewport",
    .ViewportTexture = "ViewportTexture",
    .VisibleOnScreenEnabler2D = "VisibleOnScreenEnabler2D",
    .VisibleOnScreenEnabler3D = "VisibleOnScreenEnabler3D",
    .VisibleOnScreenNotifier2D = "VisibleOnScreenNotifier2D",
    .VisibleOnScreenNotifier3D = "VisibleOnScreenNotifier3D",
    .VisualInstance3D = "VisualInstance3D",
    .VisualShader = "VisualShader",
    .VisualShaderNode = "VisualShaderNode",
    .VisualShaderNodeBillboard = "VisualShaderNodeBillboard",
    .VisualShaderNodeBooleanConstant = "VisualShaderNodeBooleanConstant",
    .VisualShaderNodeBooleanParameter = "VisualShaderNodeBooleanParameter",
    .VisualShaderNodeClamp = "VisualShaderNodeClamp",
    .VisualShaderNodeColorConstant = "VisualShaderNodeColorConstant",
    .VisualShaderNodeColorFunc = "VisualShaderNodeColorFunc",
    .VisualShaderNodeColorOp = "VisualShaderNodeColorOp",
    .VisualShaderNodeColorParameter = "VisualShaderNodeColorParameter",
    .VisualShaderNodeComment = "VisualShaderNodeComment",
    .VisualShaderNodeCompare = "VisualShaderNodeCompare",
    .VisualShaderNodeConstant = "VisualShaderNodeConstant",
    .VisualShaderNodeCubemap = "VisualShaderNodeCubemap",
    .VisualShaderNodeCubemapParameter = "VisualShaderNodeCubemapParameter",
    .VisualShaderNodeCurveTexture = "VisualShaderNodeCurveTexture",
    .VisualShaderNodeCurveXYZTexture = "VisualShaderNodeCurveXYZTexture",
    .VisualShaderNodeCustom = "VisualShaderNodeCustom",
    .VisualShaderNodeDerivativeFunc = "VisualShaderNodeDerivativeFunc",
    .VisualShaderNodeDeterminant = "VisualShaderNodeDeterminant",
    .VisualShaderNodeDistanceFade = "VisualShaderNodeDistanceFade",
    .VisualShaderNodeDotProduct = "VisualShaderNodeDotProduct",
    .VisualShaderNodeExpression = "VisualShaderNodeExpression",
    .VisualShaderNodeFaceForward = "VisualShaderNodeFaceForward",
    .VisualShaderNodeFloatConstant = "VisualShaderNodeFloatConstant",
    .VisualShaderNodeFloatFunc = "VisualShaderNodeFloatFunc",
    .VisualShaderNodeFloatOp = "VisualShaderNodeFloatOp",
    .VisualShaderNodeFloatParameter = "VisualShaderNodeFloatParameter",
    .VisualShaderNodeFrame = "VisualShaderNodeFrame",
    .VisualShaderNodeFresnel = "VisualShaderNodeFresnel",
    .VisualShaderNodeGlobalExpression = "VisualShaderNodeGlobalExpression",
    .VisualShaderNodeGroupBase = "VisualShaderNodeGroupBase",
    .VisualShaderNodeIf = "VisualShaderNodeIf",
    .VisualShaderNodeInput = "VisualShaderNodeInput",
    .VisualShaderNodeIntConstant = "VisualShaderNodeIntConstant",
    .VisualShaderNodeIntFunc = "VisualShaderNodeIntFunc",
    .VisualShaderNodeIntOp = "VisualShaderNodeIntOp",
    .VisualShaderNodeIntParameter = "VisualShaderNodeIntParameter",
    .VisualShaderNodeIs = "VisualShaderNodeIs",
    .VisualShaderNodeLinearSceneDepth = "VisualShaderNodeLinearSceneDepth",
    .VisualShaderNodeMix = "VisualShaderNodeMix",
    .VisualShaderNodeMultiplyAdd = "VisualShaderNodeMultiplyAdd",
    .VisualShaderNodeOuterProduct = "VisualShaderNodeOuterProduct",
    .VisualShaderNodeOutput = "VisualShaderNodeOutput",
    .VisualShaderNodeParameter = "VisualShaderNodeParameter",
    .VisualShaderNodeParameterRef = "VisualShaderNodeParameterRef",
    .VisualShaderNodeParticleAccelerator = "VisualShaderNodeParticleAccelerator",
    .VisualShaderNodeParticleBoxEmitter = "VisualShaderNodeParticleBoxEmitter",
    .VisualShaderNodeParticleConeVelocity = "VisualShaderNodeParticleConeVelocity",
    .VisualShaderNodeParticleEmit = "VisualShaderNodeParticleEmit",
    .VisualShaderNodeParticleEmitter = "VisualShaderNodeParticleEmitter",
    .VisualShaderNodeParticleMeshEmitter = "VisualShaderNodeParticleMeshEmitter",
    .VisualShaderNodeParticleMultiplyByAxisAngle = "VisualShaderNodeParticleMultiplyByAxisAngle",
    .VisualShaderNodeParticleOutput = "VisualShaderNodeParticleOutput",
    .VisualShaderNodeParticleRandomness = "VisualShaderNodeParticleRandomness",
    .VisualShaderNodeParticleRingEmitter = "VisualShaderNodeParticleRingEmitter",
    .VisualShaderNodeParticleSphereEmitter = "VisualShaderNodeParticleSphereEmitter",
    .VisualShaderNodeProximityFade = "VisualShaderNodeProximityFade",
    .VisualShaderNodeRandomRange = "VisualShaderNodeRandomRange",
    .VisualShaderNodeRemap = "VisualShaderNodeRemap",
    .VisualShaderNodeReroute = "VisualShaderNodeReroute",
    .VisualShaderNodeResizableBase = "VisualShaderNodeResizableBase",
    .VisualShaderNodeRotationByAxis = "VisualShaderNodeRotationByAxis",
    .VisualShaderNodeSDFRaymarch = "VisualShaderNodeSDFRaymarch",
    .VisualShaderNodeSDFToScreenUV = "VisualShaderNodeSDFToScreenUV",
    .VisualShaderNodeSample3D = "VisualShaderNodeSample3D",
    .VisualShaderNodeScreenNormalWorldSpace = "VisualShaderNodeScreenNormalWorldSpace",
    .VisualShaderNodeScreenUVToSDF = "VisualShaderNodeScreenUVToSDF",
    .VisualShaderNodeSmoothStep = "VisualShaderNodeSmoothStep",
    .VisualShaderNodeStep = "VisualShaderNodeStep",
    .VisualShaderNodeSwitch = "VisualShaderNodeSwitch",
    .VisualShaderNodeTexture = "VisualShaderNodeTexture",
    .VisualShaderNodeTexture2DArray = "VisualShaderNodeTexture2DArray",
    .VisualShaderNodeTexture2DArrayParameter = "VisualShaderNodeTexture2DArrayParameter",
    .VisualShaderNodeTexture2DParameter = "VisualShaderNodeTexture2DParameter",
    .VisualShaderNodeTexture3D = "VisualShaderNodeTexture3D",
    .VisualShaderNodeTexture3DParameter = "VisualShaderNodeTexture3DParameter",
    .VisualShaderNodeTextureParameter = "VisualShaderNodeTextureParameter",
    .VisualShaderNodeTextureParameterTriplanar = "VisualShaderNodeTextureParameterTriplanar",
    .VisualShaderNodeTextureSDF = "VisualShaderNodeTextureSDF",
    .VisualShaderNodeTextureSDFNormal = "VisualShaderNodeTextureSDFNormal",
    .VisualShaderNodeTransformCompose = "VisualShaderNodeTransformCompose",
    .VisualShaderNodeTransformConstant = "VisualShaderNodeTransformConstant",
    .VisualShaderNodeTransformDecompose = "VisualShaderNodeTransformDecompose",
    .VisualShaderNodeTransformFunc = "VisualShaderNodeTransformFunc",
    .VisualShaderNodeTransformOp = "VisualShaderNodeTransformOp",
    .VisualShaderNodeTransformParameter = "VisualShaderNodeTransformParameter",
    .VisualShaderNodeTransformVecMult = "VisualShaderNodeTransformVecMult",
    .VisualShaderNodeUIntConstant = "VisualShaderNodeUIntConstant",
    .VisualShaderNodeUIntFunc = "VisualShaderNodeUIntFunc",
    .VisualShaderNodeUIntOp = "VisualShaderNodeUIntOp",
    .VisualShaderNodeUIntParameter = "VisualShaderNodeUIntParameter",
    .VisualShaderNodeUVFunc = "VisualShaderNodeUVFunc",
    .VisualShaderNodeUVPolarCoord = "VisualShaderNodeUVPolarCoord",
    .VisualShaderNodeVarying = "VisualShaderNodeVarying",
    .VisualShaderNodeVaryingGetter = "VisualShaderNodeVaryingGetter",
    .VisualShaderNodeVaryingSetter = "VisualShaderNodeVaryingSetter",
    .VisualShaderNodeVec2Constant = "VisualShaderNodeVec2Constant",
    .VisualShaderNodeVec2Parameter = "VisualShaderNodeVec2Parameter",
    .VisualShaderNodeVec3Constant = "VisualShaderNodeVec3Constant",
    .VisualShaderNodeVec3Parameter = "VisualShaderNodeVec3Parameter",
    .VisualShaderNodeVec4Constant = "VisualShaderNodeVec4Constant",
    .VisualShaderNodeVec4Parameter = "VisualShaderNodeVec4Parameter",
    .VisualShaderNodeVectorBase = "VisualShaderNodeVectorBase",
    .VisualShaderNodeVectorCompose = "VisualShaderNodeVectorCompose",
    .VisualShaderNodeVectorDecompose = "VisualShaderNodeVectorDecompose",
    .VisualShaderNodeVectorDistance = "VisualShaderNodeVectorDistance",
    .VisualShaderNodeVectorFunc = "VisualShaderNodeVectorFunc",
    .VisualShaderNodeVectorLen = "VisualShaderNodeVectorLen",
    .VisualShaderNodeVectorOp = "VisualShaderNodeVectorOp",
    .VisualShaderNodeVectorRefract = "VisualShaderNodeVectorRefract",
    .VisualShaderNodeWorldPositionFromDepth = "VisualShaderNodeWorldPositionFromDepth",
    .VoxelGI = "VoxelGI",
    .VoxelGIData = "VoxelGIData",
    .WeakRef = "WeakRef",
    .WebRTCDataChannel = "WebRTCDataChannel",
    .WebRTCDataChannelExtension = "WebRTCDataChannelExtension",
    .WebRTCMultiplayerPeer = "WebRTCMultiplayerPeer",
    .WebRTCPeerConnection = "WebRTCPeerConnection",
    .WebRTCPeerConnectionExtension = "WebRTCPeerConnectionExtension",
    .WebSocketMultiplayerPeer = "WebSocketMultiplayerPeer",
    .WebSocketPeer = "WebSocketPeer",
    .WebXRInterface = "WebXRInterface",
    .Window = "Window",
    .WorkerThreadPool = "WorkerThreadPool",
    .World2D = "World2D",
    .World3D = "World3D",
    .WorldBoundaryShape2D = "WorldBoundaryShape2D",
    .WorldBoundaryShape3D = "WorldBoundaryShape3D",
    .WorldEnvironment = "WorldEnvironment",
    .X509Certificate = "X509Certificate",
    .XMLParser = "XMLParser",
    .XRAnchor3D = "XRAnchor3D",
    .XRBodyModifier3D = "XRBodyModifier3D",
    .XRBodyTracker = "XRBodyTracker",
    .XRCamera3D = "XRCamera3D",
    .XRController3D = "XRController3D",
    .XRControllerTracker = "XRControllerTracker",
    .XRFaceModifier3D = "XRFaceModifier3D",
    .XRFaceTracker = "XRFaceTracker",
    .XRHandModifier3D = "XRHandModifier3D",
    .XRHandTracker = "XRHandTracker",
    .XRInterface = "XRInterface",
    .XRInterfaceExtension = "XRInterfaceExtension",
    .XRNode3D = "XRNode3D",
    .XROrigin3D = "XROrigin3D",
    .XRPose = "XRPose",
    .XRPositionalTracker = "XRPositionalTracker",
    .XRServer = "XRServer",
    .XRTracker = "XRTracker",
    .XRVRS = "XRVRS",
    .ZIPPacker = "ZIPPacker",
    .ZIPReader = "ZIPReader",
}


GodotClasses :: enum {
    AESContext,
    AStar2D,
    AStar3D,
    AStarGrid2D,
    AcceptDialog,
    AnimatableBody2D,
    AnimatableBody3D,
    AnimatedSprite2D,
    AnimatedSprite3D,
    AnimatedTexture,
    Animation,
    AnimationLibrary,
    AnimationMixer,
    AnimationNode,
    AnimationNodeAdd2,
    AnimationNodeAdd3,
    AnimationNodeAnimation,
    AnimationNodeBlend2,
    AnimationNodeBlend3,
    AnimationNodeBlendSpace1D,
    AnimationNodeBlendSpace2D,
    AnimationNodeBlendTree,
    AnimationNodeExtension,
    AnimationNodeOneShot,
    AnimationNodeOutput,
    AnimationNodeStateMachine,
    AnimationNodeStateMachinePlayback,
    AnimationNodeStateMachineTransition,
    AnimationNodeSub2,
    AnimationNodeSync,
    AnimationNodeTimeScale,
    AnimationNodeTimeSeek,
    AnimationNodeTransition,
    AnimationPlayer,
    AnimationRootNode,
    AnimationTree,
    Area2D,
    Area3D,
    ArrayMesh,
    ArrayOccluder3D,
    AspectRatioContainer,
    AtlasTexture,
    AudioBusLayout,
    AudioEffect,
    AudioEffectAmplify,
    AudioEffectBandLimitFilter,
    AudioEffectBandPassFilter,
    AudioEffectCapture,
    AudioEffectChorus,
    AudioEffectCompressor,
    AudioEffectDelay,
    AudioEffectDistortion,
    AudioEffectEQ,
    AudioEffectEQ10,
    AudioEffectEQ21,
    AudioEffectEQ6,
    AudioEffectFilter,
    AudioEffectHardLimiter,
    AudioEffectHighPassFilter,
    AudioEffectHighShelfFilter,
    AudioEffectInstance,
    AudioEffectLimiter,
    AudioEffectLowPassFilter,
    AudioEffectLowShelfFilter,
    AudioEffectNotchFilter,
    AudioEffectPanner,
    AudioEffectPhaser,
    AudioEffectPitchShift,
    AudioEffectRecord,
    AudioEffectReverb,
    AudioEffectSpectrumAnalyzer,
    AudioEffectSpectrumAnalyzerInstance,
    AudioEffectStereoEnhance,
    AudioListener2D,
    AudioListener3D,
    AudioSample,
    AudioSamplePlayback,
    AudioServer,
    AudioStream,
    AudioStreamGenerator,
    AudioStreamGeneratorPlayback,
    AudioStreamInteractive,
    AudioStreamMP3,
    AudioStreamMicrophone,
    AudioStreamOggVorbis,
    AudioStreamPlayback,
    AudioStreamPlaybackInteractive,
    AudioStreamPlaybackOggVorbis,
    AudioStreamPlaybackPlaylist,
    AudioStreamPlaybackPolyphonic,
    AudioStreamPlaybackResampled,
    AudioStreamPlaybackSynchronized,
    AudioStreamPlayer,
    AudioStreamPlayer2D,
    AudioStreamPlayer3D,
    AudioStreamPlaylist,
    AudioStreamPolyphonic,
    AudioStreamRandomizer,
    AudioStreamSynchronized,
    AudioStreamWAV,
    BackBufferCopy,
    BaseButton,
    BaseMaterial3D,
    BitMap,
    Bone2D,
    BoneAttachment3D,
    BoneMap,
    BoxContainer,
    BoxMesh,
    BoxOccluder3D,
    BoxShape3D,
    Button,
    ButtonGroup,
    CPUParticles2D,
    CPUParticles3D,
    CSGBox3D,
    CSGCombiner3D,
    CSGCylinder3D,
    CSGMesh3D,
    CSGPolygon3D,
    CSGPrimitive3D,
    CSGShape3D,
    CSGSphere3D,
    CSGTorus3D,
    CallbackTweener,
    Camera2D,
    Camera3D,
    CameraAttributes,
    CameraAttributesPhysical,
    CameraAttributesPractical,
    CameraFeed,
    CameraServer,
    CameraTexture,
    CanvasGroup,
    CanvasItem,
    CanvasItemMaterial,
    CanvasLayer,
    CanvasModulate,
    CanvasTexture,
    CapsuleMesh,
    CapsuleShape2D,
    CapsuleShape3D,
    CenterContainer,
    CharFXTransform,
    CharacterBody2D,
    CharacterBody3D,
    CheckBox,
    CheckButton,
    CircleShape2D,
    ClassDB,
    CodeEdit,
    CodeHighlighter,
    CollisionObject2D,
    CollisionObject3D,
    CollisionPolygon2D,
    CollisionPolygon3D,
    CollisionShape2D,
    CollisionShape3D,
    ColorPalette,
    ColorPicker,
    ColorPickerButton,
    ColorRect,
    Compositor,
    CompositorEffect,
    CompressedCubemap,
    CompressedCubemapArray,
    CompressedTexture2D,
    CompressedTexture2DArray,
    CompressedTexture3D,
    CompressedTextureLayered,
    ConcavePolygonShape2D,
    ConcavePolygonShape3D,
    ConeTwistJoint3D,
    ConfigFile,
    ConfirmationDialog,
    Container,
    Control,
    ConvexPolygonShape2D,
    ConvexPolygonShape3D,
    Crypto,
    CryptoKey,
    Cubemap,
    CubemapArray,
    Curve,
    Curve2D,
    Curve3D,
    CurveTexture,
    CurveXYZTexture,
    CylinderMesh,
    CylinderShape3D,
    DTLSServer,
    DampedSpringJoint2D,
    Decal,
    DirAccess,
    DirectionalLight2D,
    DirectionalLight3D,
    DisplayServer,
    ENetConnection,
    ENetMultiplayerPeer,
    ENetPacketPeer,
    EditorCommandPalette,
    EditorContextMenuPlugin,
    EditorDebuggerPlugin,
    EditorDebuggerSession,
    EditorExportPlatform,
    EditorExportPlatformAndroid,
    EditorExportPlatformExtension,
    EditorExportPlatformIOS,
    EditorExportPlatformLinuxBSD,
    EditorExportPlatformMacOS,
    EditorExportPlatformPC,
    EditorExportPlatformWeb,
    EditorExportPlatformWindows,
    EditorExportPlugin,
    EditorExportPreset,
    EditorFeatureProfile,
    EditorFileDialog,
    EditorFileSystem,
    EditorFileSystemDirectory,
    EditorFileSystemImportFormatSupportQuery,
    EditorImportPlugin,
    EditorInspector,
    EditorInspectorPlugin,
    EditorInterface,
    EditorNode3DGizmo,
    EditorNode3DGizmoPlugin,
    EditorPaths,
    EditorPlugin,
    EditorProperty,
    EditorResourceConversionPlugin,
    EditorResourcePicker,
    EditorResourcePreview,
    EditorResourcePreviewGenerator,
    EditorResourceTooltipPlugin,
    EditorSceneFormatImporter,
    EditorSceneFormatImporterBlend,
    EditorSceneFormatImporterFBX2GLTF,
    EditorSceneFormatImporterGLTF,
    EditorSceneFormatImporterUFBX,
    EditorScenePostImport,
    EditorScenePostImportPlugin,
    EditorScript,
    EditorScriptPicker,
    EditorSelection,
    EditorSettings,
    EditorSpinSlider,
    EditorSyntaxHighlighter,
    EditorToaster,
    EditorTranslationParserPlugin,
    EditorUndoRedoManager,
    EditorVCSInterface,
    EncodedObjectAsID,
    Engine,
    EngineDebugger,
    EngineProfiler,
    Environment,
    Expression,
    ExternalTexture,
    FBXDocument,
    FBXState,
    FastNoiseLite,
    FileAccess,
    FileDialog,
    FileSystemDock,
    FlowContainer,
    FogMaterial,
    FogVolume,
    Font,
    FontFile,
    FontVariation,
    FramebufferCacheRD,
    GDExtension,
    GDExtensionManager,
    GDScript,
    GDScriptSyntaxHighlighter,
    GLTFAccessor,
    GLTFAnimation,
    GLTFBufferView,
    GLTFCamera,
    GLTFDocument,
    GLTFDocumentExtension,
    GLTFDocumentExtensionConvertImporterMesh,
    GLTFLight,
    GLTFMesh,
    GLTFNode,
    GLTFObjectModelProperty,
    GLTFPhysicsBody,
    GLTFPhysicsShape,
    GLTFSkeleton,
    GLTFSkin,
    GLTFSpecGloss,
    GLTFState,
    GLTFTexture,
    GLTFTextureSampler,
    GPUParticles2D,
    GPUParticles3D,
    GPUParticlesAttractor3D,
    GPUParticlesAttractorBox3D,
    GPUParticlesAttractorSphere3D,
    GPUParticlesAttractorVectorField3D,
    GPUParticlesCollision3D,
    GPUParticlesCollisionBox3D,
    GPUParticlesCollisionHeightField3D,
    GPUParticlesCollisionSDF3D,
    GPUParticlesCollisionSphere3D,
    Generic6DOFJoint3D,
    Geometry2D,
    Geometry3D,
    GeometryInstance3D,
    Gradient,
    GradientTexture1D,
    GradientTexture2D,
    GraphEdit,
    GraphElement,
    GraphFrame,
    GraphNode,
    GridContainer,
    GridMap,
    GridMapEditorPlugin,
    GrooveJoint2D,
    HBoxContainer,
    HFlowContainer,
    HMACContext,
    HScrollBar,
    HSeparator,
    HSlider,
    HSplitContainer,
    HTTPClient,
    HTTPRequest,
    HashingContext,
    HeightMapShape3D,
    HingeJoint3D,
    IP,
    Image,
    ImageFormatLoader,
    ImageFormatLoaderExtension,
    ImageTexture,
    ImageTexture3D,
    ImageTextureLayered,
    ImmediateMesh,
    ImporterMesh,
    ImporterMeshInstance3D,
    Input,
    InputEvent,
    InputEventAction,
    InputEventFromWindow,
    InputEventGesture,
    InputEventJoypadButton,
    InputEventJoypadMotion,
    InputEventKey,
    InputEventMIDI,
    InputEventMagnifyGesture,
    InputEventMouse,
    InputEventMouseButton,
    InputEventMouseMotion,
    InputEventPanGesture,
    InputEventScreenDrag,
    InputEventScreenTouch,
    InputEventShortcut,
    InputEventWithModifiers,
    InputMap,
    InstancePlaceholder,
    IntervalTweener,
    ItemList,
    JNISingleton,
    JSON,
    JSONRPC,
    JavaClass,
    JavaClassWrapper,
    JavaObject,
    JavaScriptBridge,
    JavaScriptObject,
    Joint2D,
    Joint3D,
    KinematicCollision2D,
    KinematicCollision3D,
    Label,
    Label3D,
    LabelSettings,
    Light2D,
    Light3D,
    LightOccluder2D,
    LightmapGI,
    LightmapGIData,
    LightmapProbe,
    Lightmapper,
    LightmapperRD,
    Line2D,
    LineEdit,
    LinkButton,
    LookAtModifier3D,
    MainLoop,
    MarginContainer,
    Marker2D,
    Marker3D,
    Marshalls,
    Material,
    MenuBar,
    MenuButton,
    Mesh,
    MeshConvexDecompositionSettings,
    MeshDataTool,
    MeshInstance2D,
    MeshInstance3D,
    MeshLibrary,
    MeshTexture,
    MethodTweener,
    MissingNode,
    MissingResource,
    MobileVRInterface,
    MovieWriter,
    MultiMesh,
    MultiMeshInstance2D,
    MultiMeshInstance3D,
    MultiplayerAPI,
    MultiplayerAPIExtension,
    MultiplayerPeer,
    MultiplayerPeerExtension,
    MultiplayerSpawner,
    MultiplayerSynchronizer,
    Mutex,
    NativeMenu,
    NavigationAgent2D,
    NavigationAgent3D,
    NavigationLink2D,
    NavigationLink3D,
    NavigationMesh,
    NavigationMeshGenerator,
    NavigationMeshSourceGeometryData2D,
    NavigationMeshSourceGeometryData3D,
    NavigationObstacle2D,
    NavigationObstacle3D,
    NavigationPathQueryParameters2D,
    NavigationPathQueryParameters3D,
    NavigationPathQueryResult2D,
    NavigationPathQueryResult3D,
    NavigationPolygon,
    NavigationRegion2D,
    NavigationRegion3D,
    NavigationServer2D,
    NavigationServer3D,
    NinePatchRect,
    Node,
    Node2D,
    Node3D,
    Node3DGizmo,
    Noise,
    NoiseTexture2D,
    NoiseTexture3D,
    ORMMaterial3D,
    OS,
    Object,
    Occluder3D,
    OccluderInstance3D,
    OccluderPolygon2D,
    OfflineMultiplayerPeer,
    OggPacketSequence,
    OggPacketSequencePlayback,
    OmniLight3D,
    OpenXRAPIExtension,
    OpenXRAction,
    OpenXRActionBindingModifier,
    OpenXRActionMap,
    OpenXRActionSet,
    OpenXRAnalogThresholdModifier,
    OpenXRBindingModifier,
    OpenXRBindingModifierEditor,
    OpenXRCompositionLayer,
    OpenXRCompositionLayerCylinder,
    OpenXRCompositionLayerEquirect,
    OpenXRCompositionLayerQuad,
    OpenXRDpadBindingModifier,
    OpenXRExtensionWrapperExtension,
    OpenXRHand,
    OpenXRHapticBase,
    OpenXRHapticVibration,
    OpenXRIPBinding,
    OpenXRIPBindingModifier,
    OpenXRInteractionProfile,
    OpenXRInteractionProfileEditor,
    OpenXRInteractionProfileEditorBase,
    OpenXRInteractionProfileMetadata,
    OpenXRInterface,
    OpenXRVisibilityMask,
    OptimizedTranslation,
    OptionButton,
    PCKPacker,
    PackedDataContainer,
    PackedDataContainerRef,
    PackedScene,
    PacketPeer,
    PacketPeerDTLS,
    PacketPeerExtension,
    PacketPeerStream,
    PacketPeerUDP,
    Panel,
    PanelContainer,
    PanoramaSkyMaterial,
    Parallax2D,
    ParallaxBackground,
    ParallaxLayer,
    ParticleProcessMaterial,
    Path2D,
    Path3D,
    PathFollow2D,
    PathFollow3D,
    Performance,
    PhysicalBone2D,
    PhysicalBone3D,
    PhysicalBoneSimulator3D,
    PhysicalSkyMaterial,
    PhysicsBody2D,
    PhysicsBody3D,
    PhysicsDirectBodyState2D,
    PhysicsDirectBodyState2DExtension,
    PhysicsDirectBodyState3D,
    PhysicsDirectBodyState3DExtension,
    PhysicsDirectSpaceState2D,
    PhysicsDirectSpaceState2DExtension,
    PhysicsDirectSpaceState3D,
    PhysicsDirectSpaceState3DExtension,
    PhysicsMaterial,
    PhysicsPointQueryParameters2D,
    PhysicsPointQueryParameters3D,
    PhysicsRayQueryParameters2D,
    PhysicsRayQueryParameters3D,
    PhysicsServer2D,
    PhysicsServer2DExtension,
    PhysicsServer2DManager,
    PhysicsServer3D,
    PhysicsServer3DExtension,
    PhysicsServer3DManager,
    PhysicsServer3DRenderingServerHandler,
    PhysicsShapeQueryParameters2D,
    PhysicsShapeQueryParameters3D,
    PhysicsTestMotionParameters2D,
    PhysicsTestMotionParameters3D,
    PhysicsTestMotionResult2D,
    PhysicsTestMotionResult3D,
    PinJoint2D,
    PinJoint3D,
    PlaceholderCubemap,
    PlaceholderCubemapArray,
    PlaceholderMaterial,
    PlaceholderMesh,
    PlaceholderTexture2D,
    PlaceholderTexture2DArray,
    PlaceholderTexture3D,
    PlaceholderTextureLayered,
    PlaneMesh,
    PointLight2D,
    PointMesh,
    Polygon2D,
    PolygonOccluder3D,
    PolygonPathFinder,
    Popup,
    PopupMenu,
    PopupPanel,
    PortableCompressedTexture2D,
    PrimitiveMesh,
    PrismMesh,
    ProceduralSkyMaterial,
    ProgressBar,
    ProjectSettings,
    PropertyTweener,
    QuadMesh,
    QuadOccluder3D,
    RDAttachmentFormat,
    RDFramebufferPass,
    RDPipelineColorBlendState,
    RDPipelineColorBlendStateAttachment,
    RDPipelineDepthStencilState,
    RDPipelineMultisampleState,
    RDPipelineRasterizationState,
    RDPipelineSpecializationConstant,
    RDSamplerState,
    RDShaderFile,
    RDShaderSPIRV,
    RDShaderSource,
    RDTextureFormat,
    RDTextureView,
    RDUniform,
    RDVertexAttribute,
    RandomNumberGenerator,
    Range,
    RayCast2D,
    RayCast3D,
    RectangleShape2D,
    RefCounted,
    ReferenceRect,
    ReflectionProbe,
    RegEx,
    RegExMatch,
    RemoteTransform2D,
    RemoteTransform3D,
    RenderData,
    RenderDataExtension,
    RenderDataRD,
    RenderSceneBuffers,
    RenderSceneBuffersConfiguration,
    RenderSceneBuffersExtension,
    RenderSceneBuffersRD,
    RenderSceneData,
    RenderSceneDataExtension,
    RenderSceneDataRD,
    RenderingDevice,
    RenderingServer,
    Resource,
    ResourceFormatLoader,
    ResourceFormatSaver,
    ResourceImporter,
    ResourceImporterBMFont,
    ResourceImporterBitMap,
    ResourceImporterCSVTranslation,
    ResourceImporterDynamicFont,
    ResourceImporterImage,
    ResourceImporterImageFont,
    ResourceImporterLayeredTexture,
    ResourceImporterMP3,
    ResourceImporterOBJ,
    ResourceImporterOggVorbis,
    ResourceImporterScene,
    ResourceImporterShaderFile,
    ResourceImporterTexture,
    ResourceImporterTextureAtlas,
    ResourceImporterWAV,
    ResourceLoader,
    ResourcePreloader,
    ResourceSaver,
    ResourceUID,
    RetargetModifier3D,
    RibbonTrailMesh,
    RichTextEffect,
    RichTextLabel,
    RigidBody2D,
    RigidBody3D,
    RootMotionView,
    SceneMultiplayer,
    SceneReplicationConfig,
    SceneState,
    SceneTree,
    SceneTreeTimer,
    Script,
    ScriptCreateDialog,
    ScriptEditor,
    ScriptEditorBase,
    ScriptExtension,
    ScriptLanguage,
    ScriptLanguageExtension,
    ScrollBar,
    ScrollContainer,
    SegmentShape2D,
    Semaphore,
    SeparationRayShape2D,
    SeparationRayShape3D,
    Separator,
    Shader,
    ShaderGlobalsOverride,
    ShaderInclude,
    ShaderIncludeDB,
    ShaderMaterial,
    Shape2D,
    Shape3D,
    ShapeCast2D,
    ShapeCast3D,
    Shortcut,
    Skeleton2D,
    Skeleton3D,
    SkeletonIK3D,
    SkeletonModification2D,
    SkeletonModification2DCCDIK,
    SkeletonModification2DFABRIK,
    SkeletonModification2DJiggle,
    SkeletonModification2DLookAt,
    SkeletonModification2DPhysicalBones,
    SkeletonModification2DStackHolder,
    SkeletonModification2DTwoBoneIK,
    SkeletonModificationStack2D,
    SkeletonModifier3D,
    SkeletonProfile,
    SkeletonProfileHumanoid,
    Skin,
    SkinReference,
    Sky,
    Slider,
    SliderJoint3D,
    SoftBody3D,
    SphereMesh,
    SphereOccluder3D,
    SphereShape3D,
    SpinBox,
    SplitContainer,
    SpotLight3D,
    SpringArm3D,
    SpringBoneCollision3D,
    SpringBoneCollisionCapsule3D,
    SpringBoneCollisionPlane3D,
    SpringBoneCollisionSphere3D,
    SpringBoneSimulator3D,
    Sprite2D,
    Sprite3D,
    SpriteBase3D,
    SpriteFrames,
    StandardMaterial3D,
    StaticBody2D,
    StaticBody3D,
    StatusIndicator,
    StreamPeer,
    StreamPeerBuffer,
    StreamPeerExtension,
    StreamPeerGZIP,
    StreamPeerTCP,
    StreamPeerTLS,
    StyleBox,
    StyleBoxEmpty,
    StyleBoxFlat,
    StyleBoxLine,
    StyleBoxTexture,
    SubViewport,
    SubViewportContainer,
    SubtweenTweener,
    SurfaceTool,
    SyntaxHighlighter,
    SystemFont,
    TCPServer,
    TLSOptions,
    TabBar,
    TabContainer,
    TextEdit,
    TextLine,
    TextMesh,
    TextParagraph,
    TextServer,
    TextServerAdvanced,
    TextServerDummy,
    TextServerExtension,
    TextServerManager,
    Texture,
    Texture2D,
    Texture2DArray,
    Texture2DArrayRD,
    Texture2DRD,
    Texture3D,
    Texture3DRD,
    TextureButton,
    TextureCubemapArrayRD,
    TextureCubemapRD,
    TextureLayered,
    TextureLayeredRD,
    TextureProgressBar,
    TextureRect,
    Theme,
    ThemeDB,
    Thread,
    TileData,
    TileMap,
    TileMapLayer,
    TileMapPattern,
    TileSet,
    TileSetAtlasSource,
    TileSetScenesCollectionSource,
    TileSetSource,
    Time,
    Timer,
    TorusMesh,
    TouchScreenButton,
    Translation,
    TranslationDomain,
    TranslationServer,
    Tree,
    TreeItem,
    TriangleMesh,
    TubeTrailMesh,
    Tween,
    Tweener,
    UDPServer,
    UPNP,
    UPNPDevice,
    UndoRedo,
    UniformSetCacheRD,
    VBoxContainer,
    VFlowContainer,
    VScrollBar,
    VSeparator,
    VSlider,
    VSplitContainer,
    VehicleBody3D,
    VehicleWheel3D,
    VideoStream,
    VideoStreamPlayback,
    VideoStreamPlayer,
    VideoStreamTheora,
    Viewport,
    ViewportTexture,
    VisibleOnScreenEnabler2D,
    VisibleOnScreenEnabler3D,
    VisibleOnScreenNotifier2D,
    VisibleOnScreenNotifier3D,
    VisualInstance3D,
    VisualShader,
    VisualShaderNode,
    VisualShaderNodeBillboard,
    VisualShaderNodeBooleanConstant,
    VisualShaderNodeBooleanParameter,
    VisualShaderNodeClamp,
    VisualShaderNodeColorConstant,
    VisualShaderNodeColorFunc,
    VisualShaderNodeColorOp,
    VisualShaderNodeColorParameter,
    VisualShaderNodeComment,
    VisualShaderNodeCompare,
    VisualShaderNodeConstant,
    VisualShaderNodeCubemap,
    VisualShaderNodeCubemapParameter,
    VisualShaderNodeCurveTexture,
    VisualShaderNodeCurveXYZTexture,
    VisualShaderNodeCustom,
    VisualShaderNodeDerivativeFunc,
    VisualShaderNodeDeterminant,
    VisualShaderNodeDistanceFade,
    VisualShaderNodeDotProduct,
    VisualShaderNodeExpression,
    VisualShaderNodeFaceForward,
    VisualShaderNodeFloatConstant,
    VisualShaderNodeFloatFunc,
    VisualShaderNodeFloatOp,
    VisualShaderNodeFloatParameter,
    VisualShaderNodeFrame,
    VisualShaderNodeFresnel,
    VisualShaderNodeGlobalExpression,
    VisualShaderNodeGroupBase,
    VisualShaderNodeIf,
    VisualShaderNodeInput,
    VisualShaderNodeIntConstant,
    VisualShaderNodeIntFunc,
    VisualShaderNodeIntOp,
    VisualShaderNodeIntParameter,
    VisualShaderNodeIs,
    VisualShaderNodeLinearSceneDepth,
    VisualShaderNodeMix,
    VisualShaderNodeMultiplyAdd,
    VisualShaderNodeOuterProduct,
    VisualShaderNodeOutput,
    VisualShaderNodeParameter,
    VisualShaderNodeParameterRef,
    VisualShaderNodeParticleAccelerator,
    VisualShaderNodeParticleBoxEmitter,
    VisualShaderNodeParticleConeVelocity,
    VisualShaderNodeParticleEmit,
    VisualShaderNodeParticleEmitter,
    VisualShaderNodeParticleMeshEmitter,
    VisualShaderNodeParticleMultiplyByAxisAngle,
    VisualShaderNodeParticleOutput,
    VisualShaderNodeParticleRandomness,
    VisualShaderNodeParticleRingEmitter,
    VisualShaderNodeParticleSphereEmitter,
    VisualShaderNodeProximityFade,
    VisualShaderNodeRandomRange,
    VisualShaderNodeRemap,
    VisualShaderNodeReroute,
    VisualShaderNodeResizableBase,
    VisualShaderNodeRotationByAxis,
    VisualShaderNodeSDFRaymarch,
    VisualShaderNodeSDFToScreenUV,
    VisualShaderNodeSample3D,
    VisualShaderNodeScreenNormalWorldSpace,
    VisualShaderNodeScreenUVToSDF,
    VisualShaderNodeSmoothStep,
    VisualShaderNodeStep,
    VisualShaderNodeSwitch,
    VisualShaderNodeTexture,
    VisualShaderNodeTexture2DArray,
    VisualShaderNodeTexture2DArrayParameter,
    VisualShaderNodeTexture2DParameter,
    VisualShaderNodeTexture3D,
    VisualShaderNodeTexture3DParameter,
    VisualShaderNodeTextureParameter,
    VisualShaderNodeTextureParameterTriplanar,
    VisualShaderNodeTextureSDF,
    VisualShaderNodeTextureSDFNormal,
    VisualShaderNodeTransformCompose,
    VisualShaderNodeTransformConstant,
    VisualShaderNodeTransformDecompose,
    VisualShaderNodeTransformFunc,
    VisualShaderNodeTransformOp,
    VisualShaderNodeTransformParameter,
    VisualShaderNodeTransformVecMult,
    VisualShaderNodeUIntConstant,
    VisualShaderNodeUIntFunc,
    VisualShaderNodeUIntOp,
    VisualShaderNodeUIntParameter,
    VisualShaderNodeUVFunc,
    VisualShaderNodeUVPolarCoord,
    VisualShaderNodeVarying,
    VisualShaderNodeVaryingGetter,
    VisualShaderNodeVaryingSetter,
    VisualShaderNodeVec2Constant,
    VisualShaderNodeVec2Parameter,
    VisualShaderNodeVec3Constant,
    VisualShaderNodeVec3Parameter,
    VisualShaderNodeVec4Constant,
    VisualShaderNodeVec4Parameter,
    VisualShaderNodeVectorBase,
    VisualShaderNodeVectorCompose,
    VisualShaderNodeVectorDecompose,
    VisualShaderNodeVectorDistance,
    VisualShaderNodeVectorFunc,
    VisualShaderNodeVectorLen,
    VisualShaderNodeVectorOp,
    VisualShaderNodeVectorRefract,
    VisualShaderNodeWorldPositionFromDepth,
    VoxelGI,
    VoxelGIData,
    WeakRef,
    WebRTCDataChannel,
    WebRTCDataChannelExtension,
    WebRTCMultiplayerPeer,
    WebRTCPeerConnection,
    WebRTCPeerConnectionExtension,
    WebSocketMultiplayerPeer,
    WebSocketPeer,
    WebXRInterface,
    Window,
    WorkerThreadPool,
    World2D,
    World3D,
    WorldBoundaryShape2D,
    WorldBoundaryShape3D,
    WorldEnvironment,
    X509Certificate,
    XMLParser,
    XRAnchor3D,
    XRBodyModifier3D,
    XRBodyTracker,
    XRCamera3D,
    XRController3D,
    XRControllerTracker,
    XRFaceModifier3D,
    XRFaceTracker,
    XRHandModifier3D,
    XRHandTracker,
    XRInterface,
    XRInterfaceExtension,
    XRNode3D,
    XROrigin3D,
    XRPose,
    XRPositionalTracker,
    XRServer,
    XRTracker,
    XRVRS,
    ZIPPacker,
    ZIPReader,
}
