package GDWrapper

import GDE "gdAPI/gdextension"
import "core:reflect"

//Just the whole list of all the class names that appear in the api json.
//No idea, I just copy/pasted.
//Should be useful for:
// * Declaring the class in your custom class
// * Hints
// * Having a table of already allocated and hashed StringName values
//Mainly want to get away from using raw strings.
//Name is very long. Yes.

ClassNameString :: string

SN_Error :: enum {
    ALREADY_NIL,
    BAD_INDEX,
}

GDClass_StringName_get :: proc(classname_index: ClassName_Index) -> ^StringName {
    //ClassName_StringNames[classname_index]
    if ClassName_StringNames[classname_index].ptr == nil {
        StringConstruct(&ClassName_StringNames[classname_index], reflect.enum_field_names(ClassName_Index)[classname_index])
    }
    return &ClassName_StringNames[classname_index]
}

ClassName_StringName_Del :: proc(classname_index: ClassName_Index) -> SN_Error {
    when ODIN_DEBUG {
        if int(classname_index) > len(ClassName_Index) {
            return .BAD_INDEX
        }
        if ClassName_StringNames[classname_index].ptr == nil {
            return .ALREADY_NIL
        }
    }

    StringName_Methods.Destroy(&ClassName_StringNames[classname_index])

    return nil
}

ClassName_Index :: enum {
    nil,
    AESContext,
    AStar2D,
    AStar3D,
    AStarGrid2D,
    AcceptDialog,
    AnimatableBody2D,
    AnimatableBody3D,
    AnimatedSprite2D,
    AnimatedSprite3D,
    AnimatedTexture,
    Animation,
    AnimationLibrary,
    AnimationMixer,
    AnimationNode,
    AnimationNodeAdd2,
    AnimationNodeAdd3,
    AnimationNodeAnimation,
    AnimationNodeBlend2,
    AnimationNodeBlend3,
    AnimationNodeBlendSpace1D,
    AnimationNodeBlendSpace2D,
    AnimationNodeBlendTree,
    AnimationNodeExtension,
    AnimationNodeOneShot,
    AnimationNodeOutput,
    AnimationNodeStateMachine,
    AnimationNodeStateMachinePlayback,
    AnimationNodeStateMachineTransition,
    AnimationNodeSub2,
    AnimationNodeSync,
    AnimationNodeTimeScale,
    AnimationNodeTimeSeek,
    AnimationNodeTransition,
    AnimationPlayer,
    AnimationRootNode,
    AnimationTree,
    Area2D,
    Area3D,
    ArrayMesh,
    ArrayOccluder3D,
    AspectRatioContainer,
    AtlasTexture,
    AudioBusLayout,
    AudioEffect,
    AudioEffectAmplify,
    AudioEffectBandLimitFilter,
    AudioEffectBandPassFilter,
    AudioEffectCapture,
    AudioEffectChorus,
    AudioEffectCompressor,
    AudioEffectDelay,
    AudioEffectDistortion,
    AudioEffectEQ,
    AudioEffectEQ10,
    AudioEffectEQ21,
    AudioEffectEQ6,
    AudioEffectFilter,
    AudioEffectHardLimiter,
    AudioEffectHighPassFilter,
    AudioEffectHighShelfFilter,
    AudioEffectInstance,
    AudioEffectLimiter,
    AudioEffectLowPassFilter,
    AudioEffectLowShelfFilter,
    AudioEffectNotchFilter,
    AudioEffectPanner,
    AudioEffectPhaser,
    AudioEffectPitchShift,
    AudioEffectRecord,
    AudioEffectReverb,
    AudioEffectSpectrumAnalyzer,
    AudioEffectSpectrumAnalyzerInstance,
    AudioEffectStereoEnhance,
    AudioListener2D,
    AudioListener3D,
    AudioSample,
    AudioSamplePlayback,
    AudioServer,
    AudioStream,
    AudioStreamGenerator,
    AudioStreamGeneratorPlayback,
    AudioStreamInteractive,
    AudioStreamMP3,
    AudioStreamMicrophone,
    AudioStreamOggVorbis,
    AudioStreamPlayback,
    AudioStreamPlaybackInteractive,
    AudioStreamPlaybackOggVorbis,
    AudioStreamPlaybackPlaylist,
    AudioStreamPlaybackPolyphonic,
    AudioStreamPlaybackResampled,
    AudioStreamPlaybackSynchronized,
    AudioStreamPlayer,
    AudioStreamPlayer2D,
    AudioStreamPlayer3D,
    AudioStreamPlaylist,
    AudioStreamPolyphonic,
    AudioStreamRandomizer,
    AudioStreamSynchronized,
    AudioStreamWAV,
    BackBufferCopy,
    BaseButton,
    BaseMaterial3D,
    BitMap,
    Bone2D,
    BoneAttachment3D,
    BoneMap,
    BoxContainer,
    BoxMesh,
    BoxOccluder3D,
    BoxShape3D,
    Button,
    ButtonGroup,
    CPUParticles2D,
    CPUParticles3D,
    CSGBox3D,
    CSGCombiner3D,
    CSGCylinder3D,
    CSGMesh3D,
    CSGPolygon3D,
    CSGPrimitive3D,
    CSGShape3D,
    CSGSphere3D,
    CSGTorus3D,
    CallbackTweener,
    Camera2D,
    Camera3D,
    CameraAttributes,
    CameraAttributesPhysical,
    CameraAttributesPractical,
    CameraFeed,
    CameraServer,
    CameraTexture,
    CanvasGroup,
    CanvasItem,
    CanvasItemMaterial,
    CanvasLayer,
    CanvasModulate,
    CanvasTexture,
    CapsuleMesh,
    CapsuleShape2D,
    CapsuleShape3D,
    CenterContainer,
    CharFXTransform,
    CharacterBody2D,
    CharacterBody3D,
    CheckBox,
    CheckButton,
    CircleShape2D,
    ClassDB,
    CodeEdit,
    CodeHighlighter,
    CollisionObject2D,
    CollisionObject3D,
    CollisionPolygon2D,
    CollisionPolygon3D,
    CollisionShape2D,
    CollisionShape3D,
    ColorPalette,
    ColorPicker,
    ColorPickerButton,
    ColorRect,
    Compositor,
    CompositorEffect,
    CompressedCubemap,
    CompressedCubemapArray,
    CompressedTexture2D,
    CompressedTexture2DArray,
    CompressedTexture3D,
    CompressedTextureLayered,
    ConcavePolygonShape2D,
    ConcavePolygonShape3D,
    ConeTwistJoint3D,
    ConfigFile,
    ConfirmationDialog,
    Container,
    Control,
    ConvexPolygonShape2D,
    ConvexPolygonShape3D,
    Crypto,
    CryptoKey,
    Cubemap,
    CubemapArray,
    Curve,
    Curve2D,
    Curve3D,
    CurveTexture,
    CurveXYZTexture,
    CylinderMesh,
    CylinderShape3D,
    DTLSServer,
    DampedSpringJoint2D,
    Decal,
    DirAccess,
    DirectionalLight2D,
    DirectionalLight3D,
    DisplayServer,
    ENetConnection,
    ENetMultiplayerPeer,
    ENetPacketPeer,
    EditorCommandPalette,
    EditorContextMenuPlugin,
    EditorDebuggerPlugin,
    EditorDebuggerSession,
    EditorExportPlatform,
    EditorExportPlatformAndroid,
    EditorExportPlatformExtension,
    EditorExportPlatformIOS,
    EditorExportPlatformLinuxBSD,
    EditorExportPlatformMacOS,
    EditorExportPlatformPC,
    EditorExportPlatformWeb,
    EditorExportPlatformWindows,
    EditorExportPlugin,
    EditorExportPreset,
    EditorFeatureProfile,
    EditorFileDialog,
    EditorFileSystem,
    EditorFileSystemDirectory,
    EditorFileSystemImportFormatSupportQuery,
    EditorImportPlugin,
    EditorInspector,
    EditorInspectorPlugin,
    EditorInterface,
    EditorNode3DGizmo,
    EditorNode3DGizmoPlugin,
    EditorPaths,
    EditorPlugin,
    EditorProperty,
    EditorResourceConversionPlugin,
    EditorResourcePicker,
    EditorResourcePreview,
    EditorResourcePreviewGenerator,
    EditorResourceTooltipPlugin,
    EditorSceneFormatImporter,
    EditorSceneFormatImporterBlend,
    EditorSceneFormatImporterFBX2GLTF,
    EditorSceneFormatImporterGLTF,
    EditorSceneFormatImporterUFBX,
    EditorScenePostImport,
    EditorScenePostImportPlugin,
    EditorScript,
    EditorScriptPicker,
    EditorSelection,
    EditorSettings,
    EditorSpinSlider,
    EditorSyntaxHighlighter,
    EditorToaster,
    EditorTranslationParserPlugin,
    EditorUndoRedoManager,
    EditorVCSInterface,
    EncodedObjectAsID,
    Engine,
    EngineDebugger,
    EngineProfiler,
    Environment,
    Expression,
    ExternalTexture,
    FBXDocument,
    FBXState,
    FastNoiseLite,
    FileAccess,
    FileDialog,
    FileSystemDock,
    FlowContainer,
    FogMaterial,
    FogVolume,
    Font,
    FontFile,
    FontVariation,
    FramebufferCacheRD,
    GDExtension,
    GDExtensionManager,
    GDScript,
    GDScriptSyntaxHighlighter,
    GLTFAccessor,
    GLTFAnimation,
    GLTFBufferView,
    GLTFCamera,
    GLTFDocument,
    GLTFDocumentExtension,
    GLTFDocumentExtensionConvertImporterMesh,
    GLTFLight,
    GLTFMesh,
    GLTFNode,
    GLTFObjectModelProperty,
    GLTFPhysicsBody,
    GLTFPhysicsShape,
    GLTFSkeleton,
    GLTFSkin,
    GLTFSpecGloss,
    GLTFState,
    GLTFTexture,
    GLTFTextureSampler,
    GPUParticles2D,
    GPUParticles3D,
    GPUParticlesAttractor3D,
    GPUParticlesAttractorBox3D,
    GPUParticlesAttractorSphere3D,
    GPUParticlesAttractorVectorField3D,
    GPUParticlesCollision3D,
    GPUParticlesCollisionBox3D,
    GPUParticlesCollisionHeightField3D,
    GPUParticlesCollisionSDF3D,
    GPUParticlesCollisionSphere3D,
    Generic6DOFJoint3D,
    Geometry2D,
    Geometry3D,
    GeometryInstance3D,
    Gradient,
    GradientTexture1D,
    GradientTexture2D,
    GraphEdit,
    GraphElement,
    GraphFrame,
    GraphNode,
    GridContainer,
    GridMap,
    GridMapEditorPlugin,
    GrooveJoint2D,
    HBoxContainer,
    HFlowContainer,
    HMACContext,
    HScrollBar,
    HSeparator,
    HSlider,
    HSplitContainer,
    HTTPClient,
    HTTPRequest,
    HashingContext,
    HeightMapShape3D,
    HingeJoint3D,
    IP,
    Image,
    ImageFormatLoader,
    ImageFormatLoaderExtension,
    ImageTexture,
    ImageTexture3D,
    ImageTextureLayered,
    ImmediateMesh,
    ImporterMesh,
    ImporterMeshInstance3D,
    Input,
    InputEvent,
    InputEventAction,
    InputEventFromWindow,
    InputEventGesture,
    InputEventJoypadButton,
    InputEventJoypadMotion,
    InputEventKey,
    InputEventMIDI,
    InputEventMagnifyGesture,
    InputEventMouse,
    InputEventMouseButton,
    InputEventMouseMotion,
    InputEventPanGesture,
    InputEventScreenDrag,
    InputEventScreenTouch,
    InputEventShortcut,
    InputEventWithModifiers,
    InputMap,
    InstancePlaceholder,
    IntervalTweener,
    ItemList,
    JNISingleton,
    JSON,
    JSONRPC,
    JavaClass,
    JavaClassWrapper,
    JavaObject,
    JavaScriptBridge,
    JavaScriptObject,
    Joint2D,
    Joint3D,
    KinematicCollision2D,
    KinematicCollision3D,
    Label,
    Label3D,
    LabelSettings,
    Light2D,
    Light3D,
    LightOccluder2D,
    LightmapGI,
    LightmapGIData,
    LightmapProbe,
    Lightmapper,
    LightmapperRD,
    Line2D,
    LineEdit,
    LinkButton,
    LookAtModifier3D,
    MainLoop,
    MarginContainer,
    Marker2D,
    Marker3D,
    Marshalls,
    Material,
    MenuBar,
    MenuButton,
    Mesh,
    MeshConvexDecompositionSettings,
    MeshDataTool,
    MeshInstance2D,
    MeshInstance3D,
    MeshLibrary,
    MeshTexture,
    MethodTweener,
    MissingNode,
    MissingResource,
    MobileVRInterface,
    MovieWriter,
    MultiMesh,
    MultiMeshInstance2D,
    MultiMeshInstance3D,
    MultiplayerAPI,
    MultiplayerAPIExtension,
    MultiplayerPeer,
    MultiplayerPeerExtension,
    MultiplayerSpawner,
    MultiplayerSynchronizer,
    Mutex,
    NativeMenu,
    NavigationAgent2D,
    NavigationAgent3D,
    NavigationLink2D,
    NavigationLink3D,
    NavigationMesh,
    NavigationMeshGenerator,
    NavigationMeshSourceGeometryData2D,
    NavigationMeshSourceGeometryData3D,
    NavigationObstacle2D,
    NavigationObstacle3D,
    NavigationPathQueryParameters2D,
    NavigationPathQueryParameters3D,
    NavigationPathQueryResult2D,
    NavigationPathQueryResult3D,
    NavigationPolygon,
    NavigationRegion2D,
    NavigationRegion3D,
    NavigationServer2D,
    NavigationServer3D,
    NinePatchRect,
    Node,
    Node2D,
    Node3D,
    Node3DGizmo,
    Noise,
    NoiseTexture2D,
    NoiseTexture3D,
    ORMMaterial3D,
    OS,
    Object,
    Occluder3D,
    OccluderInstance3D,
    OccluderPolygon2D,
    OfflineMultiplayerPeer,
    OggPacketSequence,
    OggPacketSequencePlayback,
    OmniLight3D,
    OpenXRAPIExtension,
    OpenXRAction,
    OpenXRActionBindingModifier,
    OpenXRActionMap,
    OpenXRActionSet,
    OpenXRAnalogThresholdModifier,
    OpenXRBindingModifier,
    OpenXRBindingModifierEditor,
    OpenXRCompositionLayer,
    OpenXRCompositionLayerCylinder,
    OpenXRCompositionLayerEquirect,
    OpenXRCompositionLayerQuad,
    OpenXRDpadBindingModifier,
    OpenXRExtensionWrapperExtension,
    OpenXRHand,
    OpenXRHapticBase,
    OpenXRHapticVibration,
    OpenXRIPBinding,
    OpenXRIPBindingModifier,
    OpenXRInteractionProfile,
    OpenXRInteractionProfileEditor,
    OpenXRInteractionProfileEditorBase,
    OpenXRInteractionProfileMetadata,
    OpenXRInterface,
    OpenXRVisibilityMask,
    OptimizedTranslation,
    OptionButton,
    PCKPacker,
    PackedDataContainer,
    PackedDataContainerRef,
    PackedScene,
    PacketPeer,
    PacketPeerDTLS,
    PacketPeerExtension,
    PacketPeerStream,
    PacketPeerUDP,
    Panel,
    PanelContainer,
    PanoramaSkyMaterial,
    Parallax2D,
    ParallaxBackground,
    ParallaxLayer,
    ParticleProcessMaterial,
    Path2D,
    Path3D,
    PathFollow2D,
    PathFollow3D,
    Performance,
    PhysicalBone2D,
    PhysicalBone3D,
    PhysicalBoneSimulator3D,
    PhysicalSkyMaterial,
    PhysicsBody2D,
    PhysicsBody3D,
    PhysicsDirectBodyState2D,
    PhysicsDirectBodyState2DExtension,
    PhysicsDirectBodyState3D,
    PhysicsDirectBodyState3DExtension,
    PhysicsDirectSpaceState2D,
    PhysicsDirectSpaceState2DExtension,
    PhysicsDirectSpaceState3D,
    PhysicsDirectSpaceState3DExtension,
    PhysicsMaterial,
    PhysicsPointQueryParameters2D,
    PhysicsPointQueryParameters3D,
    PhysicsRayQueryParameters2D,
    PhysicsRayQueryParameters3D,
    PhysicsServer2D,
    PhysicsServer2DExtension,
    PhysicsServer2DManager,
    PhysicsServer3D,
    PhysicsServer3DExtension,
    PhysicsServer3DManager,
    PhysicsServer3DRenderingServerHandler,
    PhysicsShapeQueryParameters2D,
    PhysicsShapeQueryParameters3D,
    PhysicsTestMotionParameters2D,
    PhysicsTestMotionParameters3D,
    PhysicsTestMotionResult2D,
    PhysicsTestMotionResult3D,
    PinJoint2D,
    PinJoint3D,
    PlaceholderCubemap,
    PlaceholderCubemapArray,
    PlaceholderMaterial,
    PlaceholderMesh,
    PlaceholderTexture2D,
    PlaceholderTexture2DArray,
    PlaceholderTexture3D,
    PlaceholderTextureLayered,
    PlaneMesh,
    PointLight2D,
    PointMesh,
    Polygon2D,
    PolygonOccluder3D,
    PolygonPathFinder,
    Popup,
    PopupMenu,
    PopupPanel,
    PortableCompressedTexture2D,
    PrimitiveMesh,
    PrismMesh,
    ProceduralSkyMaterial,
    ProgressBar,
    ProjectSettings,
    PropertyTweener,
    QuadMesh,
    QuadOccluder3D,
    RDAttachmentFormat,
    RDFramebufferPass,
    RDPipelineColorBlendState,
    RDPipelineColorBlendStateAttachment,
    RDPipelineDepthStencilState,
    RDPipelineMultisampleState,
    RDPipelineRasterizationState,
    RDPipelineSpecializationConstant,
    RDSamplerState,
    RDShaderFile,
    RDShaderSPIRV,
    RDShaderSource,
    RDTextureFormat,
    RDTextureView,
    RDUniform,
    RDVertexAttribute,
    RandomNumberGenerator,
    Range,
    RayCast2D,
    RayCast3D,
    RectangleShape2D,
    RefCounted,
    ReferenceRect,
    ReflectionProbe,
    RegEx,
    RegExMatch,
    RemoteTransform2D,
    RemoteTransform3D,
    RenderData,
    RenderDataExtension,
    RenderDataRD,
    RenderSceneBuffers,
    RenderSceneBuffersConfiguration,
    RenderSceneBuffersExtension,
    RenderSceneBuffersRD,
    RenderSceneData,
    RenderSceneDataExtension,
    RenderSceneDataRD,
    RenderingDevice,
    RenderingServer,
    Resource,
    ResourceFormatLoader,
    ResourceFormatSaver,
    ResourceImporter,
    ResourceImporterBMFont,
    ResourceImporterBitMap,
    ResourceImporterCSVTranslation,
    ResourceImporterDynamicFont,
    ResourceImporterImage,
    ResourceImporterImageFont,
    ResourceImporterLayeredTexture,
    ResourceImporterMP3,
    ResourceImporterOBJ,
    ResourceImporterOggVorbis,
    ResourceImporterScene,
    ResourceImporterShaderFile,
    ResourceImporterTexture,
    ResourceImporterTextureAtlas,
    ResourceImporterWAV,
    ResourceLoader,
    ResourcePreloader,
    ResourceSaver,
    ResourceUID,
    RetargetModifier3D,
    RibbonTrailMesh,
    RichTextEffect,
    RichTextLabel,
    RigidBody2D,
    RigidBody3D,
    RootMotionView,
    SceneMultiplayer,
    SceneReplicationConfig,
    SceneState,
    SceneTree,
    SceneTreeTimer,
    Script,
    ScriptCreateDialog,
    ScriptEditor,
    ScriptEditorBase,
    ScriptExtension,
    ScriptLanguage,
    ScriptLanguageExtension,
    ScrollBar,
    ScrollContainer,
    SegmentShape2D,
    Semaphore,
    SeparationRayShape2D,
    SeparationRayShape3D,
    Separator,
    Shader,
    ShaderGlobalsOverride,
    ShaderInclude,
    ShaderIncludeDB,
    ShaderMaterial,
    Shape2D,
    Shape3D,
    ShapeCast2D,
    ShapeCast3D,
    Shortcut,
    Skeleton2D,
    Skeleton3D,
    SkeletonIK3D,
    SkeletonModification2D,
    SkeletonModification2DCCDIK,
    SkeletonModification2DFABRIK,
    SkeletonModification2DJiggle,
    SkeletonModification2DLookAt,
    SkeletonModification2DPhysicalBones,
    SkeletonModification2DStackHolder,
    SkeletonModification2DTwoBoneIK,
    SkeletonModificationStack2D,
    SkeletonModifier3D,
    SkeletonProfile,
    SkeletonProfileHumanoid,
    Skin,
    SkinReference,
    Sky,
    Slider,
    SliderJoint3D,
    SoftBody3D,
    SphereMesh,
    SphereOccluder3D,
    SphereShape3D,
    SpinBox,
    SplitContainer,
    SpotLight3D,
    SpringArm3D,
    SpringBoneCollision3D,
    SpringBoneCollisionCapsule3D,
    SpringBoneCollisionPlane3D,
    SpringBoneCollisionSphere3D,
    SpringBoneSimulator3D,
    Sprite2D,
    Sprite3D,
    SpriteBase3D,
    SpriteFrames,
    StandardMaterial3D,
    StaticBody2D,
    StaticBody3D,
    StatusIndicator,
    StreamPeer,
    StreamPeerBuffer,
    StreamPeerExtension,
    StreamPeerGZIP,
    StreamPeerTCP,
    StreamPeerTLS,
    StyleBox,
    StyleBoxEmpty,
    StyleBoxFlat,
    StyleBoxLine,
    StyleBoxTexture,
    SubViewport,
    SubViewportContainer,
    SubtweenTweener,
    SurfaceTool,
    SyntaxHighlighter,
    SystemFont,
    TCPServer,
    TLSOptions,
    TabBar,
    TabContainer,
    TextEdit,
    TextLine,
    TextMesh,
    TextParagraph,
    TextServer,
    TextServerAdvanced,
    TextServerDummy,
    TextServerExtension,
    TextServerManager,
    Texture,
    Texture2D,
    Texture2DArray,
    Texture2DArrayRD,
    Texture2DRD,
    Texture3D,
    Texture3DRD,
    TextureButton,
    TextureCubemapArrayRD,
    TextureCubemapRD,
    TextureLayered,
    TextureLayeredRD,
    TextureProgressBar,
    TextureRect,
    Theme,
    ThemeDB,
    Thread,
    TileData,
    TileMap,
    TileMapLayer,
    TileMapPattern,
    TileSet,
    TileSetAtlasSource,
    TileSetScenesCollectionSource,
    TileSetSource,
    Time,
    Timer,
    TorusMesh,
    TouchScreenButton,
    Translation,
    TranslationDomain,
    TranslationServer,
    Tree,
    TreeItem,
    TriangleMesh,
    TubeTrailMesh,
    Tween,
    Tweener,
    UDPServer,
    UPNP,
    UPNPDevice,
    UndoRedo,
    UniformSetCacheRD,
    VBoxContainer,
    VFlowContainer,
    VScrollBar,
    VSeparator,
    VSlider,
    VSplitContainer,
    VehicleBody3D,
    VehicleWheel3D,
    VideoStream,
    VideoStreamPlayback,
    VideoStreamPlayer,
    VideoStreamTheora,
    Viewport,
    ViewportTexture,
    VisibleOnScreenEnabler2D,
    VisibleOnScreenEnabler3D,
    VisibleOnScreenNotifier2D,
    VisibleOnScreenNotifier3D,
    VisualInstance3D,
    VisualShader,
    VisualShaderNode,
    VisualShaderNodeBillboard,
    VisualShaderNodeBooleanConstant,
    VisualShaderNodeBooleanParameter,
    VisualShaderNodeClamp,
    VisualShaderNodeColorConstant,
    VisualShaderNodeColorFunc,
    VisualShaderNodeColorOp,
    VisualShaderNodeColorParameter,
    VisualShaderNodeComment,
    VisualShaderNodeCompare,
    VisualShaderNodeConstant,
    VisualShaderNodeCubemap,
    VisualShaderNodeCubemapParameter,
    VisualShaderNodeCurveTexture,
    VisualShaderNodeCurveXYZTexture,
    VisualShaderNodeCustom,
    VisualShaderNodeDerivativeFunc,
    VisualShaderNodeDeterminant,
    VisualShaderNodeDistanceFade,
    VisualShaderNodeDotProduct,
    VisualShaderNodeExpression,
    VisualShaderNodeFaceForward,
    VisualShaderNodeFloatConstant,
    VisualShaderNodeFloatFunc,
    VisualShaderNodeFloatOp,
    VisualShaderNodeFloatParameter,
    VisualShaderNodeFrame,
    VisualShaderNodeFresnel,
    VisualShaderNodeGlobalExpression,
    VisualShaderNodeGroupBase,
    VisualShaderNodeIf,
    VisualShaderNodeInput,
    VisualShaderNodeIntConstant,
    VisualShaderNodeIntFunc,
    VisualShaderNodeIntOp,
    VisualShaderNodeIntParameter,
    VisualShaderNodeIs,
    VisualShaderNodeLinearSceneDepth,
    VisualShaderNodeMix,
    VisualShaderNodeMultiplyAdd,
    VisualShaderNodeOuterProduct,
    VisualShaderNodeOutput,
    VisualShaderNodeParameter,
    VisualShaderNodeParameterRef,
    VisualShaderNodeParticleAccelerator,
    VisualShaderNodeParticleBoxEmitter,
    VisualShaderNodeParticleConeVelocity,
    VisualShaderNodeParticleEmit,
    VisualShaderNodeParticleEmitter,
    VisualShaderNodeParticleMeshEmitter,
    VisualShaderNodeParticleMultiplyByAxisAngle,
    VisualShaderNodeParticleOutput,
    VisualShaderNodeParticleRandomness,
    VisualShaderNodeParticleRingEmitter,
    VisualShaderNodeParticleSphereEmitter,
    VisualShaderNodeProximityFade,
    VisualShaderNodeRandomRange,
    VisualShaderNodeRemap,
    VisualShaderNodeReroute,
    VisualShaderNodeResizableBase,
    VisualShaderNodeRotationByAxis,
    VisualShaderNodeSDFRaymarch,
    VisualShaderNodeSDFToScreenUV,
    VisualShaderNodeSample3D,
    VisualShaderNodeScreenNormalWorldSpace,
    VisualShaderNodeScreenUVToSDF,
    VisualShaderNodeSmoothStep,
    VisualShaderNodeStep,
    VisualShaderNodeSwitch,
    VisualShaderNodeTexture,
    VisualShaderNodeTexture2DArray,
    VisualShaderNodeTexture2DArrayParameter,
    VisualShaderNodeTexture2DParameter,
    VisualShaderNodeTexture3D,
    VisualShaderNodeTexture3DParameter,
    VisualShaderNodeTextureParameter,
    VisualShaderNodeTextureParameterTriplanar,
    VisualShaderNodeTextureSDF,
    VisualShaderNodeTextureSDFNormal,
    VisualShaderNodeTransformCompose,
    VisualShaderNodeTransformConstant,
    VisualShaderNodeTransformDecompose,
    VisualShaderNodeTransformFunc,
    VisualShaderNodeTransformOp,
    VisualShaderNodeTransformParameter,
    VisualShaderNodeTransformVecMult,
    VisualShaderNodeUIntConstant,
    VisualShaderNodeUIntFunc,
    VisualShaderNodeUIntOp,
    VisualShaderNodeUIntParameter,
    VisualShaderNodeUVFunc,
    VisualShaderNodeUVPolarCoord,
    VisualShaderNodeVarying,
    VisualShaderNodeVaryingGetter,
    VisualShaderNodeVaryingSetter,
    VisualShaderNodeVec2Constant,
    VisualShaderNodeVec2Parameter,
    VisualShaderNodeVec3Constant,
    VisualShaderNodeVec3Parameter,
    VisualShaderNodeVec4Constant,
    VisualShaderNodeVec4Parameter,
    VisualShaderNodeVectorBase,
    VisualShaderNodeVectorCompose,
    VisualShaderNodeVectorDecompose,
    VisualShaderNodeVectorDistance,
    VisualShaderNodeVectorFunc,
    VisualShaderNodeVectorLen,
    VisualShaderNodeVectorOp,
    VisualShaderNodeVectorRefract,
    VisualShaderNodeWorldPositionFromDepth,
    VoxelGI,
    VoxelGIData,
    WeakRef,
    WebRTCDataChannel,
    WebRTCDataChannelExtension,
    WebRTCMultiplayerPeer,
    WebRTCPeerConnection,
    WebRTCPeerConnectionExtension,
    WebSocketMultiplayerPeer,
    WebSocketPeer,
    WebXRInterface,
    Window,
    WorkerThreadPool,
    World2D,
    World3D,
    WorldBoundaryShape2D,
    WorldBoundaryShape3D,
    WorldEnvironment,
    X509Certificate,
    XMLParser,
    XRAnchor3D,
    XRBodyModifier3D,
    XRBodyTracker,
    XRCamera3D,
    XRController3D,
    XRControllerTracker,
    XRFaceModifier3D,
    XRFaceTracker,
    XRHandModifier3D,
    XRHandTracker,
    XRInterface,
    XRInterfaceExtension,
    XRNode3D,
    XROrigin3D,
    XRPose,
    XRPositionalTracker,
    XRServer,
    XRTracker,
    XRVRS,
    ZIPPacker,
    ZIPReader,
    Master,
}

@(private)
ClassName_StringNames : [ClassName_Index]StringName = {
    .nil = StringName({nil}),
    .AESContext = StringName({nil}),
    .AStar2D = StringName({nil}),
    .AStar3D = StringName({nil}),
    .AStarGrid2D = StringName({nil}),
    .AcceptDialog = StringName({nil}),
    .AnimatableBody2D = StringName({nil}),
    .AnimatableBody3D = StringName({nil}),
    .AnimatedSprite2D = StringName({nil}),
    .AnimatedSprite3D = StringName({nil}),
    .AnimatedTexture = StringName({nil}),
    .Animation = StringName({nil}),
    .AnimationLibrary = StringName({nil}),
    .AnimationMixer = StringName({nil}),
    .AnimationNode = StringName({nil}),
    .AnimationNodeAdd2 = StringName({nil}),
    .AnimationNodeAdd3 = StringName({nil}),
    .AnimationNodeAnimation = StringName({nil}),
    .AnimationNodeBlend2 = StringName({nil}),
    .AnimationNodeBlend3 = StringName({nil}),
    .AnimationNodeBlendSpace1D = StringName({nil}),
    .AnimationNodeBlendSpace2D = StringName({nil}),
    .AnimationNodeBlendTree = StringName({nil}),
    .AnimationNodeExtension = StringName({nil}),
    .AnimationNodeOneShot = StringName({nil}),
    .AnimationNodeOutput = StringName({nil}),
    .AnimationNodeStateMachine = StringName({nil}),
    .AnimationNodeStateMachinePlayback = StringName({nil}),
    .AnimationNodeStateMachineTransition = StringName({nil}),
    .AnimationNodeSub2 = StringName({nil}),
    .AnimationNodeSync = StringName({nil}),
    .AnimationNodeTimeScale = StringName({nil}),
    .AnimationNodeTimeSeek = StringName({nil}),
    .AnimationNodeTransition = StringName({nil}),
    .AnimationPlayer = StringName({nil}),
    .AnimationRootNode = StringName({nil}),
    .AnimationTree = StringName({nil}),
    .Area2D = StringName({nil}),
    .Area3D = StringName({nil}),
    .ArrayMesh = StringName({nil}),
    .ArrayOccluder3D = StringName({nil}),
    .AspectRatioContainer = StringName({nil}),
    .AtlasTexture = StringName({nil}),
    .AudioBusLayout = StringName({nil}),
    .AudioEffect = StringName({nil}),
    .AudioEffectAmplify = StringName({nil}),
    .AudioEffectBandLimitFilter = StringName({nil}),
    .AudioEffectBandPassFilter = StringName({nil}),
    .AudioEffectCapture = StringName({nil}),
    .AudioEffectChorus = StringName({nil}),
    .AudioEffectCompressor = StringName({nil}),
    .AudioEffectDelay = StringName({nil}),
    .AudioEffectDistortion = StringName({nil}),
    .AudioEffectEQ = StringName({nil}),
    .AudioEffectEQ10 = StringName({nil}),
    .AudioEffectEQ21 = StringName({nil}),
    .AudioEffectEQ6 = StringName({nil}),
    .AudioEffectFilter = StringName({nil}),
    .AudioEffectHardLimiter = StringName({nil}),
    .AudioEffectHighPassFilter = StringName({nil}),
    .AudioEffectHighShelfFilter = StringName({nil}),
    .AudioEffectInstance = StringName({nil}),
    .AudioEffectLimiter = StringName({nil}),
    .AudioEffectLowPassFilter = StringName({nil}),
    .AudioEffectLowShelfFilter = StringName({nil}),
    .AudioEffectNotchFilter = StringName({nil}),
    .AudioEffectPanner = StringName({nil}),
    .AudioEffectPhaser = StringName({nil}),
    .AudioEffectPitchShift = StringName({nil}),
    .AudioEffectRecord = StringName({nil}),
    .AudioEffectReverb = StringName({nil}),
    .AudioEffectSpectrumAnalyzer = StringName({nil}),
    .AudioEffectSpectrumAnalyzerInstance = StringName({nil}),
    .AudioEffectStereoEnhance = StringName({nil}),
    .AudioListener2D = StringName({nil}),
    .AudioListener3D = StringName({nil}),
    .AudioSample = StringName({nil}),
    .AudioSamplePlayback = StringName({nil}),
    .AudioServer = StringName({nil}),
    .AudioStream = StringName({nil}),
    .AudioStreamGenerator = StringName({nil}),
    .AudioStreamGeneratorPlayback = StringName({nil}),
    .AudioStreamInteractive = StringName({nil}),
    .AudioStreamMP3 = StringName({nil}),
    .AudioStreamMicrophone = StringName({nil}),
    .AudioStreamOggVorbis = StringName({nil}),
    .AudioStreamPlayback = StringName({nil}),
    .AudioStreamPlaybackInteractive = StringName({nil}),
    .AudioStreamPlaybackOggVorbis = StringName({nil}),
    .AudioStreamPlaybackPlaylist = StringName({nil}),
    .AudioStreamPlaybackPolyphonic = StringName({nil}),
    .AudioStreamPlaybackResampled = StringName({nil}),
    .AudioStreamPlaybackSynchronized = StringName({nil}),
    .AudioStreamPlayer = StringName({nil}),
    .AudioStreamPlayer2D = StringName({nil}),
    .AudioStreamPlayer3D = StringName({nil}),
    .AudioStreamPlaylist = StringName({nil}),
    .AudioStreamPolyphonic = StringName({nil}),
    .AudioStreamRandomizer = StringName({nil}),
    .AudioStreamSynchronized = StringName({nil}),
    .AudioStreamWAV = StringName({nil}),
    .BackBufferCopy = StringName({nil}),
    .BaseButton = StringName({nil}),
    .BaseMaterial3D = StringName({nil}),
    .BitMap = StringName({nil}),
    .Bone2D = StringName({nil}),
    .BoneAttachment3D = StringName({nil}),
    .BoneMap = StringName({nil}),
    .BoxContainer = StringName({nil}),
    .BoxMesh = StringName({nil}),
    .BoxOccluder3D = StringName({nil}),
    .BoxShape3D = StringName({nil}),
    .Button = StringName({nil}),
    .ButtonGroup = StringName({nil}),
    .CPUParticles2D = StringName({nil}),
    .CPUParticles3D = StringName({nil}),
    .CSGBox3D = StringName({nil}),
    .CSGCombiner3D = StringName({nil}),
    .CSGCylinder3D = StringName({nil}),
    .CSGMesh3D = StringName({nil}),
    .CSGPolygon3D = StringName({nil}),
    .CSGPrimitive3D = StringName({nil}),
    .CSGShape3D = StringName({nil}),
    .CSGSphere3D = StringName({nil}),
    .CSGTorus3D = StringName({nil}),
    .CallbackTweener = StringName({nil}),
    .Camera2D = StringName({nil}),
    .Camera3D = StringName({nil}),
    .CameraAttributes = StringName({nil}),
    .CameraAttributesPhysical = StringName({nil}),
    .CameraAttributesPractical = StringName({nil}),
    .CameraFeed = StringName({nil}),
    .CameraServer = StringName({nil}),
    .CameraTexture = StringName({nil}),
    .CanvasGroup = StringName({nil}),
    .CanvasItem = StringName({nil}),
    .CanvasItemMaterial = StringName({nil}),
    .CanvasLayer = StringName({nil}),
    .CanvasModulate = StringName({nil}),
    .CanvasTexture = StringName({nil}),
    .CapsuleMesh = StringName({nil}),
    .CapsuleShape2D = StringName({nil}),
    .CapsuleShape3D = StringName({nil}),
    .CenterContainer = StringName({nil}),
    .CharFXTransform = StringName({nil}),
    .CharacterBody2D = StringName({nil}),
    .CharacterBody3D = StringName({nil}),
    .CheckBox = StringName({nil}),
    .CheckButton = StringName({nil}),
    .CircleShape2D = StringName({nil}),
    .ClassDB = StringName({nil}),
    .CodeEdit = StringName({nil}),
    .CodeHighlighter = StringName({nil}),
    .CollisionObject2D = StringName({nil}),
    .CollisionObject3D = StringName({nil}),
    .CollisionPolygon2D = StringName({nil}),
    .CollisionPolygon3D = StringName({nil}),
    .CollisionShape2D = StringName({nil}),
    .CollisionShape3D = StringName({nil}),
    .ColorPalette = StringName({nil}),
    .ColorPicker = StringName({nil}),
    .ColorPickerButton = StringName({nil}),
    .ColorRect = StringName({nil}),
    .Compositor = StringName({nil}),
    .CompositorEffect = StringName({nil}),
    .CompressedCubemap = StringName({nil}),
    .CompressedCubemapArray = StringName({nil}),
    .CompressedTexture2D = StringName({nil}),
    .CompressedTexture2DArray = StringName({nil}),
    .CompressedTexture3D = StringName({nil}),
    .CompressedTextureLayered = StringName({nil}),
    .ConcavePolygonShape2D = StringName({nil}),
    .ConcavePolygonShape3D = StringName({nil}),
    .ConeTwistJoint3D = StringName({nil}),
    .ConfigFile = StringName({nil}),
    .ConfirmationDialog = StringName({nil}),
    .Container = StringName({nil}),
    .Control = StringName({nil}),
    .ConvexPolygonShape2D = StringName({nil}),
    .ConvexPolygonShape3D = StringName({nil}),
    .Crypto = StringName({nil}),
    .CryptoKey = StringName({nil}),
    .Cubemap = StringName({nil}),
    .CubemapArray = StringName({nil}),
    .Curve = StringName({nil}),
    .Curve2D = StringName({nil}),
    .Curve3D = StringName({nil}),
    .CurveTexture = StringName({nil}),
    .CurveXYZTexture = StringName({nil}),
    .CylinderMesh = StringName({nil}),
    .CylinderShape3D = StringName({nil}),
    .DTLSServer = StringName({nil}),
    .DampedSpringJoint2D = StringName({nil}),
    .Decal = StringName({nil}),
    .DirAccess = StringName({nil}),
    .DirectionalLight2D = StringName({nil}),
    .DirectionalLight3D = StringName({nil}),
    .DisplayServer = StringName({nil}),
    .ENetConnection = StringName({nil}),
    .ENetMultiplayerPeer = StringName({nil}),
    .ENetPacketPeer = StringName({nil}),
    .EditorCommandPalette = StringName({nil}),
    .EditorContextMenuPlugin = StringName({nil}),
    .EditorDebuggerPlugin = StringName({nil}),
    .EditorDebuggerSession = StringName({nil}),
    .EditorExportPlatform = StringName({nil}),
    .EditorExportPlatformAndroid = StringName({nil}),
    .EditorExportPlatformExtension = StringName({nil}),
    .EditorExportPlatformIOS = StringName({nil}),
    .EditorExportPlatformLinuxBSD = StringName({nil}),
    .EditorExportPlatformMacOS = StringName({nil}),
    .EditorExportPlatformPC = StringName({nil}),
    .EditorExportPlatformWeb = StringName({nil}),
    .EditorExportPlatformWindows = StringName({nil}),
    .EditorExportPlugin = StringName({nil}),
    .EditorExportPreset = StringName({nil}),
    .EditorFeatureProfile = StringName({nil}),
    .EditorFileDialog = StringName({nil}),
    .EditorFileSystem = StringName({nil}),
    .EditorFileSystemDirectory = StringName({nil}),
    .EditorFileSystemImportFormatSupportQuery = StringName({nil}),
    .EditorImportPlugin = StringName({nil}),
    .EditorInspector = StringName({nil}),
    .EditorInspectorPlugin = StringName({nil}),
    .EditorInterface = StringName({nil}),
    .EditorNode3DGizmo = StringName({nil}),
    .EditorNode3DGizmoPlugin = StringName({nil}),
    .EditorPaths = StringName({nil}),
    .EditorPlugin = StringName({nil}),
    .EditorProperty = StringName({nil}),
    .EditorResourceConversionPlugin = StringName({nil}),
    .EditorResourcePicker = StringName({nil}),
    .EditorResourcePreview = StringName({nil}),
    .EditorResourcePreviewGenerator = StringName({nil}),
    .EditorResourceTooltipPlugin = StringName({nil}),
    .EditorSceneFormatImporter = StringName({nil}),
    .EditorSceneFormatImporterBlend = StringName({nil}),
    .EditorSceneFormatImporterFBX2GLTF = StringName({nil}),
    .EditorSceneFormatImporterGLTF = StringName({nil}),
    .EditorSceneFormatImporterUFBX = StringName({nil}),
    .EditorScenePostImport = StringName({nil}),
    .EditorScenePostImportPlugin = StringName({nil}),
    .EditorScript = StringName({nil}),
    .EditorScriptPicker = StringName({nil}),
    .EditorSelection = StringName({nil}),
    .EditorSettings = StringName({nil}),
    .EditorSpinSlider = StringName({nil}),
    .EditorSyntaxHighlighter = StringName({nil}),
    .EditorToaster = StringName({nil}),
    .EditorTranslationParserPlugin = StringName({nil}),
    .EditorUndoRedoManager = StringName({nil}),
    .EditorVCSInterface = StringName({nil}),
    .EncodedObjectAsID = StringName({nil}),
    .Engine = StringName({nil}),
    .EngineDebugger = StringName({nil}),
    .EngineProfiler = StringName({nil}),
    .Environment = StringName({nil}),
    .Expression = StringName({nil}),
    .ExternalTexture = StringName({nil}),
    .FBXDocument = StringName({nil}),
    .FBXState = StringName({nil}),
    .FastNoiseLite = StringName({nil}),
    .FileAccess = StringName({nil}),
    .FileDialog = StringName({nil}),
    .FileSystemDock = StringName({nil}),
    .FlowContainer = StringName({nil}),
    .FogMaterial = StringName({nil}),
    .FogVolume = StringName({nil}),
    .Font = StringName({nil}),
    .FontFile = StringName({nil}),
    .FontVariation = StringName({nil}),
    .FramebufferCacheRD = StringName({nil}),
    .GDExtension = StringName({nil}),
    .GDExtensionManager = StringName({nil}),
    .GDScript = StringName({nil}),
    .GDScriptSyntaxHighlighter = StringName({nil}),
    .GLTFAccessor = StringName({nil}),
    .GLTFAnimation = StringName({nil}),
    .GLTFBufferView = StringName({nil}),
    .GLTFCamera = StringName({nil}),
    .GLTFDocument = StringName({nil}),
    .GLTFDocumentExtension = StringName({nil}),
    .GLTFDocumentExtensionConvertImporterMesh = StringName({nil}),
    .GLTFLight = StringName({nil}),
    .GLTFMesh = StringName({nil}),
    .GLTFNode = StringName({nil}),
    .GLTFObjectModelProperty = StringName({nil}),
    .GLTFPhysicsBody = StringName({nil}),
    .GLTFPhysicsShape = StringName({nil}),
    .GLTFSkeleton = StringName({nil}),
    .GLTFSkin = StringName({nil}),
    .GLTFSpecGloss = StringName({nil}),
    .GLTFState = StringName({nil}),
    .GLTFTexture = StringName({nil}),
    .GLTFTextureSampler = StringName({nil}),
    .GPUParticles2D = StringName({nil}),
    .GPUParticles3D = StringName({nil}),
    .GPUParticlesAttractor3D = StringName({nil}),
    .GPUParticlesAttractorBox3D = StringName({nil}),
    .GPUParticlesAttractorSphere3D = StringName({nil}),
    .GPUParticlesAttractorVectorField3D = StringName({nil}),
    .GPUParticlesCollision3D = StringName({nil}),
    .GPUParticlesCollisionBox3D = StringName({nil}),
    .GPUParticlesCollisionHeightField3D = StringName({nil}),
    .GPUParticlesCollisionSDF3D = StringName({nil}),
    .GPUParticlesCollisionSphere3D = StringName({nil}),
    .Generic6DOFJoint3D = StringName({nil}),
    .Geometry2D = StringName({nil}),
    .Geometry3D = StringName({nil}),
    .GeometryInstance3D = StringName({nil}),
    .Gradient = StringName({nil}),
    .GradientTexture1D = StringName({nil}),
    .GradientTexture2D = StringName({nil}),
    .GraphEdit = StringName({nil}),
    .GraphElement = StringName({nil}),
    .GraphFrame = StringName({nil}),
    .GraphNode = StringName({nil}),
    .GridContainer = StringName({nil}),
    .GridMap = StringName({nil}),
    .GridMapEditorPlugin = StringName({nil}),
    .GrooveJoint2D = StringName({nil}),
    .HBoxContainer = StringName({nil}),
    .HFlowContainer = StringName({nil}),
    .HMACContext = StringName({nil}),
    .HScrollBar = StringName({nil}),
    .HSeparator = StringName({nil}),
    .HSlider = StringName({nil}),
    .HSplitContainer = StringName({nil}),
    .HTTPClient = StringName({nil}),
    .HTTPRequest = StringName({nil}),
    .HashingContext = StringName({nil}),
    .HeightMapShape3D = StringName({nil}),
    .HingeJoint3D = StringName({nil}),
    .IP = StringName({nil}),
    .Image = StringName({nil}),
    .ImageFormatLoader = StringName({nil}),
    .ImageFormatLoaderExtension = StringName({nil}),
    .ImageTexture = StringName({nil}),
    .ImageTexture3D = StringName({nil}),
    .ImageTextureLayered = StringName({nil}),
    .ImmediateMesh = StringName({nil}),
    .ImporterMesh = StringName({nil}),
    .ImporterMeshInstance3D = StringName({nil}),
    .Input = StringName({nil}),
    .InputEvent = StringName({nil}),
    .InputEventAction = StringName({nil}),
    .InputEventFromWindow = StringName({nil}),
    .InputEventGesture = StringName({nil}),
    .InputEventJoypadButton = StringName({nil}),
    .InputEventJoypadMotion = StringName({nil}),
    .InputEventKey = StringName({nil}),
    .InputEventMIDI = StringName({nil}),
    .InputEventMagnifyGesture = StringName({nil}),
    .InputEventMouse = StringName({nil}),
    .InputEventMouseButton = StringName({nil}),
    .InputEventMouseMotion = StringName({nil}),
    .InputEventPanGesture = StringName({nil}),
    .InputEventScreenDrag = StringName({nil}),
    .InputEventScreenTouch = StringName({nil}),
    .InputEventShortcut = StringName({nil}),
    .InputEventWithModifiers = StringName({nil}),
    .InputMap = StringName({nil}),
    .InstancePlaceholder = StringName({nil}),
    .IntervalTweener = StringName({nil}),
    .ItemList = StringName({nil}),
    .JNISingleton = StringName({nil}),
    .JSON = StringName({nil}),
    .JSONRPC = StringName({nil}),
    .JavaClass = StringName({nil}),
    .JavaClassWrapper = StringName({nil}),
    .JavaObject = StringName({nil}),
    .JavaScriptBridge = StringName({nil}),
    .JavaScriptObject = StringName({nil}),
    .Joint2D = StringName({nil}),
    .Joint3D = StringName({nil}),
    .KinematicCollision2D = StringName({nil}),
    .KinematicCollision3D = StringName({nil}),
    .Label = StringName({nil}),
    .Label3D = StringName({nil}),
    .LabelSettings = StringName({nil}),
    .Light2D = StringName({nil}),
    .Light3D = StringName({nil}),
    .LightOccluder2D = StringName({nil}),
    .LightmapGI = StringName({nil}),
    .LightmapGIData = StringName({nil}),
    .LightmapProbe = StringName({nil}),
    .Lightmapper = StringName({nil}),
    .LightmapperRD = StringName({nil}),
    .Line2D = StringName({nil}),
    .LineEdit = StringName({nil}),
    .LinkButton = StringName({nil}),
    .LookAtModifier3D = StringName({nil}),
    .MainLoop = StringName({nil}),
    .MarginContainer = StringName({nil}),
    .Marker2D = StringName({nil}),
    .Marker3D = StringName({nil}),
    .Marshalls = StringName({nil}),
    .Material = StringName({nil}),
    .MenuBar = StringName({nil}),
    .MenuButton = StringName({nil}),
    .Mesh = StringName({nil}),
    .MeshConvexDecompositionSettings = StringName({nil}),
    .MeshDataTool = StringName({nil}),
    .MeshInstance2D = StringName({nil}),
    .MeshInstance3D = StringName({nil}),
    .MeshLibrary = StringName({nil}),
    .MeshTexture = StringName({nil}),
    .MethodTweener = StringName({nil}),
    .MissingNode = StringName({nil}),
    .MissingResource = StringName({nil}),
    .MobileVRInterface = StringName({nil}),
    .MovieWriter = StringName({nil}),
    .MultiMesh = StringName({nil}),
    .MultiMeshInstance2D = StringName({nil}),
    .MultiMeshInstance3D = StringName({nil}),
    .MultiplayerAPI = StringName({nil}),
    .MultiplayerAPIExtension = StringName({nil}),
    .MultiplayerPeer = StringName({nil}),
    .MultiplayerPeerExtension = StringName({nil}),
    .MultiplayerSpawner = StringName({nil}),
    .MultiplayerSynchronizer = StringName({nil}),
    .Mutex = StringName({nil}),
    .NativeMenu = StringName({nil}),
    .NavigationAgent2D = StringName({nil}),
    .NavigationAgent3D = StringName({nil}),
    .NavigationLink2D = StringName({nil}),
    .NavigationLink3D = StringName({nil}),
    .NavigationMesh = StringName({nil}),
    .NavigationMeshGenerator = StringName({nil}),
    .NavigationMeshSourceGeometryData2D = StringName({nil}),
    .NavigationMeshSourceGeometryData3D = StringName({nil}),
    .NavigationObstacle2D = StringName({nil}),
    .NavigationObstacle3D = StringName({nil}),
    .NavigationPathQueryParameters2D = StringName({nil}),
    .NavigationPathQueryParameters3D = StringName({nil}),
    .NavigationPathQueryResult2D = StringName({nil}),
    .NavigationPathQueryResult3D = StringName({nil}),
    .NavigationPolygon = StringName({nil}),
    .NavigationRegion2D = StringName({nil}),
    .NavigationRegion3D = StringName({nil}),
    .NavigationServer2D = StringName({nil}),
    .NavigationServer3D = StringName({nil}),
    .NinePatchRect = StringName({nil}),
    .Node = StringName({nil}),
    .Node2D = StringName({nil}),
    .Node3D = StringName({nil}),
    .Node3DGizmo = StringName({nil}),
    .Noise = StringName({nil}),
    .NoiseTexture2D = StringName({nil}),
    .NoiseTexture3D = StringName({nil}),
    .ORMMaterial3D = StringName({nil}),
    .OS = StringName({nil}),
    .Object = StringName({nil}),
    .Occluder3D = StringName({nil}),
    .OccluderInstance3D = StringName({nil}),
    .OccluderPolygon2D = StringName({nil}),
    .OfflineMultiplayerPeer = StringName({nil}),
    .OggPacketSequence = StringName({nil}),
    .OggPacketSequencePlayback = StringName({nil}),
    .OmniLight3D = StringName({nil}),
    .OpenXRAPIExtension = StringName({nil}),
    .OpenXRAction = StringName({nil}),
    .OpenXRActionBindingModifier = StringName({nil}),
    .OpenXRActionMap = StringName({nil}),
    .OpenXRActionSet = StringName({nil}),
    .OpenXRAnalogThresholdModifier = StringName({nil}),
    .OpenXRBindingModifier = StringName({nil}),
    .OpenXRBindingModifierEditor = StringName({nil}),
    .OpenXRCompositionLayer = StringName({nil}),
    .OpenXRCompositionLayerCylinder = StringName({nil}),
    .OpenXRCompositionLayerEquirect = StringName({nil}),
    .OpenXRCompositionLayerQuad = StringName({nil}),
    .OpenXRDpadBindingModifier = StringName({nil}),
    .OpenXRExtensionWrapperExtension = StringName({nil}),
    .OpenXRHand = StringName({nil}),
    .OpenXRHapticBase = StringName({nil}),
    .OpenXRHapticVibration = StringName({nil}),
    .OpenXRIPBinding = StringName({nil}),
    .OpenXRIPBindingModifier = StringName({nil}),
    .OpenXRInteractionProfile = StringName({nil}),
    .OpenXRInteractionProfileEditor = StringName({nil}),
    .OpenXRInteractionProfileEditorBase = StringName({nil}),
    .OpenXRInteractionProfileMetadata = StringName({nil}),
    .OpenXRInterface = StringName({nil}),
    .OpenXRVisibilityMask = StringName({nil}),
    .OptimizedTranslation = StringName({nil}),
    .OptionButton = StringName({nil}),
    .PCKPacker = StringName({nil}),
    .PackedDataContainer = StringName({nil}),
    .PackedDataContainerRef = StringName({nil}),
    .PackedScene = StringName({nil}),
    .PacketPeer = StringName({nil}),
    .PacketPeerDTLS = StringName({nil}),
    .PacketPeerExtension = StringName({nil}),
    .PacketPeerStream = StringName({nil}),
    .PacketPeerUDP = StringName({nil}),
    .Panel = StringName({nil}),
    .PanelContainer = StringName({nil}),
    .PanoramaSkyMaterial = StringName({nil}),
    .Parallax2D = StringName({nil}),
    .ParallaxBackground = StringName({nil}),
    .ParallaxLayer = StringName({nil}),
    .ParticleProcessMaterial = StringName({nil}),
    .Path2D = StringName({nil}),
    .Path3D = StringName({nil}),
    .PathFollow2D = StringName({nil}),
    .PathFollow3D = StringName({nil}),
    .Performance = StringName({nil}),
    .PhysicalBone2D = StringName({nil}),
    .PhysicalBone3D = StringName({nil}),
    .PhysicalBoneSimulator3D = StringName({nil}),
    .PhysicalSkyMaterial = StringName({nil}),
    .PhysicsBody2D = StringName({nil}),
    .PhysicsBody3D = StringName({nil}),
    .PhysicsDirectBodyState2D = StringName({nil}),
    .PhysicsDirectBodyState2DExtension = StringName({nil}),
    .PhysicsDirectBodyState3D = StringName({nil}),
    .PhysicsDirectBodyState3DExtension = StringName({nil}),
    .PhysicsDirectSpaceState2D = StringName({nil}),
    .PhysicsDirectSpaceState2DExtension = StringName({nil}),
    .PhysicsDirectSpaceState3D = StringName({nil}),
    .PhysicsDirectSpaceState3DExtension = StringName({nil}),
    .PhysicsMaterial = StringName({nil}),
    .PhysicsPointQueryParameters2D = StringName({nil}),
    .PhysicsPointQueryParameters3D = StringName({nil}),
    .PhysicsRayQueryParameters2D = StringName({nil}),
    .PhysicsRayQueryParameters3D = StringName({nil}),
    .PhysicsServer2D = StringName({nil}),
    .PhysicsServer2DExtension = StringName({nil}),
    .PhysicsServer2DManager = StringName({nil}),
    .PhysicsServer3D = StringName({nil}),
    .PhysicsServer3DExtension = StringName({nil}),
    .PhysicsServer3DManager = StringName({nil}),
    .PhysicsServer3DRenderingServerHandler = StringName({nil}),
    .PhysicsShapeQueryParameters2D = StringName({nil}),
    .PhysicsShapeQueryParameters3D = StringName({nil}),
    .PhysicsTestMotionParameters2D = StringName({nil}),
    .PhysicsTestMotionParameters3D = StringName({nil}),
    .PhysicsTestMotionResult2D = StringName({nil}),
    .PhysicsTestMotionResult3D = StringName({nil}),
    .PinJoint2D = StringName({nil}),
    .PinJoint3D = StringName({nil}),
    .PlaceholderCubemap = StringName({nil}),
    .PlaceholderCubemapArray = StringName({nil}),
    .PlaceholderMaterial = StringName({nil}),
    .PlaceholderMesh = StringName({nil}),
    .PlaceholderTexture2D = StringName({nil}),
    .PlaceholderTexture2DArray = StringName({nil}),
    .PlaceholderTexture3D = StringName({nil}),
    .PlaceholderTextureLayered = StringName({nil}),
    .PlaneMesh = StringName({nil}),
    .PointLight2D = StringName({nil}),
    .PointMesh = StringName({nil}),
    .Polygon2D = StringName({nil}),
    .PolygonOccluder3D = StringName({nil}),
    .PolygonPathFinder = StringName({nil}),
    .Popup = StringName({nil}),
    .PopupMenu = StringName({nil}),
    .PopupPanel = StringName({nil}),
    .PortableCompressedTexture2D = StringName({nil}),
    .PrimitiveMesh = StringName({nil}),
    .PrismMesh = StringName({nil}),
    .ProceduralSkyMaterial = StringName({nil}),
    .ProgressBar = StringName({nil}),
    .ProjectSettings = StringName({nil}),
    .PropertyTweener = StringName({nil}),
    .QuadMesh = StringName({nil}),
    .QuadOccluder3D = StringName({nil}),
    .RDAttachmentFormat = StringName({nil}),
    .RDFramebufferPass = StringName({nil}),
    .RDPipelineColorBlendState = StringName({nil}),
    .RDPipelineColorBlendStateAttachment = StringName({nil}),
    .RDPipelineDepthStencilState = StringName({nil}),
    .RDPipelineMultisampleState = StringName({nil}),
    .RDPipelineRasterizationState = StringName({nil}),
    .RDPipelineSpecializationConstant = StringName({nil}),
    .RDSamplerState = StringName({nil}),
    .RDShaderFile = StringName({nil}),
    .RDShaderSPIRV = StringName({nil}),
    .RDShaderSource = StringName({nil}),
    .RDTextureFormat = StringName({nil}),
    .RDTextureView = StringName({nil}),
    .RDUniform = StringName({nil}),
    .RDVertexAttribute = StringName({nil}),
    .RandomNumberGenerator = StringName({nil}),
    .Range = StringName({nil}),
    .RayCast2D = StringName({nil}),
    .RayCast3D = StringName({nil}),
    .RectangleShape2D = StringName({nil}),
    .RefCounted = StringName({nil}),
    .ReferenceRect = StringName({nil}),
    .ReflectionProbe = StringName({nil}),
    .RegEx = StringName({nil}),
    .RegExMatch = StringName({nil}),
    .RemoteTransform2D = StringName({nil}),
    .RemoteTransform3D = StringName({nil}),
    .RenderData = StringName({nil}),
    .RenderDataExtension = StringName({nil}),
    .RenderDataRD = StringName({nil}),
    .RenderSceneBuffers = StringName({nil}),
    .RenderSceneBuffersConfiguration = StringName({nil}),
    .RenderSceneBuffersExtension = StringName({nil}),
    .RenderSceneBuffersRD = StringName({nil}),
    .RenderSceneData = StringName({nil}),
    .RenderSceneDataExtension = StringName({nil}),
    .RenderSceneDataRD = StringName({nil}),
    .RenderingDevice = StringName({nil}),
    .RenderingServer = StringName({nil}),
    .Resource = StringName({nil}),
    .ResourceFormatLoader = StringName({nil}),
    .ResourceFormatSaver = StringName({nil}),
    .ResourceImporter = StringName({nil}),
    .ResourceImporterBMFont = StringName({nil}),
    .ResourceImporterBitMap = StringName({nil}),
    .ResourceImporterCSVTranslation = StringName({nil}),
    .ResourceImporterDynamicFont = StringName({nil}),
    .ResourceImporterImage = StringName({nil}),
    .ResourceImporterImageFont = StringName({nil}),
    .ResourceImporterLayeredTexture = StringName({nil}),
    .ResourceImporterMP3 = StringName({nil}),
    .ResourceImporterOBJ = StringName({nil}),
    .ResourceImporterOggVorbis = StringName({nil}),
    .ResourceImporterScene = StringName({nil}),
    .ResourceImporterShaderFile = StringName({nil}),
    .ResourceImporterTexture = StringName({nil}),
    .ResourceImporterTextureAtlas = StringName({nil}),
    .ResourceImporterWAV = StringName({nil}),
    .ResourceLoader = StringName({nil}),
    .ResourcePreloader = StringName({nil}),
    .ResourceSaver = StringName({nil}),
    .ResourceUID = StringName({nil}),
    .RetargetModifier3D = StringName({nil}),
    .RibbonTrailMesh = StringName({nil}),
    .RichTextEffect = StringName({nil}),
    .RichTextLabel = StringName({nil}),
    .RigidBody2D = StringName({nil}),
    .RigidBody3D = StringName({nil}),
    .RootMotionView = StringName({nil}),
    .SceneMultiplayer = StringName({nil}),
    .SceneReplicationConfig = StringName({nil}),
    .SceneState = StringName({nil}),
    .SceneTree = StringName({nil}),
    .SceneTreeTimer = StringName({nil}),
    .Script = StringName({nil}),
    .ScriptCreateDialog = StringName({nil}),
    .ScriptEditor = StringName({nil}),
    .ScriptEditorBase = StringName({nil}),
    .ScriptExtension = StringName({nil}),
    .ScriptLanguage = StringName({nil}),
    .ScriptLanguageExtension = StringName({nil}),
    .ScrollBar = StringName({nil}),
    .ScrollContainer = StringName({nil}),
    .SegmentShape2D = StringName({nil}),
    .Semaphore = StringName({nil}),
    .SeparationRayShape2D = StringName({nil}),
    .SeparationRayShape3D = StringName({nil}),
    .Separator = StringName({nil}),
    .Shader = StringName({nil}),
    .ShaderGlobalsOverride = StringName({nil}),
    .ShaderInclude = StringName({nil}),
    .ShaderIncludeDB = StringName({nil}),
    .ShaderMaterial = StringName({nil}),
    .Shape2D = StringName({nil}),
    .Shape3D = StringName({nil}),
    .ShapeCast2D = StringName({nil}),
    .ShapeCast3D = StringName({nil}),
    .Shortcut = StringName({nil}),
    .Skeleton2D = StringName({nil}),
    .Skeleton3D = StringName({nil}),
    .SkeletonIK3D = StringName({nil}),
    .SkeletonModification2D = StringName({nil}),
    .SkeletonModification2DCCDIK = StringName({nil}),
    .SkeletonModification2DFABRIK = StringName({nil}),
    .SkeletonModification2DJiggle = StringName({nil}),
    .SkeletonModification2DLookAt = StringName({nil}),
    .SkeletonModification2DPhysicalBones = StringName({nil}),
    .SkeletonModification2DStackHolder = StringName({nil}),
    .SkeletonModification2DTwoBoneIK = StringName({nil}),
    .SkeletonModificationStack2D = StringName({nil}),
    .SkeletonModifier3D = StringName({nil}),
    .SkeletonProfile = StringName({nil}),
    .SkeletonProfileHumanoid = StringName({nil}),
    .Skin = StringName({nil}),
    .SkinReference = StringName({nil}),
    .Sky = StringName({nil}),
    .Slider = StringName({nil}),
    .SliderJoint3D = StringName({nil}),
    .SoftBody3D = StringName({nil}),
    .SphereMesh = StringName({nil}),
    .SphereOccluder3D = StringName({nil}),
    .SphereShape3D = StringName({nil}),
    .SpinBox = StringName({nil}),
    .SplitContainer = StringName({nil}),
    .SpotLight3D = StringName({nil}),
    .SpringArm3D = StringName({nil}),
    .SpringBoneCollision3D = StringName({nil}),
    .SpringBoneCollisionCapsule3D = StringName({nil}),
    .SpringBoneCollisionPlane3D = StringName({nil}),
    .SpringBoneCollisionSphere3D = StringName({nil}),
    .SpringBoneSimulator3D = StringName({nil}),
    .Sprite2D = StringName({nil}),
    .Sprite3D = StringName({nil}),
    .SpriteBase3D = StringName({nil}),
    .SpriteFrames = StringName({nil}),
    .StandardMaterial3D = StringName({nil}),
    .StaticBody2D = StringName({nil}),
    .StaticBody3D = StringName({nil}),
    .StatusIndicator = StringName({nil}),
    .StreamPeer = StringName({nil}),
    .StreamPeerBuffer = StringName({nil}),
    .StreamPeerExtension = StringName({nil}),
    .StreamPeerGZIP = StringName({nil}),
    .StreamPeerTCP = StringName({nil}),
    .StreamPeerTLS = StringName({nil}),
    .StyleBox = StringName({nil}),
    .StyleBoxEmpty = StringName({nil}),
    .StyleBoxFlat = StringName({nil}),
    .StyleBoxLine = StringName({nil}),
    .StyleBoxTexture = StringName({nil}),
    .SubViewport = StringName({nil}),
    .SubViewportContainer = StringName({nil}),
    .SubtweenTweener = StringName({nil}),
    .SurfaceTool = StringName({nil}),
    .SyntaxHighlighter = StringName({nil}),
    .SystemFont = StringName({nil}),
    .TCPServer = StringName({nil}),
    .TLSOptions = StringName({nil}),
    .TabBar = StringName({nil}),
    .TabContainer = StringName({nil}),
    .TextEdit = StringName({nil}),
    .TextLine = StringName({nil}),
    .TextMesh = StringName({nil}),
    .TextParagraph = StringName({nil}),
    .TextServer = StringName({nil}),
    .TextServerAdvanced = StringName({nil}),
    .TextServerDummy = StringName({nil}),
    .TextServerExtension = StringName({nil}),
    .TextServerManager = StringName({nil}),
    .Texture = StringName({nil}),
    .Texture2D = StringName({nil}),
    .Texture2DArray = StringName({nil}),
    .Texture2DArrayRD = StringName({nil}),
    .Texture2DRD = StringName({nil}),
    .Texture3D = StringName({nil}),
    .Texture3DRD = StringName({nil}),
    .TextureButton = StringName({nil}),
    .TextureCubemapArrayRD = StringName({nil}),
    .TextureCubemapRD = StringName({nil}),
    .TextureLayered = StringName({nil}),
    .TextureLayeredRD = StringName({nil}),
    .TextureProgressBar = StringName({nil}),
    .TextureRect = StringName({nil}),
    .Theme = StringName({nil}),
    .ThemeDB = StringName({nil}),
    .Thread = StringName({nil}),
    .TileData = StringName({nil}),
    .TileMap = StringName({nil}),
    .TileMapLayer = StringName({nil}),
    .TileMapPattern = StringName({nil}),
    .TileSet = StringName({nil}),
    .TileSetAtlasSource = StringName({nil}),
    .TileSetScenesCollectionSource = StringName({nil}),
    .TileSetSource = StringName({nil}),
    .Time = StringName({nil}),
    .Timer = StringName({nil}),
    .TorusMesh = StringName({nil}),
    .TouchScreenButton = StringName({nil}),
    .Translation = StringName({nil}),
    .TranslationDomain = StringName({nil}),
    .TranslationServer = StringName({nil}),
    .Tree = StringName({nil}),
    .TreeItem = StringName({nil}),
    .TriangleMesh = StringName({nil}),
    .TubeTrailMesh = StringName({nil}),
    .Tween = StringName({nil}),
    .Tweener = StringName({nil}),
    .UDPServer = StringName({nil}),
    .UPNP = StringName({nil}),
    .UPNPDevice = StringName({nil}),
    .UndoRedo = StringName({nil}),
    .UniformSetCacheRD = StringName({nil}),
    .VBoxContainer = StringName({nil}),
    .VFlowContainer = StringName({nil}),
    .VScrollBar = StringName({nil}),
    .VSeparator = StringName({nil}),
    .VSlider = StringName({nil}),
    .VSplitContainer = StringName({nil}),
    .VehicleBody3D = StringName({nil}),
    .VehicleWheel3D = StringName({nil}),
    .VideoStream = StringName({nil}),
    .VideoStreamPlayback = StringName({nil}),
    .VideoStreamPlayer = StringName({nil}),
    .VideoStreamTheora = StringName({nil}),
    .Viewport = StringName({nil}),
    .ViewportTexture = StringName({nil}),
    .VisibleOnScreenEnabler2D = StringName({nil}),
    .VisibleOnScreenEnabler3D = StringName({nil}),
    .VisibleOnScreenNotifier2D = StringName({nil}),
    .VisibleOnScreenNotifier3D = StringName({nil}),
    .VisualInstance3D = StringName({nil}),
    .VisualShader = StringName({nil}),
    .VisualShaderNode = StringName({nil}),
    .VisualShaderNodeBillboard = StringName({nil}),
    .VisualShaderNodeBooleanConstant = StringName({nil}),
    .VisualShaderNodeBooleanParameter = StringName({nil}),
    .VisualShaderNodeClamp = StringName({nil}),
    .VisualShaderNodeColorConstant = StringName({nil}),
    .VisualShaderNodeColorFunc = StringName({nil}),
    .VisualShaderNodeColorOp = StringName({nil}),
    .VisualShaderNodeColorParameter = StringName({nil}),
    .VisualShaderNodeComment = StringName({nil}),
    .VisualShaderNodeCompare = StringName({nil}),
    .VisualShaderNodeConstant = StringName({nil}),
    .VisualShaderNodeCubemap = StringName({nil}),
    .VisualShaderNodeCubemapParameter = StringName({nil}),
    .VisualShaderNodeCurveTexture = StringName({nil}),
    .VisualShaderNodeCurveXYZTexture = StringName({nil}),
    .VisualShaderNodeCustom = StringName({nil}),
    .VisualShaderNodeDerivativeFunc = StringName({nil}),
    .VisualShaderNodeDeterminant = StringName({nil}),
    .VisualShaderNodeDistanceFade = StringName({nil}),
    .VisualShaderNodeDotProduct = StringName({nil}),
    .VisualShaderNodeExpression = StringName({nil}),
    .VisualShaderNodeFaceForward = StringName({nil}),
    .VisualShaderNodeFloatConstant = StringName({nil}),
    .VisualShaderNodeFloatFunc = StringName({nil}),
    .VisualShaderNodeFloatOp = StringName({nil}),
    .VisualShaderNodeFloatParameter = StringName({nil}),
    .VisualShaderNodeFrame = StringName({nil}),
    .VisualShaderNodeFresnel = StringName({nil}),
    .VisualShaderNodeGlobalExpression = StringName({nil}),
    .VisualShaderNodeGroupBase = StringName({nil}),
    .VisualShaderNodeIf = StringName({nil}),
    .VisualShaderNodeInput = StringName({nil}),
    .VisualShaderNodeIntConstant = StringName({nil}),
    .VisualShaderNodeIntFunc = StringName({nil}),
    .VisualShaderNodeIntOp = StringName({nil}),
    .VisualShaderNodeIntParameter = StringName({nil}),
    .VisualShaderNodeIs = StringName({nil}),
    .VisualShaderNodeLinearSceneDepth = StringName({nil}),
    .VisualShaderNodeMix = StringName({nil}),
    .VisualShaderNodeMultiplyAdd = StringName({nil}),
    .VisualShaderNodeOuterProduct = StringName({nil}),
    .VisualShaderNodeOutput = StringName({nil}),
    .VisualShaderNodeParameter = StringName({nil}),
    .VisualShaderNodeParameterRef = StringName({nil}),
    .VisualShaderNodeParticleAccelerator = StringName({nil}),
    .VisualShaderNodeParticleBoxEmitter = StringName({nil}),
    .VisualShaderNodeParticleConeVelocity = StringName({nil}),
    .VisualShaderNodeParticleEmit = StringName({nil}),
    .VisualShaderNodeParticleEmitter = StringName({nil}),
    .VisualShaderNodeParticleMeshEmitter = StringName({nil}),
    .VisualShaderNodeParticleMultiplyByAxisAngle = StringName({nil}),
    .VisualShaderNodeParticleOutput = StringName({nil}),
    .VisualShaderNodeParticleRandomness = StringName({nil}),
    .VisualShaderNodeParticleRingEmitter = StringName({nil}),
    .VisualShaderNodeParticleSphereEmitter = StringName({nil}),
    .VisualShaderNodeProximityFade = StringName({nil}),
    .VisualShaderNodeRandomRange = StringName({nil}),
    .VisualShaderNodeRemap = StringName({nil}),
    .VisualShaderNodeReroute = StringName({nil}),
    .VisualShaderNodeResizableBase = StringName({nil}),
    .VisualShaderNodeRotationByAxis = StringName({nil}),
    .VisualShaderNodeSDFRaymarch = StringName({nil}),
    .VisualShaderNodeSDFToScreenUV = StringName({nil}),
    .VisualShaderNodeSample3D = StringName({nil}),
    .VisualShaderNodeScreenNormalWorldSpace = StringName({nil}),
    .VisualShaderNodeScreenUVToSDF = StringName({nil}),
    .VisualShaderNodeSmoothStep = StringName({nil}),
    .VisualShaderNodeStep = StringName({nil}),
    .VisualShaderNodeSwitch = StringName({nil}),
    .VisualShaderNodeTexture = StringName({nil}),
    .VisualShaderNodeTexture2DArray = StringName({nil}),
    .VisualShaderNodeTexture2DArrayParameter = StringName({nil}),
    .VisualShaderNodeTexture2DParameter = StringName({nil}),
    .VisualShaderNodeTexture3D = StringName({nil}),
    .VisualShaderNodeTexture3DParameter = StringName({nil}),
    .VisualShaderNodeTextureParameter = StringName({nil}),
    .VisualShaderNodeTextureParameterTriplanar = StringName({nil}),
    .VisualShaderNodeTextureSDF = StringName({nil}),
    .VisualShaderNodeTextureSDFNormal = StringName({nil}),
    .VisualShaderNodeTransformCompose = StringName({nil}),
    .VisualShaderNodeTransformConstant = StringName({nil}),
    .VisualShaderNodeTransformDecompose = StringName({nil}),
    .VisualShaderNodeTransformFunc = StringName({nil}),
    .VisualShaderNodeTransformOp = StringName({nil}),
    .VisualShaderNodeTransformParameter = StringName({nil}),
    .VisualShaderNodeTransformVecMult = StringName({nil}),
    .VisualShaderNodeUIntConstant = StringName({nil}),
    .VisualShaderNodeUIntFunc = StringName({nil}),
    .VisualShaderNodeUIntOp = StringName({nil}),
    .VisualShaderNodeUIntParameter = StringName({nil}),
    .VisualShaderNodeUVFunc = StringName({nil}),
    .VisualShaderNodeUVPolarCoord = StringName({nil}),
    .VisualShaderNodeVarying = StringName({nil}),
    .VisualShaderNodeVaryingGetter = StringName({nil}),
    .VisualShaderNodeVaryingSetter = StringName({nil}),
    .VisualShaderNodeVec2Constant = StringName({nil}),
    .VisualShaderNodeVec2Parameter = StringName({nil}),
    .VisualShaderNodeVec3Constant = StringName({nil}),
    .VisualShaderNodeVec3Parameter = StringName({nil}),
    .VisualShaderNodeVec4Constant = StringName({nil}),
    .VisualShaderNodeVec4Parameter = StringName({nil}),
    .VisualShaderNodeVectorBase = StringName({nil}),
    .VisualShaderNodeVectorCompose = StringName({nil}),
    .VisualShaderNodeVectorDecompose = StringName({nil}),
    .VisualShaderNodeVectorDistance = StringName({nil}),
    .VisualShaderNodeVectorFunc = StringName({nil}),
    .VisualShaderNodeVectorLen = StringName({nil}),
    .VisualShaderNodeVectorOp = StringName({nil}),
    .VisualShaderNodeVectorRefract = StringName({nil}),
    .VisualShaderNodeWorldPositionFromDepth = StringName({nil}),
    .VoxelGI = StringName({nil}),
    .VoxelGIData = StringName({nil}),
    .WeakRef = StringName({nil}),
    .WebRTCDataChannel = StringName({nil}),
    .WebRTCDataChannelExtension = StringName({nil}),
    .WebRTCMultiplayerPeer = StringName({nil}),
    .WebRTCPeerConnection = StringName({nil}),
    .WebRTCPeerConnectionExtension = StringName({nil}),
    .WebSocketMultiplayerPeer = StringName({nil}),
    .WebSocketPeer = StringName({nil}),
    .WebXRInterface = StringName({nil}),
    .Window = StringName({nil}),
    .WorkerThreadPool = StringName({nil}),
    .World2D = StringName({nil}),
    .World3D = StringName({nil}),
    .WorldBoundaryShape2D = StringName({nil}),
    .WorldBoundaryShape3D = StringName({nil}),
    .WorldEnvironment = StringName({nil}),
    .X509Certificate = StringName({nil}),
    .XMLParser = StringName({nil}),
    .XRAnchor3D = StringName({nil}),
    .XRBodyModifier3D = StringName({nil}),
    .XRBodyTracker = StringName({nil}),
    .XRCamera3D = StringName({nil}),
    .XRController3D = StringName({nil}),
    .XRControllerTracker = StringName({nil}),
    .XRFaceModifier3D = StringName({nil}),
    .XRFaceTracker = StringName({nil}),
    .XRHandModifier3D = StringName({nil}),
    .XRHandTracker = StringName({nil}),
    .XRInterface = StringName({nil}),
    .XRInterfaceExtension = StringName({nil}),
    .XRNode3D = StringName({nil}),
    .XROrigin3D = StringName({nil}),
    .XRPose = StringName({nil}),
    .XRPositionalTracker = StringName({nil}),
    .XRServer = StringName({nil}),
    .XRTracker = StringName({nil}),
    .XRVRS = StringName({nil}),
    .ZIPPacker = StringName({nil}),
    .ZIPReader = StringName({nil}),
    .Master = StringName({nil}),
}
