package GDWrapper

import "shared:GDWrapper/gdAPI"
import GDE "shared:GDWrapper/gdAPI/gdextension"
import "core:math"


Nil_Methods_list :: struct {
    Create0: proc "c" (p_base: ^rawptr = nil, p_args: rawptr = nil),
    Create1: proc "c" (p_base: ^rawptr = nil,  #by_ptr p_args: struct{ from: ^Variant, }),
    VARIANT_OP_NOT_: proc "c" (p_left: rawptr = nil, p_right: rawptr = nil,  r_result: ^Bool),
    VARIANT_OP_EQUAL_Bool: proc "c" (p_left: rawptr = nil, p_right: ^Bool, r_result: ^Bool),
    VARIANT_OP_NOT_EQUAL_Bool: proc "c" (p_left: rawptr = nil, p_right: ^Bool, r_result: ^Bool),
    VARIANT_OP_AND_Bool: proc "c" (p_left: rawptr = nil, p_right: ^Bool, r_result: ^Bool),
    VARIANT_OP_OR_Bool: proc "c" (p_left: rawptr = nil, p_right: ^Bool, r_result: ^Bool),
    VARIANT_OP_XOR_Bool: proc "c" (p_left: rawptr = nil, p_right: ^Bool, r_result: ^Bool),
    VARIANT_OP_EQUAL_Int: proc "c" (p_left: rawptr = nil, p_right: ^Int, r_result: ^Bool),
    VARIANT_OP_NOT_EQUAL_Int: proc "c" (p_left: rawptr = nil, p_right: ^Int, r_result: ^Bool),
    VARIANT_OP_AND_Int: proc "c" (p_left: rawptr = nil, p_right: ^Int, r_result: ^Bool),
    VARIANT_OP_OR_Int: proc "c" (p_left: rawptr = nil, p_right: ^Int, r_result: ^Bool),
    VARIANT_OP_XOR_Int: proc "c" (p_left: rawptr = nil, p_right: ^Int, r_result: ^Bool),
    VARIANT_OP_EQUAL_float: proc "c" (p_left: rawptr = nil, p_right: ^float, r_result: ^Bool),
    VARIANT_OP_NOT_EQUAL_float: proc "c" (p_left: rawptr = nil, p_right: ^float, r_result: ^Bool),
    VARIANT_OP_AND_float: proc "c" (p_left: rawptr = nil, p_right: ^float, r_result: ^Bool),
    VARIANT_OP_OR_float: proc "c" (p_left: rawptr = nil, p_right: ^float, r_result: ^Bool),
    VARIANT_OP_XOR_float: proc "c" (p_left: rawptr = nil, p_right: ^float, r_result: ^Bool),
    VARIANT_OP_EQUAL_gdstring: proc "c" (p_left: rawptr = nil, p_right: ^gdstring, r_result: ^Bool),
    VARIANT_OP_NOT_EQUAL_gdstring: proc "c" (p_left: rawptr = nil, p_right: ^gdstring, r_result: ^Bool),
    VARIANT_OP_EQUAL_Vector2: proc "c" (p_left: rawptr = nil, p_right: ^Vector2, r_result: ^Bool),
    VARIANT_OP_NOT_EQUAL_Vector2: proc "c" (p_left: rawptr = nil, p_right: ^Vector2, r_result: ^Bool),
    VARIANT_OP_EQUAL_Vector2i: proc "c" (p_left: rawptr = nil, p_right: ^Vector2i, r_result: ^Bool),
    VARIANT_OP_NOT_EQUAL_Vector2i: proc "c" (p_left: rawptr = nil, p_right: ^Vector2i, r_result: ^Bool),
    VARIANT_OP_EQUAL_Rect2: proc "c" (p_left: rawptr = nil, p_right: ^Rect2, r_result: ^Bool),
    VARIANT_OP_NOT_EQUAL_Rect2: proc "c" (p_left: rawptr = nil, p_right: ^Rect2, r_result: ^Bool),
    VARIANT_OP_EQUAL_Rect2i: proc "c" (p_left: rawptr = nil, p_right: ^Rect2i, r_result: ^Bool),
    VARIANT_OP_NOT_EQUAL_Rect2i: proc "c" (p_left: rawptr = nil, p_right: ^Rect2i, r_result: ^Bool),
    VARIANT_OP_EQUAL_Vector3: proc "c" (p_left: rawptr = nil, p_right: ^Vector3, r_result: ^Bool),
    VARIANT_OP_NOT_EQUAL_Vector3: proc "c" (p_left: rawptr = nil, p_right: ^Vector3, r_result: ^Bool),
    VARIANT_OP_EQUAL_Vector3i: proc "c" (p_left: rawptr = nil, p_right: ^Vector3i, r_result: ^Bool),
    VARIANT_OP_NOT_EQUAL_Vector3i: proc "c" (p_left: rawptr = nil, p_right: ^Vector3i, r_result: ^Bool),
    VARIANT_OP_EQUAL_Transform2D: proc "c" (p_left: rawptr = nil, p_right: ^Transform2D, r_result: ^Bool),
    VARIANT_OP_NOT_EQUAL_Transform2D: proc "c" (p_left: rawptr = nil, p_right: ^Transform2D, r_result: ^Bool),
    VARIANT_OP_EQUAL_Vector4: proc "c" (p_left: rawptr = nil, p_right: ^Vector4, r_result: ^Bool),
    VARIANT_OP_NOT_EQUAL_Vector4: proc "c" (p_left: rawptr = nil, p_right: ^Vector4, r_result: ^Bool),
    VARIANT_OP_EQUAL_Vector4i: proc "c" (p_left: rawptr = nil, p_right: ^Vector4i, r_result: ^Bool),
    VARIANT_OP_NOT_EQUAL_Vector4i: proc "c" (p_left: rawptr = nil, p_right: ^Vector4i, r_result: ^Bool),
    VARIANT_OP_EQUAL_Plane: proc "c" (p_left: rawptr = nil, p_right: ^Plane, r_result: ^Bool),
    VARIANT_OP_NOT_EQUAL_Plane: proc "c" (p_left: rawptr = nil, p_right: ^Plane, r_result: ^Bool),
    VARIANT_OP_EQUAL_Quaternion: proc "c" (p_left: rawptr = nil, p_right: ^Quaternion, r_result: ^Bool),
    VARIANT_OP_NOT_EQUAL_Quaternion: proc "c" (p_left: rawptr = nil, p_right: ^Quaternion, r_result: ^Bool),
    VARIANT_OP_EQUAL_AABB: proc "c" (p_left: rawptr = nil, p_right: ^AABB, r_result: ^Bool),
    VARIANT_OP_NOT_EQUAL_AABB: proc "c" (p_left: rawptr = nil, p_right: ^AABB, r_result: ^Bool),
    VARIANT_OP_EQUAL_Basis: proc "c" (p_left: rawptr = nil, p_right: ^Basis, r_result: ^Bool),
    VARIANT_OP_NOT_EQUAL_Basis: proc "c" (p_left: rawptr = nil, p_right: ^Basis, r_result: ^Bool),
    VARIANT_OP_EQUAL_Transform3D: proc "c" (p_left: rawptr = nil, p_right: ^Transform3D, r_result: ^Bool),
    VARIANT_OP_NOT_EQUAL_Transform3D: proc "c" (p_left: rawptr = nil, p_right: ^Transform3D, r_result: ^Bool),
    VARIANT_OP_EQUAL_Projection: proc "c" (p_left: rawptr = nil, p_right: ^Projection, r_result: ^Bool),
    VARIANT_OP_NOT_EQUAL_Projection: proc "c" (p_left: rawptr = nil, p_right: ^Projection, r_result: ^Bool),
    VARIANT_OP_EQUAL_Color: proc "c" (p_left: rawptr = nil, p_right: ^Color, r_result: ^Bool),
    VARIANT_OP_NOT_EQUAL_Color: proc "c" (p_left: rawptr = nil, p_right: ^Color, r_result: ^Bool),
    VARIANT_OP_EQUAL_StringName: proc "c" (p_left: rawptr = nil, p_right: ^StringName, r_result: ^Bool),
    VARIANT_OP_NOT_EQUAL_StringName: proc "c" (p_left: rawptr = nil, p_right: ^StringName, r_result: ^Bool),
    VARIANT_OP_EQUAL_NodePath: proc "c" (p_left: rawptr = nil, p_right: ^NodePath, r_result: ^Bool),
    VARIANT_OP_NOT_EQUAL_NodePath: proc "c" (p_left: rawptr = nil, p_right: ^NodePath, r_result: ^Bool),
    VARIANT_OP_EQUAL_RID: proc "c" (p_left: rawptr = nil, p_right: ^RID, r_result: ^Bool),
    VARIANT_OP_NOT_EQUAL_RID: proc "c" (p_left: rawptr = nil, p_right: ^RID, r_result: ^Bool),
    VARIANT_OP_EQUAL_Object: proc "c" (p_left: rawptr = nil, p_right: ^Object, r_result: ^Bool),
    VARIANT_OP_NOT_EQUAL_Object: proc "c" (p_left: rawptr = nil, p_right: ^Object, r_result: ^Bool),
    VARIANT_OP_AND_Object: proc "c" (p_left: rawptr = nil, p_right: ^Object, r_result: ^Bool),
    VARIANT_OP_OR_Object: proc "c" (p_left: rawptr = nil, p_right: ^Object, r_result: ^Bool),
    VARIANT_OP_XOR_Object: proc "c" (p_left: rawptr = nil, p_right: ^Object, r_result: ^Bool),
    VARIANT_OP_EQUAL_Callable: proc "c" (p_left: rawptr = nil, p_right: ^Callable, r_result: ^Bool),
    VARIANT_OP_NOT_EQUAL_Callable: proc "c" (p_left: rawptr = nil, p_right: ^Callable, r_result: ^Bool),
    VARIANT_OP_EQUAL_Signal: proc "c" (p_left: rawptr = nil, p_right: ^Signal, r_result: ^Bool),
    VARIANT_OP_NOT_EQUAL_Signal: proc "c" (p_left: rawptr = nil, p_right: ^Signal, r_result: ^Bool),
    VARIANT_OP_EQUAL_Dictionary: proc "c" (p_left: rawptr = nil, p_right: ^Dictionary, r_result: ^Bool),
    VARIANT_OP_NOT_EQUAL_Dictionary: proc "c" (p_left: rawptr = nil, p_right: ^Dictionary, r_result: ^Bool),
    VARIANT_OP_IN_Dictionary: proc "c" (p_left: rawptr = nil, p_right: ^Dictionary, r_result: ^Bool),
    VARIANT_OP_EQUAL_Array: proc "c" (p_left: rawptr = nil, p_right: ^Array, r_result: ^Bool),
    VARIANT_OP_NOT_EQUAL_Array: proc "c" (p_left: rawptr = nil, p_right: ^Array, r_result: ^Bool),
    VARIANT_OP_IN_Array: proc "c" (p_left: rawptr = nil, p_right: ^Array, r_result: ^Bool),
    VARIANT_OP_EQUAL_PackedByteArray: proc "c" (p_left: rawptr = nil, p_right: ^PackedByteArray, r_result: ^Bool),
    VARIANT_OP_NOT_EQUAL_PackedByteArray: proc "c" (p_left: rawptr = nil, p_right: ^PackedByteArray, r_result: ^Bool),
    VARIANT_OP_EQUAL_PackedInt32Array: proc "c" (p_left: rawptr = nil, p_right: ^PackedInt32Array, r_result: ^Bool),
    VARIANT_OP_NOT_EQUAL_PackedInt32Array: proc "c" (p_left: rawptr = nil, p_right: ^PackedInt32Array, r_result: ^Bool),
    VARIANT_OP_EQUAL_PackedInt64Array: proc "c" (p_left: rawptr = nil, p_right: ^PackedInt64Array, r_result: ^Bool),
    VARIANT_OP_NOT_EQUAL_PackedInt64Array: proc "c" (p_left: rawptr = nil, p_right: ^PackedInt64Array, r_result: ^Bool),
    VARIANT_OP_EQUAL_PackedFloat32Array: proc "c" (p_left: rawptr = nil, p_right: ^PackedFloat32Array, r_result: ^Bool),
    VARIANT_OP_NOT_EQUAL_PackedFloat32Array: proc "c" (p_left: rawptr = nil, p_right: ^PackedFloat32Array, r_result: ^Bool),
    VARIANT_OP_EQUAL_PackedFloat64Array: proc "c" (p_left: rawptr = nil, p_right: ^PackedFloat64Array, r_result: ^Bool),
    VARIANT_OP_NOT_EQUAL_PackedFloat64Array: proc "c" (p_left: rawptr = nil, p_right: ^PackedFloat64Array, r_result: ^Bool),
    VARIANT_OP_EQUAL_PackedStringArray: proc "c" (p_left: rawptr = nil, p_right: ^PackedStringArray, r_result: ^Bool),
    VARIANT_OP_NOT_EQUAL_PackedStringArray: proc "c" (p_left: rawptr = nil, p_right: ^PackedStringArray, r_result: ^Bool),
    VARIANT_OP_EQUAL_PackedVector2Array: proc "c" (p_left: rawptr = nil, p_right: ^PackedVector2Array, r_result: ^Bool),
    VARIANT_OP_NOT_EQUAL_PackedVector2Array: proc "c" (p_left: rawptr = nil, p_right: ^PackedVector2Array, r_result: ^Bool),
    VARIANT_OP_EQUAL_PackedVector3Array: proc "c" (p_left: rawptr = nil, p_right: ^PackedVector3Array, r_result: ^Bool),
    VARIANT_OP_NOT_EQUAL_PackedVector3Array: proc "c" (p_left: rawptr = nil, p_right: ^PackedVector3Array, r_result: ^Bool),
    VARIANT_OP_EQUAL_PackedColorArray: proc "c" (p_left: rawptr = nil, p_right: ^PackedColorArray, r_result: ^Bool),
    VARIANT_OP_NOT_EQUAL_PackedColorArray: proc "c" (p_left: rawptr = nil, p_right: ^PackedColorArray, r_result: ^Bool),
    VARIANT_OP_EQUAL_PackedVector4Array: proc "c" (p_left: rawptr = nil, p_right: ^PackedVector4Array, r_result: ^Bool),
    VARIANT_OP_NOT_EQUAL_PackedVector4Array: proc "c" (p_left: rawptr = nil, p_right: ^PackedVector4Array, r_result: ^Bool),
}
init_Nil_Methods :: proc(Nil_method_store: ^Nil_Methods_list) {
  Nil_method_store.Create0 = cast(type_of(Nil_method_store.Create0))gdAPI.Variant_Utils.GetPtrConstructor(.NIL, 0)
  Nil_method_store.Create1 = cast(type_of(Nil_method_store.Create1))gdAPI.Variant_Utils.GetPtrConstructor(.NIL, 1)
  Nil_method_store.VARIANT_OP_NOT_ = cast(type_of(Nil_method_store.VARIANT_OP_NOT_))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_NOT, .NIL, .NIL)
  Nil_method_store.VARIANT_OP_EQUAL_Bool = cast(type_of(Nil_method_store.VARIANT_OP_EQUAL_Bool))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_EQUAL, .NIL, .NIL)
  Nil_method_store.VARIANT_OP_NOT_EQUAL_Bool = cast(type_of(Nil_method_store.VARIANT_OP_NOT_EQUAL_Bool))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_NOT_EQUAL, .NIL, .NIL)
  Nil_method_store.VARIANT_OP_AND_Bool = cast(type_of(Nil_method_store.VARIANT_OP_AND_Bool))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_AND, .NIL, .NIL)
  Nil_method_store.VARIANT_OP_OR_Bool = cast(type_of(Nil_method_store.VARIANT_OP_OR_Bool))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_OR, .NIL, .NIL)
  Nil_method_store.VARIANT_OP_XOR_Bool = cast(type_of(Nil_method_store.VARIANT_OP_XOR_Bool))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_XOR, .NIL, .NIL)
  Nil_method_store.VARIANT_OP_EQUAL_Int = cast(type_of(Nil_method_store.VARIANT_OP_EQUAL_Int))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_EQUAL, .NIL, .NIL)
  Nil_method_store.VARIANT_OP_NOT_EQUAL_Int = cast(type_of(Nil_method_store.VARIANT_OP_NOT_EQUAL_Int))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_NOT_EQUAL, .NIL, .NIL)
  Nil_method_store.VARIANT_OP_AND_Int = cast(type_of(Nil_method_store.VARIANT_OP_AND_Int))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_AND, .NIL, .NIL)
  Nil_method_store.VARIANT_OP_OR_Int = cast(type_of(Nil_method_store.VARIANT_OP_OR_Int))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_OR, .NIL, .NIL)
  Nil_method_store.VARIANT_OP_XOR_Int = cast(type_of(Nil_method_store.VARIANT_OP_XOR_Int))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_XOR, .NIL, .NIL)
  Nil_method_store.VARIANT_OP_EQUAL_float = cast(type_of(Nil_method_store.VARIANT_OP_EQUAL_float))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_EQUAL, .NIL, .FLOAT)
  Nil_method_store.VARIANT_OP_NOT_EQUAL_float = cast(type_of(Nil_method_store.VARIANT_OP_NOT_EQUAL_float))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_NOT_EQUAL, .NIL, .FLOAT)
  Nil_method_store.VARIANT_OP_AND_float = cast(type_of(Nil_method_store.VARIANT_OP_AND_float))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_AND, .NIL, .FLOAT)
  Nil_method_store.VARIANT_OP_OR_float = cast(type_of(Nil_method_store.VARIANT_OP_OR_float))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_OR, .NIL, .FLOAT)
  Nil_method_store.VARIANT_OP_XOR_float = cast(type_of(Nil_method_store.VARIANT_OP_XOR_float))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_XOR, .NIL, .FLOAT)
  Nil_method_store.VARIANT_OP_EQUAL_gdstring = cast(type_of(Nil_method_store.VARIANT_OP_EQUAL_gdstring))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_EQUAL, .NIL, .NIL)
  Nil_method_store.VARIANT_OP_NOT_EQUAL_gdstring = cast(type_of(Nil_method_store.VARIANT_OP_NOT_EQUAL_gdstring))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_NOT_EQUAL, .NIL, .NIL)
  Nil_method_store.VARIANT_OP_EQUAL_Vector2 = cast(type_of(Nil_method_store.VARIANT_OP_EQUAL_Vector2))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_EQUAL, .NIL, .VECTOR2)
  Nil_method_store.VARIANT_OP_NOT_EQUAL_Vector2 = cast(type_of(Nil_method_store.VARIANT_OP_NOT_EQUAL_Vector2))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_NOT_EQUAL, .NIL, .VECTOR2)
  Nil_method_store.VARIANT_OP_EQUAL_Vector2i = cast(type_of(Nil_method_store.VARIANT_OP_EQUAL_Vector2i))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_EQUAL, .NIL, .VECTOR2I)
  Nil_method_store.VARIANT_OP_NOT_EQUAL_Vector2i = cast(type_of(Nil_method_store.VARIANT_OP_NOT_EQUAL_Vector2i))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_NOT_EQUAL, .NIL, .VECTOR2I)
  Nil_method_store.VARIANT_OP_EQUAL_Rect2 = cast(type_of(Nil_method_store.VARIANT_OP_EQUAL_Rect2))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_EQUAL, .NIL, .RECT2)
  Nil_method_store.VARIANT_OP_NOT_EQUAL_Rect2 = cast(type_of(Nil_method_store.VARIANT_OP_NOT_EQUAL_Rect2))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_NOT_EQUAL, .NIL, .RECT2)
  Nil_method_store.VARIANT_OP_EQUAL_Rect2i = cast(type_of(Nil_method_store.VARIANT_OP_EQUAL_Rect2i))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_EQUAL, .NIL, .RECT2I)
  Nil_method_store.VARIANT_OP_NOT_EQUAL_Rect2i = cast(type_of(Nil_method_store.VARIANT_OP_NOT_EQUAL_Rect2i))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_NOT_EQUAL, .NIL, .RECT2I)
  Nil_method_store.VARIANT_OP_EQUAL_Vector3 = cast(type_of(Nil_method_store.VARIANT_OP_EQUAL_Vector3))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_EQUAL, .NIL, .VECTOR3)
  Nil_method_store.VARIANT_OP_NOT_EQUAL_Vector3 = cast(type_of(Nil_method_store.VARIANT_OP_NOT_EQUAL_Vector3))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_NOT_EQUAL, .NIL, .VECTOR3)
  Nil_method_store.VARIANT_OP_EQUAL_Vector3i = cast(type_of(Nil_method_store.VARIANT_OP_EQUAL_Vector3i))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_EQUAL, .NIL, .VECTOR3I)
  Nil_method_store.VARIANT_OP_NOT_EQUAL_Vector3i = cast(type_of(Nil_method_store.VARIANT_OP_NOT_EQUAL_Vector3i))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_NOT_EQUAL, .NIL, .VECTOR3I)
  Nil_method_store.VARIANT_OP_EQUAL_Transform2D = cast(type_of(Nil_method_store.VARIANT_OP_EQUAL_Transform2D))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_EQUAL, .NIL, .TRANSFORM2D)
  Nil_method_store.VARIANT_OP_NOT_EQUAL_Transform2D = cast(type_of(Nil_method_store.VARIANT_OP_NOT_EQUAL_Transform2D))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_NOT_EQUAL, .NIL, .TRANSFORM2D)
  Nil_method_store.VARIANT_OP_EQUAL_Vector4 = cast(type_of(Nil_method_store.VARIANT_OP_EQUAL_Vector4))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_EQUAL, .NIL, .VECTOR4)
  Nil_method_store.VARIANT_OP_NOT_EQUAL_Vector4 = cast(type_of(Nil_method_store.VARIANT_OP_NOT_EQUAL_Vector4))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_NOT_EQUAL, .NIL, .VECTOR4)
  Nil_method_store.VARIANT_OP_EQUAL_Vector4i = cast(type_of(Nil_method_store.VARIANT_OP_EQUAL_Vector4i))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_EQUAL, .NIL, .VECTOR4I)
  Nil_method_store.VARIANT_OP_NOT_EQUAL_Vector4i = cast(type_of(Nil_method_store.VARIANT_OP_NOT_EQUAL_Vector4i))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_NOT_EQUAL, .NIL, .VECTOR4I)
  Nil_method_store.VARIANT_OP_EQUAL_Plane = cast(type_of(Nil_method_store.VARIANT_OP_EQUAL_Plane))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_EQUAL, .NIL, .PLANE)
  Nil_method_store.VARIANT_OP_NOT_EQUAL_Plane = cast(type_of(Nil_method_store.VARIANT_OP_NOT_EQUAL_Plane))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_NOT_EQUAL, .NIL, .PLANE)
  Nil_method_store.VARIANT_OP_EQUAL_Quaternion = cast(type_of(Nil_method_store.VARIANT_OP_EQUAL_Quaternion))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_EQUAL, .NIL, .QUATERNION)
  Nil_method_store.VARIANT_OP_NOT_EQUAL_Quaternion = cast(type_of(Nil_method_store.VARIANT_OP_NOT_EQUAL_Quaternion))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_NOT_EQUAL, .NIL, .QUATERNION)
  Nil_method_store.VARIANT_OP_EQUAL_AABB = cast(type_of(Nil_method_store.VARIANT_OP_EQUAL_AABB))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_EQUAL, .NIL, .AABB)
  Nil_method_store.VARIANT_OP_NOT_EQUAL_AABB = cast(type_of(Nil_method_store.VARIANT_OP_NOT_EQUAL_AABB))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_NOT_EQUAL, .NIL, .AABB)
  Nil_method_store.VARIANT_OP_EQUAL_Basis = cast(type_of(Nil_method_store.VARIANT_OP_EQUAL_Basis))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_EQUAL, .NIL, .BASIS)
  Nil_method_store.VARIANT_OP_NOT_EQUAL_Basis = cast(type_of(Nil_method_store.VARIANT_OP_NOT_EQUAL_Basis))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_NOT_EQUAL, .NIL, .BASIS)
  Nil_method_store.VARIANT_OP_EQUAL_Transform3D = cast(type_of(Nil_method_store.VARIANT_OP_EQUAL_Transform3D))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_EQUAL, .NIL, .TRANSFORM3D)
  Nil_method_store.VARIANT_OP_NOT_EQUAL_Transform3D = cast(type_of(Nil_method_store.VARIANT_OP_NOT_EQUAL_Transform3D))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_NOT_EQUAL, .NIL, .TRANSFORM3D)
  Nil_method_store.VARIANT_OP_EQUAL_Projection = cast(type_of(Nil_method_store.VARIANT_OP_EQUAL_Projection))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_EQUAL, .NIL, .PROJECTION)
  Nil_method_store.VARIANT_OP_NOT_EQUAL_Projection = cast(type_of(Nil_method_store.VARIANT_OP_NOT_EQUAL_Projection))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_NOT_EQUAL, .NIL, .PROJECTION)
  Nil_method_store.VARIANT_OP_EQUAL_Color = cast(type_of(Nil_method_store.VARIANT_OP_EQUAL_Color))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_EQUAL, .NIL, .COLOR)
  Nil_method_store.VARIANT_OP_NOT_EQUAL_Color = cast(type_of(Nil_method_store.VARIANT_OP_NOT_EQUAL_Color))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_NOT_EQUAL, .NIL, .COLOR)
  Nil_method_store.VARIANT_OP_EQUAL_StringName = cast(type_of(Nil_method_store.VARIANT_OP_EQUAL_StringName))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_EQUAL, .NIL, .STRING_NAME)
  Nil_method_store.VARIANT_OP_NOT_EQUAL_StringName = cast(type_of(Nil_method_store.VARIANT_OP_NOT_EQUAL_StringName))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_NOT_EQUAL, .NIL, .STRING_NAME)
  Nil_method_store.VARIANT_OP_EQUAL_NodePath = cast(type_of(Nil_method_store.VARIANT_OP_EQUAL_NodePath))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_EQUAL, .NIL, .NODE_PATH)
  Nil_method_store.VARIANT_OP_NOT_EQUAL_NodePath = cast(type_of(Nil_method_store.VARIANT_OP_NOT_EQUAL_NodePath))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_NOT_EQUAL, .NIL, .NODE_PATH)
  Nil_method_store.VARIANT_OP_EQUAL_RID = cast(type_of(Nil_method_store.VARIANT_OP_EQUAL_RID))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_EQUAL, .NIL, .RID)
  Nil_method_store.VARIANT_OP_NOT_EQUAL_RID = cast(type_of(Nil_method_store.VARIANT_OP_NOT_EQUAL_RID))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_NOT_EQUAL, .NIL, .RID)
  Nil_method_store.VARIANT_OP_EQUAL_Object = cast(type_of(Nil_method_store.VARIANT_OP_EQUAL_Object))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_EQUAL, .NIL, .OBJECT)
  Nil_method_store.VARIANT_OP_NOT_EQUAL_Object = cast(type_of(Nil_method_store.VARIANT_OP_NOT_EQUAL_Object))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_NOT_EQUAL, .NIL, .OBJECT)
  Nil_method_store.VARIANT_OP_AND_Object = cast(type_of(Nil_method_store.VARIANT_OP_AND_Object))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_AND, .NIL, .OBJECT)
  Nil_method_store.VARIANT_OP_OR_Object = cast(type_of(Nil_method_store.VARIANT_OP_OR_Object))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_OR, .NIL, .OBJECT)
  Nil_method_store.VARIANT_OP_XOR_Object = cast(type_of(Nil_method_store.VARIANT_OP_XOR_Object))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_XOR, .NIL, .OBJECT)
  Nil_method_store.VARIANT_OP_EQUAL_Callable = cast(type_of(Nil_method_store.VARIANT_OP_EQUAL_Callable))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_EQUAL, .NIL, .CALLABLE)
  Nil_method_store.VARIANT_OP_NOT_EQUAL_Callable = cast(type_of(Nil_method_store.VARIANT_OP_NOT_EQUAL_Callable))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_NOT_EQUAL, .NIL, .CALLABLE)
  Nil_method_store.VARIANT_OP_EQUAL_Signal = cast(type_of(Nil_method_store.VARIANT_OP_EQUAL_Signal))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_EQUAL, .NIL, .SIGNAL)
  Nil_method_store.VARIANT_OP_NOT_EQUAL_Signal = cast(type_of(Nil_method_store.VARIANT_OP_NOT_EQUAL_Signal))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_NOT_EQUAL, .NIL, .SIGNAL)
  Nil_method_store.VARIANT_OP_EQUAL_Dictionary = cast(type_of(Nil_method_store.VARIANT_OP_EQUAL_Dictionary))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_EQUAL, .NIL, .DICTIONARY)
  Nil_method_store.VARIANT_OP_NOT_EQUAL_Dictionary = cast(type_of(Nil_method_store.VARIANT_OP_NOT_EQUAL_Dictionary))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_NOT_EQUAL, .NIL, .DICTIONARY)
  Nil_method_store.VARIANT_OP_IN_Dictionary = cast(type_of(Nil_method_store.VARIANT_OP_IN_Dictionary))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_IN, .NIL, .DICTIONARY)
  Nil_method_store.VARIANT_OP_EQUAL_Array = cast(type_of(Nil_method_store.VARIANT_OP_EQUAL_Array))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_EQUAL, .NIL, .ARRAY)
  Nil_method_store.VARIANT_OP_NOT_EQUAL_Array = cast(type_of(Nil_method_store.VARIANT_OP_NOT_EQUAL_Array))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_NOT_EQUAL, .NIL, .ARRAY)
  Nil_method_store.VARIANT_OP_IN_Array = cast(type_of(Nil_method_store.VARIANT_OP_IN_Array))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_IN, .NIL, .ARRAY)
  Nil_method_store.VARIANT_OP_EQUAL_PackedByteArray = cast(type_of(Nil_method_store.VARIANT_OP_EQUAL_PackedByteArray))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_EQUAL, .NIL, .PACKED_BYTE_ARRAY)
  Nil_method_store.VARIANT_OP_NOT_EQUAL_PackedByteArray = cast(type_of(Nil_method_store.VARIANT_OP_NOT_EQUAL_PackedByteArray))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_NOT_EQUAL, .NIL, .PACKED_BYTE_ARRAY)
  Nil_method_store.VARIANT_OP_EQUAL_PackedInt32Array = cast(type_of(Nil_method_store.VARIANT_OP_EQUAL_PackedInt32Array))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_EQUAL, .NIL, .PACKED_INT32_ARRAY)
  Nil_method_store.VARIANT_OP_NOT_EQUAL_PackedInt32Array = cast(type_of(Nil_method_store.VARIANT_OP_NOT_EQUAL_PackedInt32Array))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_NOT_EQUAL, .NIL, .PACKED_INT32_ARRAY)
  Nil_method_store.VARIANT_OP_EQUAL_PackedInt64Array = cast(type_of(Nil_method_store.VARIANT_OP_EQUAL_PackedInt64Array))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_EQUAL, .NIL, .PACKED_INT64_ARRAY)
  Nil_method_store.VARIANT_OP_NOT_EQUAL_PackedInt64Array = cast(type_of(Nil_method_store.VARIANT_OP_NOT_EQUAL_PackedInt64Array))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_NOT_EQUAL, .NIL, .PACKED_INT64_ARRAY)
  Nil_method_store.VARIANT_OP_EQUAL_PackedFloat32Array = cast(type_of(Nil_method_store.VARIANT_OP_EQUAL_PackedFloat32Array))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_EQUAL, .NIL, .PACKED_FLOAT32_ARRAY)
  Nil_method_store.VARIANT_OP_NOT_EQUAL_PackedFloat32Array = cast(type_of(Nil_method_store.VARIANT_OP_NOT_EQUAL_PackedFloat32Array))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_NOT_EQUAL, .NIL, .PACKED_FLOAT32_ARRAY)
  Nil_method_store.VARIANT_OP_EQUAL_PackedFloat64Array = cast(type_of(Nil_method_store.VARIANT_OP_EQUAL_PackedFloat64Array))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_EQUAL, .NIL, .PACKED_FLOAT64_ARRAY)
  Nil_method_store.VARIANT_OP_NOT_EQUAL_PackedFloat64Array = cast(type_of(Nil_method_store.VARIANT_OP_NOT_EQUAL_PackedFloat64Array))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_NOT_EQUAL, .NIL, .PACKED_FLOAT64_ARRAY)
  Nil_method_store.VARIANT_OP_EQUAL_PackedStringArray = cast(type_of(Nil_method_store.VARIANT_OP_EQUAL_PackedStringArray))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_EQUAL, .NIL, .PACKED_STRING_ARRAY)
  Nil_method_store.VARIANT_OP_NOT_EQUAL_PackedStringArray = cast(type_of(Nil_method_store.VARIANT_OP_NOT_EQUAL_PackedStringArray))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_NOT_EQUAL, .NIL, .PACKED_STRING_ARRAY)
  Nil_method_store.VARIANT_OP_EQUAL_PackedVector2Array = cast(type_of(Nil_method_store.VARIANT_OP_EQUAL_PackedVector2Array))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_EQUAL, .NIL, .PACKED_VECTOR2_ARRAY)
  Nil_method_store.VARIANT_OP_NOT_EQUAL_PackedVector2Array = cast(type_of(Nil_method_store.VARIANT_OP_NOT_EQUAL_PackedVector2Array))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_NOT_EQUAL, .NIL, .PACKED_VECTOR2_ARRAY)
  Nil_method_store.VARIANT_OP_EQUAL_PackedVector3Array = cast(type_of(Nil_method_store.VARIANT_OP_EQUAL_PackedVector3Array))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_EQUAL, .NIL, .PACKED_VECTOR3_ARRAY)
  Nil_method_store.VARIANT_OP_NOT_EQUAL_PackedVector3Array = cast(type_of(Nil_method_store.VARIANT_OP_NOT_EQUAL_PackedVector3Array))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_NOT_EQUAL, .NIL, .PACKED_VECTOR3_ARRAY)
  Nil_method_store.VARIANT_OP_EQUAL_PackedColorArray = cast(type_of(Nil_method_store.VARIANT_OP_EQUAL_PackedColorArray))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_EQUAL, .NIL, .PACKED_COLOR_ARRAY)
  Nil_method_store.VARIANT_OP_NOT_EQUAL_PackedColorArray = cast(type_of(Nil_method_store.VARIANT_OP_NOT_EQUAL_PackedColorArray))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_NOT_EQUAL, .NIL, .PACKED_COLOR_ARRAY)
  Nil_method_store.VARIANT_OP_EQUAL_PackedVector4Array = cast(type_of(Nil_method_store.VARIANT_OP_EQUAL_PackedVector4Array))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_EQUAL, .NIL, .PACKED_VECTOR4_ARRAY)
  Nil_method_store.VARIANT_OP_NOT_EQUAL_PackedVector4Array = cast(type_of(Nil_method_store.VARIANT_OP_NOT_EQUAL_PackedVector4Array))gdAPI.Variant_Utils.GetPtrOperatorEvaluator(.VARIANT_OP_NOT_EQUAL, .NIL, .PACKED_VECTOR4_ARRAY)
}
