package GDWrapper


Init_Builtins :: proc() {

init_StringName_Methods(&StringName_M_List) //MUST be first in order to destroy the StringNames which will be created for retrieving MethodBind
init_bool_Methods(&Bool_M_List)
init_int_Methods(&Int_M_List)
init_float_Methods(&float_M_List)
init_Vector2_Methods(&Vector2_M_List)
init_Vector2i_Methods(&Vector2i_M_List)
init_Rect2_Methods(&Rect2_M_List)
init_Rect2i_Methods(&Rect2i_M_List)
init_Vector3_Methods(&Vector3_M_List)
init_Vector3i_Methods(&Vector3i_M_List)
init_Vector4_Methods(&Vector4_M_List)
init_Vector4i_Methods(&Vector4i_M_List)
init_Plane_Methods(&Plane_M_List)
init_Color_Methods(&Color_M_List)
init_Quaternion_Methods(&Quaternion_M_List)
init_String_Methods(&gdstring_M_List)
init_NodePath_Methods(&NodePath_M_List)
init_RID_Methods(&RID_M_List)
init_Callable_Methods(&Callable_M_List)
init_Signal_Methods(&Signal_M_List)
init_Dictionary_Methods(&Dictionary_M_List)
init_Transform2D_Methods(&Transform2D_M_List)
init_AABB_Methods(&AABB_M_List)
init_Basis_Methods(&Basis_M_List)
init_Transform3D_Methods(&Transform3D_M_List)
init_Projection_Methods(&Projection_M_List)
init_Array_Methods(&Array_M_List)
init_PackedByteArray_Methods(&PackedByteArray_M_List)
init_PackedInt32Array_Methods(&PackedInt32Array_M_List)
init_PackedInt64Array_Methods(&PackedInt64Array_M_List)
init_PackedFloat32Array_Methods(&PackedFloat32Array_M_List)
init_PackedFloat64Array_Methods(&PackedFloat64Array_M_List)
init_PackedStringArray_Methods(&PackedStringArray_M_List)
init_PackedVector2Array_Methods(&PackedVector2Array_M_List)
init_PackedVector3Array_Methods(&PackedVector3Array_M_List)
init_PackedColorArray_Methods(&PackedColorArray_M_List)
init_PackedVector4Array_Methods(&PackedVector4Array_M_List)
}
Bool_M_List: bool_Methods_list
Int_M_List: int_Methods_list
float_M_List: float_Methods_list
Vector2_M_List: Vector2_Methods_list
Vector2i_M_List: Vector2i_Methods_list
Rect2_M_List: Rect2_Methods_list
Rect2i_M_List: Rect2i_Methods_list
Vector3_M_List: Vector3_Methods_list
Vector3i_M_List: Vector3i_Methods_list
Vector4_M_List: Vector4_Methods_list
Vector4i_M_List: Vector4i_Methods_list
Plane_M_List: Plane_Methods_list
Color_M_List: Color_Methods_list
Quaternion_M_List: Quaternion_Methods_list
gdstring_M_List: String_Methods_list
StringName_M_List: StringName_Methods_list
NodePath_M_List: NodePath_Methods_list
RID_M_List: RID_Methods_list
Callable_M_List: Callable_Methods_list
Signal_M_List: Signal_Methods_list
Dictionary_M_List: Dictionary_Methods_list
Transform2D_M_List: Transform2D_Methods_list
AABB_M_List: AABB_Methods_list
Basis_M_List: Basis_Methods_list
Transform3D_M_List: Transform3D_Methods_list
Projection_M_List: Projection_Methods_list
Array_M_List: Array_Methods_list
PackedByteArray_M_List: PackedByteArray_Methods_list
PackedInt32Array_M_List: PackedInt32Array_Methods_list
PackedInt64Array_M_List: PackedInt64Array_Methods_list
PackedFloat32Array_M_List: PackedFloat32Array_Methods_list
PackedFloat64Array_M_List: PackedFloat64Array_Methods_list
PackedStringArray_M_List: PackedStringArray_Methods_list
PackedVector2Array_M_List: PackedVector2Array_Methods_list
PackedVector3Array_M_List: PackedVector3Array_Methods_list
PackedColorArray_M_List: PackedColorArray_Methods_list
PackedVector4Array_M_List: PackedVector4Array_Methods_list