package Toxin

import GDE "shared:GDWrapper/gdAPI/gdextension"
import GDW "shared:GDWrapper"


PackedByteArray_Methods: GDW.PackedByteArray_Methods_list
PackedInt32Array_Methods: GDW.PackedInt32Array_Methods_list
PackedInt64Array_Methods: GDW.PackedInt64Array_Methods_list
PackedFloat32Array_Methods: GDW.PackedFloat32Array_Methods_list
PackedFloat64Array_Methods: GDW.PackedFloat64Array_Methods_list
PackedStringArray_Methods: GDW.PackedStringArray_Methods_list
PackedVector2Array_Methods: GDW.PackedVector2Array_Methods_list
PackedVector3Array_Methods: GDW.PackedVector3Array_Methods_list
PackedColorArray_Methods: GDW.PackedColorArray_Methods_list
PackedVector4Array_Methods: GDW.PackedVector4Array_Methods_list
GDDictionary_Methods: GDW.GDDictionary_Methods_list


RefCounted_Methods_list: GDW.RefCounted_Methods_list