package GDWrapper

import GDE "gdAPI/gdextension"
import "core:reflect"

//Just the whole list of all the class names that appear in the api json.
//No idea, I just copy/pasted.
//Should be useful for:
// * Declaring the class in your custom class
// * Hints
// * Having a table of already allocated and hashed StringName values
//Mainly want to get away from using raw strings.
//Name is very long. Yes.

ClassNameString :: string

SN_Error :: enum {
    ALREADY_NIL,
    BAD_INDEX,
}

GDClass_StringName_get :: proc(classname_index: ClassName_Index) -> ^StringName {
    //ClassName_StringNames[classname_index]
    if ClassName_StringNames[classname_index].ptr == nil {
        StringConstruct(&ClassName_StringNames[classname_index], reflect.enum_field_names(ClassName_Index)[classname_index])
    }
    return &ClassName_StringNames[classname_index]
}

ClassName_StringName_Del :: proc(classname_index: ClassName_Index) -> SN_Error {
    when ODIN_DEBUG {
        if int(classname_index) > len(ClassName_Index) {
            return .BAD_INDEX
        }
        if ClassName_StringNames[classname_index].ptr == nil {
            return .ALREADY_NIL
        }
    }

    StringName_M_List.Destroy(&ClassName_StringNames[classname_index])

    return nil
}

ClassName_Index :: enum {
    nil,
    Marshalls,
    ClassDB,
Engine,
ZIPReader,
ZIPPacker,
Window,
WebSocketPeer,
WebSocketMultiplayerPeer,
WebRTCPeerConnection,
WebRTCMultiplayerPeer,
VideoStreamPlayback,
UPNPDevice,
UPNP,
TreeItem,
Tree,
TranslationServer,
TileSetScenesCollectionSource,
TileSetAtlasSource,
TileSet,
TileMapPattern,
TileMapLayer,
TileMap,
Texture2D,
TextServer,
TextParagraph,
TextLine,
TextEdit,
SurfaceTool,
SpriteFrames,
Skeleton3D,
Shader,
ScriptCreateDialog,
SceneTree,
SceneReplicationConfig,
SceneMultiplayer,
RigidBody3D,
RigidBody2D,
RichTextLabel,
ResourceSaver,
ResourceLoader,
RenderingServer,
RenderingDevice,
RegEx,
RDShaderFile,
ProjectSettings,
PortableCompressedTexture2D,
PopupMenu,
PhysicsServer3D,
PhysicsServer2D,
PhysicsRayQueryParameters3D,
PhysicsRayQueryParameters2D,
PhysicsDirectSpaceState3D,
PhysicsDirectSpaceState2D,
PhysicsDirectBodyState3D,
PhysicsDirectBodyState2D,
PhysicsBody3D,
PhysicsBody2D,
PhysicalBone3D,
Performance,
OptionButton,
OpenXRAPIExtension,
OS,
Noise,
Node3D,
Node,
NavigationServer3D,
NavigationServer2D,
NavigationMeshGenerator,
NativeMenu,
MultiplayerAPI,
Line2D,
JavaScriptBridge,
ItemList,
InputMap,
Input,
ImporterMesh,
ImmediateMesh,
IP,
HTTPRequest,
GridMap,
GraphNode,
Geometry3D,
Geometry2D,
GLTFDocument,
Font,
FileDialog,
Expression,
EngineDebugger,
EditorUndoRedoManager,
EditorScenePostImportPlugin,
EditorNode3DGizmoPlugin,
EditorNode3DGizmo,
EditorInterface,
EditorImportPlugin,
EditorFileDialog,
EditorDebuggerSession,
EditorCommandPalette,
ENetMultiplayerPeer,
ENetConnection,
EditorProperty,
EditorExportPlatform,
DisplayServer,
Curve3D,
Curve2D,
Curve,
Control,
CodeEdit,
CanvasItem,
BitMap,
AudioStreamRandomizer,
AudioStreamPlaybackPolyphonic,
AudioServer,
AudioEffectSpectrumAnalyzerInstance,
ArrayMesh,
AnimationPlayer,
AnimationNodeStateMachinePlayback,
AnimationNodeStateMachine,
AnimationNodeBlendTree,
AnimationNodeBlendSpace2D,
AnimationNodeBlendSpace1D,
AnimationNode,
Animation,
AnimatedSprite3D,
AnimatedSprite2D,
AcceptDialog,
EngineProfiler,
ResourceUID,
GDExtensionManager,
GodotInstance,
GDExtension,
ResourceImporter,
ImageFormatLoaderExtension,
ImageFormatLoader,
PackedDataContainerRef,
PackedDataContainer,
RandomNumberGenerator,
EncodedObjectAsID,
AStarGrid2D,
AStar2D,
AStar3D,
PCKPacker,
ConfigFile,
JSON,
XMLParser,
Logger,
Semaphore,
Mutex,
Thread,
DirAccess,
FileAccess,
TriangleMesh,
UndoRedo,
OptimizedTranslation,
TranslationDomain,
Translation,
MainLoop,
DTLSServer,
PacketPeerDTLS,
StreamPeerTLS,
Crypto,
HMACContext,
TLSOptions,
CryptoKey,
X509Certificate,
AESContext,
HashingContext,
HTTPClient,
WorkerThreadPool,
UDPServer,
PacketPeerUDP,
PacketPeerStream,
PacketPeerExtension,
PacketPeer,
UDSServer,
StreamPeerUDS,
TCPServer,
StreamPeerTCP,
StreamPeerGZIP,
StreamPeerBuffer,
StreamPeerExtension,
SocketServer,
StreamPeerSocket,
StreamPeer,
InputEventMIDI,
InputEventPanGesture,
InputEventMagnifyGesture,
InputEventGesture,
InputEventAction,
InputEventScreenTouch,
InputEventScreenDrag,
InputEventJoypadMotion,
InputEventJoypadButton,
InputEventMouseMotion,
InputEventMouseButton,
InputEventMouse,
InputEventShortcut,
InputEventKey,
InputEventWithModifiers,
InputEventFromWindow,
InputEvent,
Shortcut,
Image,
MissingResource,
ScriptLanguageExtension,
ScriptExtension,
ScriptBacktrace,
ScriptLanguage,
Script,
ResourceFormatSaver,
ResourceFormatLoader,
Time,
Resource,
WeakRef,
RefCounted,
Object,
RDPipelineSpecializationConstant,
CameraServer,
NavigationServer3DManager,
NavigationServer2DManager,
PhysicsServer2DManager,
PhysicsServer3DManager,
TextServerDummy,
TextServerExtension,
TextServerManager,
EditorPaths,
MultiplayerPeer,
OpenXRAndroidThreadSettingsExtension,
OpenXRRenderModelExtension,
OpenXRFutureExtension,
OpenXRFrameSynthesisExtension,
OpenXRFutureResult,
OpenXRExtensionWrapperExtension,
OpenXRExtensionWrapper,
Viewport,
PlaceholderMaterial,
Material,
Texture,
InstancePlaceholder,
MissingNode,
StyleBox,
ThemeDB,
TextServerAdvanced,
EditorTranslationParserPlugin,
GDScript,
XRServer,
XRInterfaceExtension,
XRHandTracker,
XRFaceTracker,
XRControllerTracker,
XRBodyTracker,
XRPose,
XRPositionalTracker,
XRVRS,
XRTracker,
XRInterface,
PhysicsTestMotionResult3D,
PhysicsTestMotionParameters3D,
Shape3D,
PhysicsShapeQueryParameters3D,
PhysicsPointQueryParameters3D,
PhysicsDirectSpaceState3DExtension,
PhysicsDirectBodyState3DExtension,
PhysicsServer3DRenderingServerHandler,
PhysicsServer3DExtension,
NavigationPathQueryResult3D,
NavigationPathQueryParameters3D,
PhysicsTestMotionResult2D,
PhysicsTestMotionParameters2D,
Shape2D,
PhysicsShapeQueryParameters2D,
PhysicsPointQueryParameters2D,
PhysicsDirectSpaceState2DExtension,
PhysicsDirectBodyState2DExtension,
PhysicsServer2DExtension,
NavigationPathQueryResult2D,
NavigationPathQueryParameters2D,
MovieWriter,
CameraFeed,
UniformSetCacheRD,
FramebufferCacheRD,
RenderSceneBuffersRD,
RenderSceneBuffersExtension,
RenderSceneBuffersConfiguration,
RenderSceneDataRD,
RenderSceneDataExtension,
RenderDataRD,
RenderSceneData,
RenderSceneBuffers,
RenderDataExtension,
RenderData,
RDShaderSPIRV,
RDShaderSource,
RDPipelineColorBlendState,
RDPipelineColorBlendStateAttachment,
RDPipelineDepthStencilState,
RDPipelineMultisampleState,
RDPipelineRasterizationState,
RDUniform,
RDVertexAttribute,
RDSamplerState,
RDFramebufferPass,
RDAttachmentFormat,
RDTextureView,
RDTextureFormat,
ShaderIncludeDB,
AudioEffectLimiter,
AudioEffectCapture,
AudioEffectSpectrumAnalyzer,
AudioEffectRecord,
AudioEffectPhaser,
AudioEffectPitchShift,
AudioEffectHardLimiter,
AudioEffectCompressor,
AudioEffectDelay,
AudioEffectChorus,
AudioEffectPanner,
AudioEffectStereoEnhance,
AudioEffectDistortion,
AudioEffectEQ21,
AudioEffectEQ10,
AudioEffectEQ6,
AudioEffectHighShelfFilter,
AudioEffectLowShelfFilter,
AudioEffectBandLimitFilter,
AudioEffectNotchFilter,
AudioEffectBandPassFilter,
AudioEffectHighPassFilter,
AudioEffectLowPassFilter,
AudioEffectReverb,
AudioEffectAmplify,
AudioStreamGeneratorPlayback,
AudioStreamGenerator,
AudioBusLayout,
AudioEffectFilter,
AudioEffectEQ,
AudioEffectInstance,
AudioEffect,
AudioSamplePlayback,
AudioSample,
AudioStreamMicrophone,
AudioStreamPlaybackResampled,
AudioStreamPlayback,
AudioStream,
AnimationRootNode,
AnimationTree,
AnimationMixer,
SubtweenTweener,
MethodTweener,
CallbackTweener,
IntervalTweener,
PropertyTweener,
Tweener,
Tween,
FoldableContainer,
FoldableGroup,
GraphEdit,
GraphFrame,
GraphElement,
VSplitContainer,
HSplitContainer,
SplitContainer,
SubViewportContainer,
CharFXTransform,
RichTextEffect,
ColorPickerButton,
ColorPicker,
SpinBox,
MenuButton,
MenuBar,
CodeHighlighter,
SyntaxHighlighter,
ConfirmationDialog,
VideoStream,
VideoStreamPlayer,
LineEdit,
TextureProgressBar,
MarginContainer,
VFlowContainer,
HFlowContainer,
FlowContainer,
PanelContainer,
ScrollContainer,
CenterContainer,
GridContainer,
VBoxContainer,
HBoxContainer,
BoxContainer,
TextureButton,
VSeparator,
HSeparator,
Separator,
TabBar,
TabContainer,
AspectRatioContainer,
ReferenceRect,
NinePatchRect,
ColorRect,
TextureRect,
Container,
Panel,
LinkButton,
CheckButton,
CheckBox,
PopupPanel,
Popup,
VSlider,
HSlider,
Slider,
ProgressBar,
VScrollBar,
HScrollBar,
ScrollBar,
Range,
LabelSettings,
Label,
Button,
ButtonGroup,
BaseButton,
StatusIndicator,
Theme,
ResourcePreloader,
CanvasLayer,
Timer,
MultiplayerAPIExtension,
MultiplayerPeerExtension,
CompositorEffect,
ViewportTexture,
SubViewport,
World2D,
World3D,
SkeletonModification2DFABRIK,
SkeletonModification2DCCDIK,
SkeletonModification2DLookAt,
SkeletonModification2D,
SkeletonModificationStack2D,
ParallaxLayer,
ParallaxBackground,
RemoteTransform2D,
Parallax2D,
TileData,
TileSetSource,
TouchScreenButton,
DampedSpringJoint2D,
GrooveJoint2D,
PinJoint2D,
Joint2D,
AudioListener2D,
Camera2D,
CanvasModulate,
BackBufferCopy,
OccluderPolygon2D,
LightOccluder2D,
DirectionalLight2D,
PointLight2D,
Light2D,
Bone2D,
Skeleton2D,
Polygon2D,
VisibleOnScreenEnabler2D,
VisibleOnScreenNotifier2D,
ShapeCast2D,
RayCast2D,
CollisionPolygon2D,
CollisionShape2D,
Area2D,
KinematicCollision2D,
CharacterBody2D,
AnimatableBody2D,
StaticBody2D,
CollisionObject2D,
MultiMeshInstance2D,
MeshInstance2D,
Marker2D,
Sprite2D,
GPUParticles2D,
CPUParticles2D,
CanvasGroup,
Node2D,
CanvasItemMaterial,
CanvasTexture,
ShaderMaterial,
VisualShaderNodeParticleEmit,
VisualShaderNodeParticleAccelerator,
VisualShaderNodeParticleRandomness,
VisualShaderNodeParticleConeVelocity,
VisualShaderNodeParticleMultiplyByAxisAngle,
VisualShaderNodeParticleMeshEmitter,
VisualShaderNodeParticleRingEmitter,
VisualShaderNodeParticleBoxEmitter,
VisualShaderNodeParticleSphereEmitter,
VisualShaderNodeParticleEmitter,
VisualShaderNodeParticleOutput,
VisualShaderNodeSDFRaymarch,
VisualShaderNodeTextureSDFNormal,
VisualShaderNodeTextureSDF,
VisualShaderNodeScreenUVToSDF,
VisualShaderNodeSDFToScreenUV,
VisualShaderNodeReroute,
VisualShaderNodeVaryingGetter,
VisualShaderNodeVaryingSetter,
VisualShaderNodeVarying,
VisualShaderNodeRotationByAxis,
VisualShaderNodeRemap,
VisualShaderNodeRandomRange,
VisualShaderNodeProximityFade,
VisualShaderNodeDistanceFade,
VisualShaderNodeBillboard,
VisualShaderNodeMultiplyAdd,
VisualShaderNodeCompare,
VisualShaderNodeIs,
VisualShaderNodeGlobalExpression,
VisualShaderNodeExpression,
VisualShaderNodeFresnel,
VisualShaderNodeSwitch,
VisualShaderNodeIf,
VisualShaderNodeScreenNormalWorldSpace,
VisualShaderNodeWorldPositionFromDepth,
VisualShaderNodeLinearSceneDepth,
VisualShaderNodeCubemapParameter,
VisualShaderNodeTexture3DParameter,
VisualShaderNodeTexture2DArrayParameter,
VisualShaderNodeTextureParameterTriplanar,
VisualShaderNodeTexture2DParameter,
VisualShaderNodeTextureParameter,
VisualShaderNodeTransformParameter,
VisualShaderNodeVec4Parameter,
VisualShaderNodeVec3Parameter,
VisualShaderNodeVec2Parameter,
VisualShaderNodeColorParameter,
VisualShaderNodeBooleanParameter,
VisualShaderNodeUIntParameter,
VisualShaderNodeIntParameter,
VisualShaderNodeFloatParameter,
VisualShaderNodeParameterRef,
VisualShaderNodeParameter,
VisualShaderNodeCubemap,
VisualShaderNodeTexture3D,
VisualShaderNodeTexture2DArray,
VisualShaderNodeSample3D,
CurveXYZTexture,
VisualShaderNodeCurveXYZTexture,
CurveTexture,
VisualShaderNodeCurveTexture,
VisualShaderNodeTexture,
VisualShaderNodeTransformDecompose,
VisualShaderNodeVectorDecompose,
VisualShaderNodeTransformCompose,
VisualShaderNodeVectorCompose,
VisualShaderNodeMix,
VisualShaderNodeVectorRefract,
VisualShaderNodeVectorDistance,
VisualShaderNodeStep,
VisualShaderNodeSmoothStep,
VisualShaderNodeOuterProduct,
VisualShaderNodeFaceForward,
VisualShaderNodeClamp,
VisualShaderNodeDerivativeFunc,
VisualShaderNodeDeterminant,
VisualShaderNodeVectorLen,
VisualShaderNodeDotProduct,
VisualShaderNodeUVPolarCoord,
VisualShaderNodeUVFunc,
VisualShaderNodeTransformFunc,
VisualShaderNodeColorFunc,
VisualShaderNodeVectorFunc,
VisualShaderNodeUIntFunc,
VisualShaderNodeIntFunc,
VisualShaderNodeFloatFunc,
VisualShaderNodeTransformVecMult,
VisualShaderNodeTransformOp,
VisualShaderNodeColorOp,
VisualShaderNodeVectorOp,
VisualShaderNodeUIntOp,
VisualShaderNodeIntOp,
VisualShaderNodeFloatOp,
VisualShaderNodeTransformConstant,
VisualShaderNodeVec4Constant,
VisualShaderNodeVec3Constant,
VisualShaderNodeVec2Constant,
VisualShaderNodeColorConstant,
VisualShaderNodeBooleanConstant,
VisualShaderNodeUIntConstant,
VisualShaderNodeIntConstant,
VisualShaderNodeFloatConstant,
VisualShaderNodeComment,
VisualShaderNodeFrame,
VisualShaderNodeVectorBase,
VisualShaderNodeConstant,
VisualShaderNodeGroupBase,
VisualShaderNodeResizableBase,
VisualShaderNodeOutput,
VisualShaderNodeInput,
VisualShaderNodeCustom,
VisualShaderNode,
ShaderInclude,
VisualShader,
NavigationLink3D,
NavigationObstacle3D,
NavigationAgent3D,
NavigationMesh,
NavigationRegion3D,
NavigationMeshSourceGeometryData3D,
Generic6DOFJoint3D,
ConeTwistJoint3D,
SliderJoint3D,
HingeJoint3D,
PinJoint3D,
Joint3D,
RemoteTransform3D,
FogMaterial,
FogVolume,
WorldEnvironment,
VisibleOnScreenEnabler3D,
VisibleOnScreenNotifier3D,
PathFollow3D,
Path3D,
MultiMesh,
MultiMeshInstance3D,
ShapeCast3D,
RayCast3D,
CollisionPolygon3D,
CollisionShape3D,
Area3D,
VehicleWheel3D,
VehicleBody3D,
SkeletonIK3D,
LookAtModifier3D,
BoneAttachment3D,
SoftBody3D,
PhysicalBoneSimulator3D,
SpringArm3D,
CharacterBody3D,
KinematicCollision3D,
AnimatableBody3D,
PhysicsMaterial,
StaticBody3D,
CollisionObject3D,
XRFaceModifier3D,
XRHandModifier3D,
XRBodyModifier3D,
XROrigin3D,
XRAnchor3D,
XRController3D,
XRNode3D,
XRCamera3D,
BoneTwistDisperser3D,
LimitAngularVelocityModifier3D,
JacobianIK3D,
CCDIK3D,
FABRIK3D,
IterateIK3D,
SplineIK3D,
ChainIK3D,
TwoBoneIK3D,
IKModifier3D,
AimModifier3D,
ConvertTransformModifier3D,
CopyTransformModifier3D,
BoneConstraint3D,
SpringBoneCollisionPlane3D,
SpringBoneCollisionCapsule3D,
SpringBoneCollisionSphere3D,
SpringBoneCollision3D,
SpringBoneSimulator3D,
JointLimitationCone3D,
JointLimitation3D,
SkeletonProfile,
RetargetModifier3D,
ModifierBoneTarget3D,
SkeletonModifier3D,
RootMotionView,
Marker3D,
Gradient,
CPUParticles3D,
GPUParticlesAttractorVectorField3D,
GPUParticlesAttractorSphere3D,
GPUParticlesAttractorBox3D,
GPUParticlesAttractor3D,
GPUParticlesCollisionHeightField3D,
Texture3D,
GPUParticlesCollisionSDF3D,
GPUParticlesCollisionSphere3D,
GPUParticlesCollisionBox3D,
GPUParticlesCollision3D,
GPUParticles3D,
Lightmapper,
LightmapProbe,
TextureLayered,
LightmapGIData,
Sky,
LightmapGI,
VoxelGIData,
VoxelGI,
Decal,
ReflectionProbe,
SpotLight3D,
OmniLight3D,
DirectionalLight3D,
Light3D,
Label3D,
Sprite3D,
SpriteBase3D,
PolygonOccluder3D,
SphereOccluder3D,
BoxOccluder3D,
QuadOccluder3D,
ArrayOccluder3D,
Occluder3D,
OccluderInstance3D,
Mesh,
MeshInstance3D,
AudioListener3D,
Compositor,
Environment,
Camera3D,
GeometryInstance3D,
VisualInstance3D,
ImporterMeshInstance3D,
SkinReference,
Skin,
Node3DGizmo,
ShaderGlobalsOverride,
AnimationNodeTransition,
AnimationNodeTimeSeek,
AnimationNodeTimeScale,
AnimationNodeSub2,
AnimationNodeBlend3,
AnimationNodeBlend2,
AnimationNodeAdd3,
AnimationNodeAdd2,
AnimationNodeAnimation,
AnimationNodeOneShot,
AnimationNodeOutput,
AnimationNodeStateMachineTransition,
AnimationNodeSync,
AnimationNodeExtension,
GLTFPhysicsShape,
GLTFPhysicsBody,
GLTFMesh,
GLTFLight,
GLTFCamera,
GLTFBufferView,
GLTFAnimation,
GLTFAccessor,
GLTFObjectModelProperty,
GLTFTexture,
GLTFNode,
GLTFDocumentExtensionConvertImporterMesh,
GLTFDocumentExtension,
FBXState,
GLTFState,
FBXDocument,
ENetPacketPeer,
OggPacketSequence,
AudioStreamOggVorbis,
CSGTorus3D,
CSGSphere3D,
CSGShape3D,
CSGPrimitive3D,
CSGPolygon3D,
CSGMesh3D,
CSGCylinder3D,
CSGCombiner3D,
CSGBox3D,
FastNoiseLite,
SceneTreeTimer,
PackedScene,
SceneState,
PolygonPathFinder,
NavigationLink2D,
NavigationObstacle2D,
NavigationAgent2D,
NavigationRegion2D,
NavigationPolygon,
NavigationMeshSourceGeometryData2D,
ConcavePolygonShape2D,
ConvexPolygonShape2D,
CapsuleShape2D,
RectangleShape2D,
CircleShape2D,
SeparationRayShape2D,
SegmentShape2D,
WorldBoundaryShape2D,
PathFollow2D,
Path2D,
AudioStreamPlayer2D,
AudioStreamPolyphonic,
AudioStreamWAV,
AudioStreamPlayer,
BoneMap,
SkeletonProfileHumanoid,
StyleBoxLine,
StyleBoxFlat,
StyleBoxTexture,
StyleBoxEmpty,
ColorPalette,
SystemFont,
FontVariation,
FontFile,
AnimationLibrary,
Texture3DRD,
TextureCubemapArrayRD,
TextureCubemapRD,
Texture2DArrayRD,
TextureLayeredRD,
Texture2DRD,
AnimatedTexture,
DPITexture,
PlaceholderCubemapArray,
PlaceholderCubemap,
PlaceholderTexture2DArray,
PlaceholderTextureLayered,
PlaceholderTexture3D,
PlaceholderTexture2D,
CompressedTexture2DArray,
CompressedCubemapArray,
CompressedCubemap,
CompressedTextureLayered,
Texture2DArray,
CubemapArray,
Cubemap,
CompressedTexture3D,
ImageTexture3D,
ImageTextureLayered,
ExternalTexture,
CameraTexture,
GradientTexture2D,
MeshTexture,
AtlasTexture,
ImageTexture,
CompressedTexture2D,
CameraAttributesPractical,
CameraAttributesPhysical,
CameraAttributes,
ConcavePolygonShape3D,
ConvexPolygonShape3D,
WorldBoundaryShape3D,
HeightMapShape3D,
CylinderShape3D,
CapsuleShape3D,
BoxShape3D,
SphereShape3D,
SeparationRayShape3D,
MeshLibrary,
PhysicalSkyMaterial,
PanoramaSkyMaterial,
ProceduralSkyMaterial,
ORMMaterial3D,
StandardMaterial3D,
BaseMaterial3D,
PointMesh,
RibbonTrailMesh,
TubeTrailMesh,
TorusMesh,
TextMesh,
SphereMesh,
QuadMesh,
PrismMesh,
PlaneMesh,
CylinderMesh,
CapsuleMesh,
BoxMesh,
PrimitiveMesh,
AudioStreamPlayer3D,
MeshDataTool,
PlaceholderMesh,
MeshConvexDecompositionSettings,
GradientTexture1D,
ParticleProcessMaterial,
SkeletonModification2DPhysicalBones,
SkeletonModification2DJiggle,
PhysicalBone2D,
SkeletonModification2DStackHolder,
SkeletonModification2DTwoBoneIK,
JavaScriptObject,
JavaObject,
JavaClass,
JNISingleton,
JavaClassWrapper,
ResourceImporterOggVorbis,
OpenXRBindingModifierEditor,
OpenXRInteractionProfileEditor,
OpenXRInteractionProfileEditorBase,
ResourceImporterMP3,
GridMapEditorPlugin,
EditorSceneFormatImporterBlend,
EditorSceneFormatImporterGLTF,
GDScriptSyntaxHighlighter,
EditorSceneFormatImporterFBX2GLTF,
EditorSceneFormatImporterUFBX,
ResourceImporterWAV,
ResourceImporterTextureAtlas,
ResourceImporterTexture,
ResourceImporterShaderFile,
ResourceImporterScene,
ResourceImporterOBJ,
ResourceImporterLayeredTexture,
ResourceImporterSVG,
ResourceImporterImageFont,
ResourceImporterImage,
ResourceImporterDynamicFont,
ResourceImporterCSVTranslation,
ResourceImporterBMFont,
ResourceImporterBitMap,
EditorDebuggerPlugin,
EditorScenePostImport,
EditorFileSystemImportFormatSupportQuery,
FileSystemDock,
EditorContextMenuPlugin,
EditorScriptPicker,
EditorResourcePicker,
EditorSpinSlider,
EditorFeatureProfile,
EditorInspectorPlugin,
EditorInspector,
EditorSceneFormatImporter,
EditorResourceConversionPlugin,
EditorExportPlatformWindows,
EditorExportPlatformWeb,
EditorExportPlatformVisionOS,
EditorExportPlatformMacOS,
EditorExportPlatformLinuxBSD,
EditorExportPlatformIOS,
EditorExportPlatformAndroid,
EditorExportPreset,
EditorExportPlatformExtension,
EditorExportPlatformAppleEmbedded,
EditorExportPlatformPC,
EditorExportPlugin,
EditorSyntaxHighlighter,
ScriptEditorBase,
ScriptEditor,
EditorVCSInterface,
EditorFileSystemDirectory,
EditorFileSystem,
EditorResourceTooltipPlugin,
EditorResourcePreviewGenerator,
EditorResourcePreview,
EditorToaster,
EditorSettings,
EditorSelection,
EditorDock,
EditorScript,
EditorPlugin,
WebXRInterface,
WebRTCDataChannelExtension,
WebRTCPeerConnectionExtension,
WebRTCDataChannel,
AudioStreamPlaybackOggVorbis,
VideoStreamTheora,
RegExMatch,
OpenXRSpatialMarkerTrackingCapability,
OpenXRSpatialPlaneTrackingCapability,
OpenXRSpatialAnchorCapability,
OpenXRSpatialComponentPersistenceList,
OpenXRSpatialComponentAnchorList,
OpenXRSpatialQueryResultData,
OpenXRSpatialComponentMarkerList,
OpenXRSpatialComponentPlaneSemanticLabelList,
OpenXRSpatialComponentPolygon2DList,
OpenXRSpatialComponentPlaneAlignmentList,
OpenXRSpatialComponentMesh3DList,
OpenXRSpatialComponentMesh2DList,
OpenXRSpatialComponentParentList,
OpenXRSpatialComponentBounded3DList,
OpenXRSpatialComponentBounded2DList,
OpenXRSpatialComponentData,
OpenXRSpatialCapabilityConfigurationPlaneTracking,
OpenXRSpatialContextPersistenceConfig,
OpenXRSpatialCapabilityConfigurationAprilTag,
OpenXRSpatialCapabilityConfigurationAruco,
OpenXRSpatialCapabilityConfigurationMicroQrCode,
OpenXRSpatialCapabilityConfigurationQrCode,
OpenXRSpatialCapabilityConfigurationAnchor,
OpenXRSpatialCapabilityConfigurationBaseHeader,
OpenXRStructureBase,
OpenXRMarkerTracker,
OpenXRPlaneTracker,
OpenXRAnchorTracker,
OpenXRSpatialEntityTracker,
OpenXRSpatialEntityExtension,
OpenXRRenderModelManager,
OpenXRRenderModel,
OpenXRVisibilityMask,
OpenXRHand,
OpenXRCompositionLayerQuad,
OpenXRCompositionLayerCylinder,
OpenXRCompositionLayerEquirect,
OpenXRCompositionLayer,
OpenXRHapticVibration,
OpenXRDpadBindingModifier,
OpenXRHapticBase,
OpenXRAnalogThresholdModifier,
OpenXRBindingModifier,
OpenXRIPBindingModifier,
OpenXRActionBindingModifier,
OpenXRIPBinding,
OpenXRInteractionProfileMetadata,
OpenXRInteractionProfile,
OpenXRActionMap,
OpenXRActionSet,
OpenXRAction,
OpenXRInterface,
OggPacketSequencePlayback,
NoiseTexture2D,
NoiseTexture3D,
OfflineMultiplayerPeer,
MultiplayerSynchronizer,
MultiplayerSpawner,
AudioStreamMP3,
MobileVRInterface,
LightmapperRD,
JSONRPC,
AudioStreamPlaybackSynchronized,
AudioStreamSynchronized,
AudioStreamPlaybackInteractive,
AudioStreamInteractive,
AudioStreamPlaybackPlaylist,
AudioStreamPlaylist,
GLTFTextureSampler,
GLTFSpecGloss,
GLTFSkin,
GLTFSkeleton,
Master,
}

@(private)
ClassName_StringNames : [ClassName_Index]StringName = {
    .nil = StringName({nil}),
    .Marshalls = StringName({nil}),
    .ClassDB = StringName({nil}),
    .Engine = StringName({nil}),
    .ZIPReader = StringName({nil}),
    .ZIPPacker = StringName({nil}),
    .Window = StringName({nil}),
    .WebSocketPeer = StringName({nil}),
    .WebSocketMultiplayerPeer = StringName({nil}),
    .WebRTCPeerConnection = StringName({nil}),
    .WebRTCMultiplayerPeer = StringName({nil}),
    .VideoStreamPlayback = StringName({nil}),
    .UPNPDevice = StringName({nil}),
    .UPNP = StringName({nil}),
    .TreeItem = StringName({nil}),
    .Tree = StringName({nil}),
    .TranslationServer = StringName({nil}),
    .TileSetScenesCollectionSource = StringName({nil}),
    .TileSetAtlasSource = StringName({nil}),
    .TileSet = StringName({nil}),
    .TileMapPattern = StringName({nil}),
    .TileMapLayer = StringName({nil}),
    .TileMap = StringName({nil}),
    .Texture2D = StringName({nil}),
    .TextServer = StringName({nil}),
    .TextParagraph = StringName({nil}),
    .TextLine = StringName({nil}),
    .TextEdit = StringName({nil}),
    .SurfaceTool = StringName({nil}),
    .SpriteFrames = StringName({nil}),
    .Skeleton3D = StringName({nil}),
    .Shader = StringName({nil}),
    .ScriptCreateDialog = StringName({nil}),
    .SceneTree = StringName({nil}),
    .SceneReplicationConfig = StringName({nil}),
    .SceneMultiplayer = StringName({nil}),
    .RigidBody3D = StringName({nil}),
    .RigidBody2D = StringName({nil}),
    .RichTextLabel = StringName({nil}),
    .ResourceSaver = StringName({nil}),
    .ResourceLoader = StringName({nil}),
    .RenderingServer = StringName({nil}),
    .RenderingDevice = StringName({nil}),
    .RegEx = StringName({nil}),
    .RDShaderFile = StringName({nil}),
    .ProjectSettings = StringName({nil}),
    .PortableCompressedTexture2D = StringName({nil}),
    .PopupMenu = StringName({nil}),
    .PhysicsServer3D = StringName({nil}),
    .PhysicsServer2D = StringName({nil}),
    .PhysicsRayQueryParameters3D = StringName({nil}),
    .PhysicsRayQueryParameters2D = StringName({nil}),
    .PhysicsDirectSpaceState3D = StringName({nil}),
    .PhysicsDirectSpaceState2D = StringName({nil}),
    .PhysicsDirectBodyState3D = StringName({nil}),
    .PhysicsDirectBodyState2D = StringName({nil}),
    .PhysicsBody3D = StringName({nil}),
    .PhysicsBody2D = StringName({nil}),
    .PhysicalBone3D = StringName({nil}),
    .Performance = StringName({nil}),
    .OptionButton = StringName({nil}),
    .OpenXRAPIExtension = StringName({nil}),
    .OS = StringName({nil}),
    .Noise = StringName({nil}),
    .Node3D = StringName({nil}),
    .Node = StringName({nil}),
    .NavigationServer3D = StringName({nil}),
    .NavigationServer2D = StringName({nil}),
    .NavigationMeshGenerator = StringName({nil}),
    .NativeMenu = StringName({nil}),
    .MultiplayerAPI = StringName({nil}),
    .Line2D = StringName({nil}),
    .JavaScriptBridge = StringName({nil}),
    .ItemList = StringName({nil}),
    .InputMap = StringName({nil}),
    .Input = StringName({nil}),
    .ImporterMesh = StringName({nil}),
    .ImmediateMesh = StringName({nil}),
    .IP = StringName({nil}),
    .HTTPRequest = StringName({nil}),
    .GridMap = StringName({nil}),
    .GraphNode = StringName({nil}),
    .Geometry3D = StringName({nil}),
    .Geometry2D = StringName({nil}),
    .GLTFDocument = StringName({nil}),
    .Font = StringName({nil}),
    .FileDialog = StringName({nil}),
    .Expression = StringName({nil}),
    .EngineDebugger = StringName({nil}),
    .EditorUndoRedoManager = StringName({nil}),
    .EditorScenePostImportPlugin = StringName({nil}),
    .EditorNode3DGizmoPlugin = StringName({nil}),
    .EditorNode3DGizmo = StringName({nil}),
    .EditorInterface = StringName({nil}),
    .EditorImportPlugin = StringName({nil}),
    .EditorFileDialog = StringName({nil}),
    .EditorDebuggerSession = StringName({nil}),
    .EditorCommandPalette = StringName({nil}),
    .ENetMultiplayerPeer = StringName({nil}),
    .ENetConnection = StringName({nil}),
    .EditorProperty = StringName({nil}),
    .EditorExportPlatform = StringName({nil}),
    .DisplayServer = StringName({nil}),
    .Curve3D = StringName({nil}),
    .Curve2D = StringName({nil}),
    .Curve = StringName({nil}),
    .Control = StringName({nil}),
    .CodeEdit = StringName({nil}),
    .CanvasItem = StringName({nil}),
    .BitMap = StringName({nil}),
    .AudioStreamRandomizer = StringName({nil}),
    .AudioStreamPlaybackPolyphonic = StringName({nil}),
    .AudioServer = StringName({nil}),
    .AudioEffectSpectrumAnalyzerInstance = StringName({nil}),
    .ArrayMesh = StringName({nil}),
    .AnimationPlayer = StringName({nil}),
    .AnimationNodeStateMachinePlayback = StringName({nil}),
    .AnimationNodeStateMachine = StringName({nil}),
    .AnimationNodeBlendTree = StringName({nil}),
    .AnimationNodeBlendSpace2D = StringName({nil}),
    .AnimationNodeBlendSpace1D = StringName({nil}),
    .AnimationNode = StringName({nil}),
    .Animation = StringName({nil}),
    .AnimatedSprite3D = StringName({nil}),
    .AnimatedSprite2D = StringName({nil}),
    .AcceptDialog = StringName({nil}),
    .EngineProfiler = StringName({nil}),
    .ResourceUID = StringName({nil}),
    .GDExtensionManager = StringName({nil}),
    .GodotInstance = StringName({nil}),
    .GDExtension = StringName({nil}),
    .ResourceImporter = StringName({nil}),
    .ImageFormatLoaderExtension = StringName({nil}),
    .ImageFormatLoader = StringName({nil}),
    .PackedDataContainerRef = StringName({nil}),
    .PackedDataContainer = StringName({nil}),
    .RandomNumberGenerator = StringName({nil}),
    .EncodedObjectAsID = StringName({nil}),
    .AStarGrid2D = StringName({nil}),
    .AStar2D = StringName({nil}),
    .AStar3D = StringName({nil}),
    .PCKPacker = StringName({nil}),
    .ConfigFile = StringName({nil}),
    .JSON = StringName({nil}),
    .XMLParser = StringName({nil}),
    .Logger = StringName({nil}),
    .Semaphore = StringName({nil}),
    .Mutex = StringName({nil}),
    .Thread = StringName({nil}),
    .DirAccess = StringName({nil}),
    .FileAccess = StringName({nil}),
    .TriangleMesh = StringName({nil}),
    .UndoRedo = StringName({nil}),
    .OptimizedTranslation = StringName({nil}),
    .TranslationDomain = StringName({nil}),
    .Translation = StringName({nil}),
    .MainLoop = StringName({nil}),
    .DTLSServer = StringName({nil}),
    .PacketPeerDTLS = StringName({nil}),
    .StreamPeerTLS = StringName({nil}),
    .Crypto = StringName({nil}),
    .HMACContext = StringName({nil}),
    .TLSOptions = StringName({nil}),
    .CryptoKey = StringName({nil}),
    .X509Certificate = StringName({nil}),
    .AESContext = StringName({nil}),
    .HashingContext = StringName({nil}),
    .HTTPClient = StringName({nil}),
    .WorkerThreadPool = StringName({nil}),
    .UDPServer = StringName({nil}),
    .PacketPeerUDP = StringName({nil}),
    .PacketPeerStream = StringName({nil}),
    .PacketPeerExtension = StringName({nil}),
    .PacketPeer = StringName({nil}),
    .UDSServer = StringName({nil}),
    .StreamPeerUDS = StringName({nil}),
    .TCPServer = StringName({nil}),
    .StreamPeerTCP = StringName({nil}),
    .StreamPeerGZIP = StringName({nil}),
    .StreamPeerBuffer = StringName({nil}),
    .StreamPeerExtension = StringName({nil}),
    .SocketServer = StringName({nil}),
    .StreamPeerSocket = StringName({nil}),
    .StreamPeer = StringName({nil}),
    .InputEventMIDI = StringName({nil}),
    .InputEventPanGesture = StringName({nil}),
    .InputEventMagnifyGesture = StringName({nil}),
    .InputEventGesture = StringName({nil}),
    .InputEventAction = StringName({nil}),
    .InputEventScreenTouch = StringName({nil}),
    .InputEventScreenDrag = StringName({nil}),
    .InputEventJoypadMotion = StringName({nil}),
    .InputEventJoypadButton = StringName({nil}),
    .InputEventMouseMotion = StringName({nil}),
    .InputEventMouseButton = StringName({nil}),
    .InputEventMouse = StringName({nil}),
    .InputEventShortcut = StringName({nil}),
    .InputEventKey = StringName({nil}),
    .InputEventWithModifiers = StringName({nil}),
    .InputEventFromWindow = StringName({nil}),
    .InputEvent = StringName({nil}),
    .Shortcut = StringName({nil}),
    .Image = StringName({nil}),
    .MissingResource = StringName({nil}),
    .ScriptLanguageExtension = StringName({nil}),
    .ScriptExtension = StringName({nil}),
    .ScriptBacktrace = StringName({nil}),
    .ScriptLanguage = StringName({nil}),
    .Script = StringName({nil}),
    .ResourceFormatSaver = StringName({nil}),
    .ResourceFormatLoader = StringName({nil}),
    .Time = StringName({nil}),
    .Resource = StringName({nil}),
    .WeakRef = StringName({nil}),
    .RefCounted = StringName({nil}),
    .Object = StringName({nil}),
    .RDPipelineSpecializationConstant = StringName({nil}),
    .CameraServer = StringName({nil}),
    .NavigationServer3DManager = StringName({nil}),
    .NavigationServer2DManager = StringName({nil}),
    .PhysicsServer2DManager = StringName({nil}),
    .PhysicsServer3DManager = StringName({nil}),
    .TextServerDummy = StringName({nil}),
    .TextServerExtension = StringName({nil}),
    .TextServerManager = StringName({nil}),
    .EditorPaths = StringName({nil}),
    .MultiplayerPeer = StringName({nil}),
    .OpenXRAndroidThreadSettingsExtension = StringName({nil}),
    .OpenXRRenderModelExtension = StringName({nil}),
    .OpenXRFutureExtension = StringName({nil}),
    .OpenXRFrameSynthesisExtension = StringName({nil}),
    .OpenXRFutureResult = StringName({nil}),
    .OpenXRExtensionWrapperExtension = StringName({nil}),
    .OpenXRExtensionWrapper = StringName({nil}),
    .Viewport = StringName({nil}),
    .PlaceholderMaterial = StringName({nil}),
    .Material = StringName({nil}),
    .Texture = StringName({nil}),
    .InstancePlaceholder = StringName({nil}),
    .MissingNode = StringName({nil}),
    .StyleBox = StringName({nil}),
    .ThemeDB = StringName({nil}),
    .TextServerAdvanced = StringName({nil}),
    .EditorTranslationParserPlugin = StringName({nil}),
    .GDScript = StringName({nil}),
    .XRServer = StringName({nil}),
    .XRInterfaceExtension = StringName({nil}),
    .XRHandTracker = StringName({nil}),
    .XRFaceTracker = StringName({nil}),
    .XRControllerTracker = StringName({nil}),
    .XRBodyTracker = StringName({nil}),
    .XRPose = StringName({nil}),
    .XRPositionalTracker = StringName({nil}),
    .XRVRS = StringName({nil}),
    .XRTracker = StringName({nil}),
    .XRInterface = StringName({nil}),
    .PhysicsTestMotionResult3D = StringName({nil}),
    .PhysicsTestMotionParameters3D = StringName({nil}),
    .Shape3D = StringName({nil}),
    .PhysicsShapeQueryParameters3D = StringName({nil}),
    .PhysicsPointQueryParameters3D = StringName({nil}),
    .PhysicsDirectSpaceState3DExtension = StringName({nil}),
    .PhysicsDirectBodyState3DExtension = StringName({nil}),
    .PhysicsServer3DRenderingServerHandler = StringName({nil}),
    .PhysicsServer3DExtension = StringName({nil}),
    .NavigationPathQueryResult3D = StringName({nil}),
    .NavigationPathQueryParameters3D = StringName({nil}),
    .PhysicsTestMotionResult2D = StringName({nil}),
    .PhysicsTestMotionParameters2D = StringName({nil}),
    .Shape2D = StringName({nil}),
    .PhysicsShapeQueryParameters2D = StringName({nil}),
    .PhysicsPointQueryParameters2D = StringName({nil}),
    .PhysicsDirectSpaceState2DExtension = StringName({nil}),
    .PhysicsDirectBodyState2DExtension = StringName({nil}),
    .PhysicsServer2DExtension = StringName({nil}),
    .NavigationPathQueryResult2D = StringName({nil}),
    .NavigationPathQueryParameters2D = StringName({nil}),
    .MovieWriter = StringName({nil}),
    .CameraFeed = StringName({nil}),
    .UniformSetCacheRD = StringName({nil}),
    .FramebufferCacheRD = StringName({nil}),
    .RenderSceneBuffersRD = StringName({nil}),
    .RenderSceneBuffersExtension = StringName({nil}),
    .RenderSceneBuffersConfiguration = StringName({nil}),
    .RenderSceneDataRD = StringName({nil}),
    .RenderSceneDataExtension = StringName({nil}),
    .RenderDataRD = StringName({nil}),
    .RenderSceneData = StringName({nil}),
    .RenderSceneBuffers = StringName({nil}),
    .RenderDataExtension = StringName({nil}),
    .RenderData = StringName({nil}),
    .RDShaderSPIRV = StringName({nil}),
    .RDShaderSource = StringName({nil}),
    .RDPipelineColorBlendState = StringName({nil}),
    .RDPipelineColorBlendStateAttachment = StringName({nil}),
    .RDPipelineDepthStencilState = StringName({nil}),
    .RDPipelineMultisampleState = StringName({nil}),
    .RDPipelineRasterizationState = StringName({nil}),
    .RDUniform = StringName({nil}),
    .RDVertexAttribute = StringName({nil}),
    .RDSamplerState = StringName({nil}),
    .RDFramebufferPass = StringName({nil}),
    .RDAttachmentFormat = StringName({nil}),
    .RDTextureView = StringName({nil}),
    .RDTextureFormat = StringName({nil}),
    .ShaderIncludeDB = StringName({nil}),
    .AudioEffectLimiter = StringName({nil}),
    .AudioEffectCapture = StringName({nil}),
    .AudioEffectSpectrumAnalyzer = StringName({nil}),
    .AudioEffectRecord = StringName({nil}),
    .AudioEffectPhaser = StringName({nil}),
    .AudioEffectPitchShift = StringName({nil}),
    .AudioEffectHardLimiter = StringName({nil}),
    .AudioEffectCompressor = StringName({nil}),
    .AudioEffectDelay = StringName({nil}),
    .AudioEffectChorus = StringName({nil}),
    .AudioEffectPanner = StringName({nil}),
    .AudioEffectStereoEnhance = StringName({nil}),
    .AudioEffectDistortion = StringName({nil}),
    .AudioEffectEQ21 = StringName({nil}),
    .AudioEffectEQ10 = StringName({nil}),
    .AudioEffectEQ6 = StringName({nil}),
    .AudioEffectHighShelfFilter = StringName({nil}),
    .AudioEffectLowShelfFilter = StringName({nil}),
    .AudioEffectBandLimitFilter = StringName({nil}),
    .AudioEffectNotchFilter = StringName({nil}),
    .AudioEffectBandPassFilter = StringName({nil}),
    .AudioEffectHighPassFilter = StringName({nil}),
    .AudioEffectLowPassFilter = StringName({nil}),
    .AudioEffectReverb = StringName({nil}),
    .AudioEffectAmplify = StringName({nil}),
    .AudioStreamGeneratorPlayback = StringName({nil}),
    .AudioStreamGenerator = StringName({nil}),
    .AudioBusLayout = StringName({nil}),
    .AudioEffectFilter = StringName({nil}),
    .AudioEffectEQ = StringName({nil}),
    .AudioEffectInstance = StringName({nil}),
    .AudioEffect = StringName({nil}),
    .AudioSamplePlayback = StringName({nil}),
    .AudioSample = StringName({nil}),
    .AudioStreamMicrophone = StringName({nil}),
    .AudioStreamPlaybackResampled = StringName({nil}),
    .AudioStreamPlayback = StringName({nil}),
    .AudioStream = StringName({nil}),
    .AnimationRootNode = StringName({nil}),
    .AnimationTree = StringName({nil}),
    .AnimationMixer = StringName({nil}),
    .SubtweenTweener = StringName({nil}),
    .MethodTweener = StringName({nil}),
    .CallbackTweener = StringName({nil}),
    .IntervalTweener = StringName({nil}),
    .PropertyTweener = StringName({nil}),
    .Tweener = StringName({nil}),
    .Tween = StringName({nil}),
    .FoldableContainer = StringName({nil}),
    .FoldableGroup = StringName({nil}),
    .GraphEdit = StringName({nil}),
    .GraphFrame = StringName({nil}),
    .GraphElement = StringName({nil}),
    .VSplitContainer = StringName({nil}),
    .HSplitContainer = StringName({nil}),
    .SplitContainer = StringName({nil}),
    .SubViewportContainer = StringName({nil}),
    .CharFXTransform = StringName({nil}),
    .RichTextEffect = StringName({nil}),
    .ColorPickerButton = StringName({nil}),
    .ColorPicker = StringName({nil}),
    .SpinBox = StringName({nil}),
    .MenuButton = StringName({nil}),
    .MenuBar = StringName({nil}),
    .CodeHighlighter = StringName({nil}),
    .SyntaxHighlighter = StringName({nil}),
    .ConfirmationDialog = StringName({nil}),
    .VideoStream = StringName({nil}),
    .VideoStreamPlayer = StringName({nil}),
    .LineEdit = StringName({nil}),
    .TextureProgressBar = StringName({nil}),
    .MarginContainer = StringName({nil}),
    .VFlowContainer = StringName({nil}),
    .HFlowContainer = StringName({nil}),
    .FlowContainer = StringName({nil}),
    .PanelContainer = StringName({nil}),
    .ScrollContainer = StringName({nil}),
    .CenterContainer = StringName({nil}),
    .GridContainer = StringName({nil}),
    .VBoxContainer = StringName({nil}),
    .HBoxContainer = StringName({nil}),
    .BoxContainer = StringName({nil}),
    .TextureButton = StringName({nil}),
    .VSeparator = StringName({nil}),
    .HSeparator = StringName({nil}),
    .Separator = StringName({nil}),
    .TabBar = StringName({nil}),
    .TabContainer = StringName({nil}),
    .AspectRatioContainer = StringName({nil}),
    .ReferenceRect = StringName({nil}),
    .NinePatchRect = StringName({nil}),
    .ColorRect = StringName({nil}),
    .TextureRect = StringName({nil}),
    .Container = StringName({nil}),
    .Panel = StringName({nil}),
    .LinkButton = StringName({nil}),
    .CheckButton = StringName({nil}),
    .CheckBox = StringName({nil}),
    .PopupPanel = StringName({nil}),
    .Popup = StringName({nil}),
    .VSlider = StringName({nil}),
    .HSlider = StringName({nil}),
    .Slider = StringName({nil}),
    .ProgressBar = StringName({nil}),
    .VScrollBar = StringName({nil}),
    .HScrollBar = StringName({nil}),
    .ScrollBar = StringName({nil}),
    .Range = StringName({nil}),
    .LabelSettings = StringName({nil}),
    .Label = StringName({nil}),
    .Button = StringName({nil}),
    .ButtonGroup = StringName({nil}),
    .BaseButton = StringName({nil}),
    .StatusIndicator = StringName({nil}),
    .Theme = StringName({nil}),
    .ResourcePreloader = StringName({nil}),
    .CanvasLayer = StringName({nil}),
    .Timer = StringName({nil}),
    .MultiplayerAPIExtension = StringName({nil}),
    .MultiplayerPeerExtension = StringName({nil}),
    .CompositorEffect = StringName({nil}),
    .ViewportTexture = StringName({nil}),
    .SubViewport = StringName({nil}),
    .World2D = StringName({nil}),
    .World3D = StringName({nil}),
    .SkeletonModification2DFABRIK = StringName({nil}),
    .SkeletonModification2DCCDIK = StringName({nil}),
    .SkeletonModification2DLookAt = StringName({nil}),
    .SkeletonModification2D = StringName({nil}),
    .SkeletonModificationStack2D = StringName({nil}),
    .ParallaxLayer = StringName({nil}),
    .ParallaxBackground = StringName({nil}),
    .RemoteTransform2D = StringName({nil}),
    .Parallax2D = StringName({nil}),
    .TileData = StringName({nil}),
    .TileSetSource = StringName({nil}),
    .TouchScreenButton = StringName({nil}),
    .DampedSpringJoint2D = StringName({nil}),
    .GrooveJoint2D = StringName({nil}),
    .PinJoint2D = StringName({nil}),
    .Joint2D = StringName({nil}),
    .AudioListener2D = StringName({nil}),
    .Camera2D = StringName({nil}),
    .CanvasModulate = StringName({nil}),
    .BackBufferCopy = StringName({nil}),
    .OccluderPolygon2D = StringName({nil}),
    .LightOccluder2D = StringName({nil}),
    .DirectionalLight2D = StringName({nil}),
    .PointLight2D = StringName({nil}),
    .Light2D = StringName({nil}),
    .Bone2D = StringName({nil}),
    .Skeleton2D = StringName({nil}),
    .Polygon2D = StringName({nil}),
    .VisibleOnScreenEnabler2D = StringName({nil}),
    .VisibleOnScreenNotifier2D = StringName({nil}),
    .ShapeCast2D = StringName({nil}),
    .RayCast2D = StringName({nil}),
    .CollisionPolygon2D = StringName({nil}),
    .CollisionShape2D = StringName({nil}),
    .Area2D = StringName({nil}),
    .KinematicCollision2D = StringName({nil}),
    .CharacterBody2D = StringName({nil}),
    .AnimatableBody2D = StringName({nil}),
    .StaticBody2D = StringName({nil}),
    .CollisionObject2D = StringName({nil}),
    .MultiMeshInstance2D = StringName({nil}),
    .MeshInstance2D = StringName({nil}),
    .Marker2D = StringName({nil}),
    .Sprite2D = StringName({nil}),
    .GPUParticles2D = StringName({nil}),
    .CPUParticles2D = StringName({nil}),
    .CanvasGroup = StringName({nil}),
    .Node2D = StringName({nil}),
    .CanvasItemMaterial = StringName({nil}),
    .CanvasTexture = StringName({nil}),
    .ShaderMaterial = StringName({nil}),
    .VisualShaderNodeParticleEmit = StringName({nil}),
    .VisualShaderNodeParticleAccelerator = StringName({nil}),
    .VisualShaderNodeParticleRandomness = StringName({nil}),
    .VisualShaderNodeParticleConeVelocity = StringName({nil}),
    .VisualShaderNodeParticleMultiplyByAxisAngle = StringName({nil}),
    .VisualShaderNodeParticleMeshEmitter = StringName({nil}),
    .VisualShaderNodeParticleRingEmitter = StringName({nil}),
    .VisualShaderNodeParticleBoxEmitter = StringName({nil}),
    .VisualShaderNodeParticleSphereEmitter = StringName({nil}),
    .VisualShaderNodeParticleEmitter = StringName({nil}),
    .VisualShaderNodeParticleOutput = StringName({nil}),
    .VisualShaderNodeSDFRaymarch = StringName({nil}),
    .VisualShaderNodeTextureSDFNormal = StringName({nil}),
    .VisualShaderNodeTextureSDF = StringName({nil}),
    .VisualShaderNodeScreenUVToSDF = StringName({nil}),
    .VisualShaderNodeSDFToScreenUV = StringName({nil}),
    .VisualShaderNodeReroute = StringName({nil}),
    .VisualShaderNodeVaryingGetter = StringName({nil}),
    .VisualShaderNodeVaryingSetter = StringName({nil}),
    .VisualShaderNodeVarying = StringName({nil}),
    .VisualShaderNodeRotationByAxis = StringName({nil}),
    .VisualShaderNodeRemap = StringName({nil}),
    .VisualShaderNodeRandomRange = StringName({nil}),
    .VisualShaderNodeProximityFade = StringName({nil}),
    .VisualShaderNodeDistanceFade = StringName({nil}),
    .VisualShaderNodeBillboard = StringName({nil}),
    .VisualShaderNodeMultiplyAdd = StringName({nil}),
    .VisualShaderNodeCompare = StringName({nil}),
    .VisualShaderNodeIs = StringName({nil}),
    .VisualShaderNodeGlobalExpression = StringName({nil}),
    .VisualShaderNodeExpression = StringName({nil}),
    .VisualShaderNodeFresnel = StringName({nil}),
    .VisualShaderNodeSwitch = StringName({nil}),
    .VisualShaderNodeIf = StringName({nil}),
    .VisualShaderNodeScreenNormalWorldSpace = StringName({nil}),
    .VisualShaderNodeWorldPositionFromDepth = StringName({nil}),
    .VisualShaderNodeLinearSceneDepth = StringName({nil}),
    .VisualShaderNodeCubemapParameter = StringName({nil}),
    .VisualShaderNodeTexture3DParameter = StringName({nil}),
    .VisualShaderNodeTexture2DArrayParameter = StringName({nil}),
    .VisualShaderNodeTextureParameterTriplanar = StringName({nil}),
    .VisualShaderNodeTexture2DParameter = StringName({nil}),
    .VisualShaderNodeTextureParameter = StringName({nil}),
    .VisualShaderNodeTransformParameter = StringName({nil}),
    .VisualShaderNodeVec4Parameter = StringName({nil}),
    .VisualShaderNodeVec3Parameter = StringName({nil}),
    .VisualShaderNodeVec2Parameter = StringName({nil}),
    .VisualShaderNodeColorParameter = StringName({nil}),
    .VisualShaderNodeBooleanParameter = StringName({nil}),
    .VisualShaderNodeUIntParameter = StringName({nil}),
    .VisualShaderNodeIntParameter = StringName({nil}),
    .VisualShaderNodeFloatParameter = StringName({nil}),
    .VisualShaderNodeParameterRef = StringName({nil}),
    .VisualShaderNodeParameter = StringName({nil}),
    .VisualShaderNodeCubemap = StringName({nil}),
    .VisualShaderNodeTexture3D = StringName({nil}),
    .VisualShaderNodeTexture2DArray = StringName({nil}),
    .VisualShaderNodeSample3D = StringName({nil}),
    .CurveXYZTexture = StringName({nil}),
    .VisualShaderNodeCurveXYZTexture = StringName({nil}),
    .CurveTexture = StringName({nil}),
    .VisualShaderNodeCurveTexture = StringName({nil}),
    .VisualShaderNodeTexture = StringName({nil}),
    .VisualShaderNodeTransformDecompose = StringName({nil}),
    .VisualShaderNodeVectorDecompose = StringName({nil}),
    .VisualShaderNodeTransformCompose = StringName({nil}),
    .VisualShaderNodeVectorCompose = StringName({nil}),
    .VisualShaderNodeMix = StringName({nil}),
    .VisualShaderNodeVectorRefract = StringName({nil}),
    .VisualShaderNodeVectorDistance = StringName({nil}),
    .VisualShaderNodeStep = StringName({nil}),
    .VisualShaderNodeSmoothStep = StringName({nil}),
    .VisualShaderNodeOuterProduct = StringName({nil}),
    .VisualShaderNodeFaceForward = StringName({nil}),
    .VisualShaderNodeClamp = StringName({nil}),
    .VisualShaderNodeDerivativeFunc = StringName({nil}),
    .VisualShaderNodeDeterminant = StringName({nil}),
    .VisualShaderNodeVectorLen = StringName({nil}),
    .VisualShaderNodeDotProduct = StringName({nil}),
    .VisualShaderNodeUVPolarCoord = StringName({nil}),
    .VisualShaderNodeUVFunc = StringName({nil}),
    .VisualShaderNodeTransformFunc = StringName({nil}),
    .VisualShaderNodeColorFunc = StringName({nil}),
    .VisualShaderNodeVectorFunc = StringName({nil}),
    .VisualShaderNodeUIntFunc = StringName({nil}),
    .VisualShaderNodeIntFunc = StringName({nil}),
    .VisualShaderNodeFloatFunc = StringName({nil}),
    .VisualShaderNodeTransformVecMult = StringName({nil}),
    .VisualShaderNodeTransformOp = StringName({nil}),
    .VisualShaderNodeColorOp = StringName({nil}),
    .VisualShaderNodeVectorOp = StringName({nil}),
    .VisualShaderNodeUIntOp = StringName({nil}),
    .VisualShaderNodeIntOp = StringName({nil}),
    .VisualShaderNodeFloatOp = StringName({nil}),
    .VisualShaderNodeTransformConstant = StringName({nil}),
    .VisualShaderNodeVec4Constant = StringName({nil}),
    .VisualShaderNodeVec3Constant = StringName({nil}),
    .VisualShaderNodeVec2Constant = StringName({nil}),
    .VisualShaderNodeColorConstant = StringName({nil}),
    .VisualShaderNodeBooleanConstant = StringName({nil}),
    .VisualShaderNodeUIntConstant = StringName({nil}),
    .VisualShaderNodeIntConstant = StringName({nil}),
    .VisualShaderNodeFloatConstant = StringName({nil}),
    .VisualShaderNodeComment = StringName({nil}),
    .VisualShaderNodeFrame = StringName({nil}),
    .VisualShaderNodeVectorBase = StringName({nil}),
    .VisualShaderNodeConstant = StringName({nil}),
    .VisualShaderNodeGroupBase = StringName({nil}),
    .VisualShaderNodeResizableBase = StringName({nil}),
    .VisualShaderNodeOutput = StringName({nil}),
    .VisualShaderNodeInput = StringName({nil}),
    .VisualShaderNodeCustom = StringName({nil}),
    .VisualShaderNode = StringName({nil}),
    .ShaderInclude = StringName({nil}),
    .VisualShader = StringName({nil}),
    .NavigationLink3D = StringName({nil}),
    .NavigationObstacle3D = StringName({nil}),
    .NavigationAgent3D = StringName({nil}),
    .NavigationMesh = StringName({nil}),
    .NavigationRegion3D = StringName({nil}),
    .NavigationMeshSourceGeometryData3D = StringName({nil}),
    .Generic6DOFJoint3D = StringName({nil}),
    .ConeTwistJoint3D = StringName({nil}),
    .SliderJoint3D = StringName({nil}),
    .HingeJoint3D = StringName({nil}),
    .PinJoint3D = StringName({nil}),
    .Joint3D = StringName({nil}),
    .RemoteTransform3D = StringName({nil}),
    .FogMaterial = StringName({nil}),
    .FogVolume = StringName({nil}),
    .WorldEnvironment = StringName({nil}),
    .VisibleOnScreenEnabler3D = StringName({nil}),
    .VisibleOnScreenNotifier3D = StringName({nil}),
    .PathFollow3D = StringName({nil}),
    .Path3D = StringName({nil}),
    .MultiMesh = StringName({nil}),
    .MultiMeshInstance3D = StringName({nil}),
    .ShapeCast3D = StringName({nil}),
    .RayCast3D = StringName({nil}),
    .CollisionPolygon3D = StringName({nil}),
    .CollisionShape3D = StringName({nil}),
    .Area3D = StringName({nil}),
    .VehicleWheel3D = StringName({nil}),
    .VehicleBody3D = StringName({nil}),
    .SkeletonIK3D = StringName({nil}),
    .LookAtModifier3D = StringName({nil}),
    .BoneAttachment3D = StringName({nil}),
    .SoftBody3D = StringName({nil}),
    .PhysicalBoneSimulator3D = StringName({nil}),
    .SpringArm3D = StringName({nil}),
    .CharacterBody3D = StringName({nil}),
    .KinematicCollision3D = StringName({nil}),
    .AnimatableBody3D = StringName({nil}),
    .PhysicsMaterial = StringName({nil}),
    .StaticBody3D = StringName({nil}),
    .CollisionObject3D = StringName({nil}),
    .XRFaceModifier3D = StringName({nil}),
    .XRHandModifier3D = StringName({nil}),
    .XRBodyModifier3D = StringName({nil}),
    .XROrigin3D = StringName({nil}),
    .XRAnchor3D = StringName({nil}),
    .XRController3D = StringName({nil}),
    .XRNode3D = StringName({nil}),
    .XRCamera3D = StringName({nil}),
    .BoneTwistDisperser3D = StringName({nil}),
    .LimitAngularVelocityModifier3D = StringName({nil}),
    .JacobianIK3D = StringName({nil}),
    .CCDIK3D = StringName({nil}),
    .FABRIK3D = StringName({nil}),
    .IterateIK3D = StringName({nil}),
    .SplineIK3D = StringName({nil}),
    .ChainIK3D = StringName({nil}),
    .TwoBoneIK3D = StringName({nil}),
    .IKModifier3D = StringName({nil}),
    .AimModifier3D = StringName({nil}),
    .ConvertTransformModifier3D = StringName({nil}),
    .CopyTransformModifier3D = StringName({nil}),
    .BoneConstraint3D = StringName({nil}),
    .SpringBoneCollisionPlane3D = StringName({nil}),
    .SpringBoneCollisionCapsule3D = StringName({nil}),
    .SpringBoneCollisionSphere3D = StringName({nil}),
    .SpringBoneCollision3D = StringName({nil}),
    .SpringBoneSimulator3D = StringName({nil}),
    .JointLimitationCone3D = StringName({nil}),
    .JointLimitation3D = StringName({nil}),
    .SkeletonProfile = StringName({nil}),
    .RetargetModifier3D = StringName({nil}),
    .ModifierBoneTarget3D = StringName({nil}),
    .SkeletonModifier3D = StringName({nil}),
    .RootMotionView = StringName({nil}),
    .Marker3D = StringName({nil}),
    .Gradient = StringName({nil}),
    .CPUParticles3D = StringName({nil}),
    .GPUParticlesAttractorVectorField3D = StringName({nil}),
    .GPUParticlesAttractorSphere3D = StringName({nil}),
    .GPUParticlesAttractorBox3D = StringName({nil}),
    .GPUParticlesAttractor3D = StringName({nil}),
    .GPUParticlesCollisionHeightField3D = StringName({nil}),
    .Texture3D = StringName({nil}),
    .GPUParticlesCollisionSDF3D = StringName({nil}),
    .GPUParticlesCollisionSphere3D = StringName({nil}),
    .GPUParticlesCollisionBox3D = StringName({nil}),
    .GPUParticlesCollision3D = StringName({nil}),
    .GPUParticles3D = StringName({nil}),
    .Lightmapper = StringName({nil}),
    .LightmapProbe = StringName({nil}),
    .TextureLayered = StringName({nil}),
    .LightmapGIData = StringName({nil}),
    .Sky = StringName({nil}),
    .LightmapGI = StringName({nil}),
    .VoxelGIData = StringName({nil}),
    .VoxelGI = StringName({nil}),
    .Decal = StringName({nil}),
    .ReflectionProbe = StringName({nil}),
    .SpotLight3D = StringName({nil}),
    .OmniLight3D = StringName({nil}),
    .DirectionalLight3D = StringName({nil}),
    .Light3D = StringName({nil}),
    .Label3D = StringName({nil}),
    .Sprite3D = StringName({nil}),
    .SpriteBase3D = StringName({nil}),
    .PolygonOccluder3D = StringName({nil}),
    .SphereOccluder3D = StringName({nil}),
    .BoxOccluder3D = StringName({nil}),
    .QuadOccluder3D = StringName({nil}),
    .ArrayOccluder3D = StringName({nil}),
    .Occluder3D = StringName({nil}),
    .OccluderInstance3D = StringName({nil}),
    .Mesh = StringName({nil}),
    .MeshInstance3D = StringName({nil}),
    .AudioListener3D = StringName({nil}),
    .Compositor = StringName({nil}),
    .Environment = StringName({nil}),
    .Camera3D = StringName({nil}),
    .GeometryInstance3D = StringName({nil}),
    .VisualInstance3D = StringName({nil}),
    .ImporterMeshInstance3D = StringName({nil}),
    .SkinReference = StringName({nil}),
    .Skin = StringName({nil}),
    .Node3DGizmo = StringName({nil}),
    .ShaderGlobalsOverride = StringName({nil}),
    .AnimationNodeTransition = StringName({nil}),
    .AnimationNodeTimeSeek = StringName({nil}),
    .AnimationNodeTimeScale = StringName({nil}),
    .AnimationNodeSub2 = StringName({nil}),
    .AnimationNodeBlend3 = StringName({nil}),
    .AnimationNodeBlend2 = StringName({nil}),
    .AnimationNodeAdd3 = StringName({nil}),
    .AnimationNodeAdd2 = StringName({nil}),
    .AnimationNodeAnimation = StringName({nil}),
    .AnimationNodeOneShot = StringName({nil}),
    .AnimationNodeOutput = StringName({nil}),
    .AnimationNodeStateMachineTransition = StringName({nil}),
    .AnimationNodeSync = StringName({nil}),
    .AnimationNodeExtension = StringName({nil}),
    .GLTFPhysicsShape = StringName({nil}),
    .GLTFPhysicsBody = StringName({nil}),
    .GLTFMesh = StringName({nil}),
    .GLTFLight = StringName({nil}),
    .GLTFCamera = StringName({nil}),
    .GLTFBufferView = StringName({nil}),
    .GLTFAnimation = StringName({nil}),
    .GLTFAccessor = StringName({nil}),
    .GLTFObjectModelProperty = StringName({nil}),
    .GLTFTexture = StringName({nil}),
    .GLTFNode = StringName({nil}),
    .GLTFDocumentExtensionConvertImporterMesh = StringName({nil}),
    .GLTFDocumentExtension = StringName({nil}),
    .FBXState = StringName({nil}),
    .GLTFState = StringName({nil}),
    .FBXDocument = StringName({nil}),
    .ENetPacketPeer = StringName({nil}),
    .OggPacketSequence = StringName({nil}),
    .AudioStreamOggVorbis = StringName({nil}),
    .CSGTorus3D = StringName({nil}),
    .CSGSphere3D = StringName({nil}),
    .CSGShape3D = StringName({nil}),
    .CSGPrimitive3D = StringName({nil}),
    .CSGPolygon3D = StringName({nil}),
    .CSGMesh3D = StringName({nil}),
    .CSGCylinder3D = StringName({nil}),
    .CSGCombiner3D = StringName({nil}),
    .CSGBox3D = StringName({nil}),
    .FastNoiseLite = StringName({nil}),
    .SceneTreeTimer = StringName({nil}),
    .PackedScene = StringName({nil}),
    .SceneState = StringName({nil}),
    .PolygonPathFinder = StringName({nil}),
    .NavigationLink2D = StringName({nil}),
    .NavigationObstacle2D = StringName({nil}),
    .NavigationAgent2D = StringName({nil}),
    .NavigationRegion2D = StringName({nil}),
    .NavigationPolygon = StringName({nil}),
    .NavigationMeshSourceGeometryData2D = StringName({nil}),
    .ConcavePolygonShape2D = StringName({nil}),
    .ConvexPolygonShape2D = StringName({nil}),
    .CapsuleShape2D = StringName({nil}),
    .RectangleShape2D = StringName({nil}),
    .CircleShape2D = StringName({nil}),
    .SeparationRayShape2D = StringName({nil}),
    .SegmentShape2D = StringName({nil}),
    .WorldBoundaryShape2D = StringName({nil}),
    .PathFollow2D = StringName({nil}),
    .Path2D = StringName({nil}),
    .AudioStreamPlayer2D = StringName({nil}),
    .AudioStreamPolyphonic = StringName({nil}),
    .AudioStreamWAV = StringName({nil}),
    .AudioStreamPlayer = StringName({nil}),
    .BoneMap = StringName({nil}),
    .SkeletonProfileHumanoid = StringName({nil}),
    .StyleBoxLine = StringName({nil}),
    .StyleBoxFlat = StringName({nil}),
    .StyleBoxTexture = StringName({nil}),
    .StyleBoxEmpty = StringName({nil}),
    .ColorPalette = StringName({nil}),
    .SystemFont = StringName({nil}),
    .FontVariation = StringName({nil}),
    .FontFile = StringName({nil}),
    .AnimationLibrary = StringName({nil}),
    .Texture3DRD = StringName({nil}),
    .TextureCubemapArrayRD = StringName({nil}),
    .TextureCubemapRD = StringName({nil}),
    .Texture2DArrayRD = StringName({nil}),
    .TextureLayeredRD = StringName({nil}),
    .Texture2DRD = StringName({nil}),
    .AnimatedTexture = StringName({nil}),
    .DPITexture = StringName({nil}),
    .PlaceholderCubemapArray = StringName({nil}),
    .PlaceholderCubemap = StringName({nil}),
    .PlaceholderTexture2DArray = StringName({nil}),
    .PlaceholderTextureLayered = StringName({nil}),
    .PlaceholderTexture3D = StringName({nil}),
    .PlaceholderTexture2D = StringName({nil}),
    .CompressedTexture2DArray = StringName({nil}),
    .CompressedCubemapArray = StringName({nil}),
    .CompressedCubemap = StringName({nil}),
    .CompressedTextureLayered = StringName({nil}),
    .Texture2DArray = StringName({nil}),
    .CubemapArray = StringName({nil}),
    .Cubemap = StringName({nil}),
    .CompressedTexture3D = StringName({nil}),
    .ImageTexture3D = StringName({nil}),
    .ImageTextureLayered = StringName({nil}),
    .ExternalTexture = StringName({nil}),
    .CameraTexture = StringName({nil}),
    .GradientTexture2D = StringName({nil}),
    .MeshTexture = StringName({nil}),
    .AtlasTexture = StringName({nil}),
    .ImageTexture = StringName({nil}),
    .CompressedTexture2D = StringName({nil}),
    .CameraAttributesPractical = StringName({nil}),
    .CameraAttributesPhysical = StringName({nil}),
    .CameraAttributes = StringName({nil}),
    .ConcavePolygonShape3D = StringName({nil}),
    .ConvexPolygonShape3D = StringName({nil}),
    .WorldBoundaryShape3D = StringName({nil}),
    .HeightMapShape3D = StringName({nil}),
    .CylinderShape3D = StringName({nil}),
    .CapsuleShape3D = StringName({nil}),
    .BoxShape3D = StringName({nil}),
    .SphereShape3D = StringName({nil}),
    .SeparationRayShape3D = StringName({nil}),
    .MeshLibrary = StringName({nil}),
    .PhysicalSkyMaterial = StringName({nil}),
    .PanoramaSkyMaterial = StringName({nil}),
    .ProceduralSkyMaterial = StringName({nil}),
    .ORMMaterial3D = StringName({nil}),
    .StandardMaterial3D = StringName({nil}),
    .BaseMaterial3D = StringName({nil}),
    .PointMesh = StringName({nil}),
    .RibbonTrailMesh = StringName({nil}),
    .TubeTrailMesh = StringName({nil}),
    .TorusMesh = StringName({nil}),
    .TextMesh = StringName({nil}),
    .SphereMesh = StringName({nil}),
    .QuadMesh = StringName({nil}),
    .PrismMesh = StringName({nil}),
    .PlaneMesh = StringName({nil}),
    .CylinderMesh = StringName({nil}),
    .CapsuleMesh = StringName({nil}),
    .BoxMesh = StringName({nil}),
    .PrimitiveMesh = StringName({nil}),
    .AudioStreamPlayer3D = StringName({nil}),
    .MeshDataTool = StringName({nil}),
    .PlaceholderMesh = StringName({nil}),
    .MeshConvexDecompositionSettings = StringName({nil}),
    .GradientTexture1D = StringName({nil}),
    .ParticleProcessMaterial = StringName({nil}),
    .SkeletonModification2DPhysicalBones = StringName({nil}),
    .SkeletonModification2DJiggle = StringName({nil}),
    .PhysicalBone2D = StringName({nil}),
    .SkeletonModification2DStackHolder = StringName({nil}),
    .SkeletonModification2DTwoBoneIK = StringName({nil}),
    .JavaScriptObject = StringName({nil}),
    .JavaObject = StringName({nil}),
    .JavaClass = StringName({nil}),
    .JNISingleton = StringName({nil}),
    .JavaClassWrapper = StringName({nil}),
    .ResourceImporterOggVorbis = StringName({nil}),
    .OpenXRBindingModifierEditor = StringName({nil}),
    .OpenXRInteractionProfileEditor = StringName({nil}),
    .OpenXRInteractionProfileEditorBase = StringName({nil}),
    .ResourceImporterMP3 = StringName({nil}),
    .GridMapEditorPlugin = StringName({nil}),
    .EditorSceneFormatImporterBlend = StringName({nil}),
    .EditorSceneFormatImporterGLTF = StringName({nil}),
    .GDScriptSyntaxHighlighter = StringName({nil}),
    .EditorSceneFormatImporterFBX2GLTF = StringName({nil}),
    .EditorSceneFormatImporterUFBX = StringName({nil}),
    .ResourceImporterWAV = StringName({nil}),
    .ResourceImporterTextureAtlas = StringName({nil}),
    .ResourceImporterTexture = StringName({nil}),
    .ResourceImporterShaderFile = StringName({nil}),
    .ResourceImporterScene = StringName({nil}),
    .ResourceImporterOBJ = StringName({nil}),
    .ResourceImporterLayeredTexture = StringName({nil}),
    .ResourceImporterSVG = StringName({nil}),
    .ResourceImporterImageFont = StringName({nil}),
    .ResourceImporterImage = StringName({nil}),
    .ResourceImporterDynamicFont = StringName({nil}),
    .ResourceImporterCSVTranslation = StringName({nil}),
    .ResourceImporterBMFont = StringName({nil}),
    .ResourceImporterBitMap = StringName({nil}),
    .EditorDebuggerPlugin = StringName({nil}),
    .EditorScenePostImport = StringName({nil}),
    .EditorFileSystemImportFormatSupportQuery = StringName({nil}),
    .FileSystemDock = StringName({nil}),
    .EditorContextMenuPlugin = StringName({nil}),
    .EditorScriptPicker = StringName({nil}),
    .EditorResourcePicker = StringName({nil}),
    .EditorSpinSlider = StringName({nil}),
    .EditorFeatureProfile = StringName({nil}),
    .EditorInspectorPlugin = StringName({nil}),
    .EditorInspector = StringName({nil}),
    .EditorSceneFormatImporter = StringName({nil}),
    .EditorResourceConversionPlugin = StringName({nil}),
    .EditorExportPlatformWindows = StringName({nil}),
    .EditorExportPlatformWeb = StringName({nil}),
    .EditorExportPlatformVisionOS = StringName({nil}),
    .EditorExportPlatformMacOS = StringName({nil}),
    .EditorExportPlatformLinuxBSD = StringName({nil}),
    .EditorExportPlatformIOS = StringName({nil}),
    .EditorExportPlatformAndroid = StringName({nil}),
    .EditorExportPreset = StringName({nil}),
    .EditorExportPlatformExtension = StringName({nil}),
    .EditorExportPlatformAppleEmbedded = StringName({nil}),
    .EditorExportPlatformPC = StringName({nil}),
    .EditorExportPlugin = StringName({nil}),
    .EditorSyntaxHighlighter = StringName({nil}),
    .ScriptEditorBase = StringName({nil}),
    .ScriptEditor = StringName({nil}),
    .EditorVCSInterface = StringName({nil}),
    .EditorFileSystemDirectory = StringName({nil}),
    .EditorFileSystem = StringName({nil}),
    .EditorResourceTooltipPlugin = StringName({nil}),
    .EditorResourcePreviewGenerator = StringName({nil}),
    .EditorResourcePreview = StringName({nil}),
    .EditorToaster = StringName({nil}),
    .EditorSettings = StringName({nil}),
    .EditorSelection = StringName({nil}),
    .EditorDock = StringName({nil}),
    .EditorScript = StringName({nil}),
    .EditorPlugin = StringName({nil}),
    .WebXRInterface = StringName({nil}),
    .WebRTCDataChannelExtension = StringName({nil}),
    .WebRTCPeerConnectionExtension = StringName({nil}),
    .WebRTCDataChannel = StringName({nil}),
    .AudioStreamPlaybackOggVorbis = StringName({nil}),
    .VideoStreamTheora = StringName({nil}),
    .RegExMatch = StringName({nil}),
    .OpenXRSpatialMarkerTrackingCapability = StringName({nil}),
    .OpenXRSpatialPlaneTrackingCapability = StringName({nil}),
    .OpenXRSpatialAnchorCapability = StringName({nil}),
    .OpenXRSpatialComponentPersistenceList = StringName({nil}),
    .OpenXRSpatialComponentAnchorList = StringName({nil}),
    .OpenXRSpatialQueryResultData = StringName({nil}),
    .OpenXRSpatialComponentMarkerList = StringName({nil}),
    .OpenXRSpatialComponentPlaneSemanticLabelList = StringName({nil}),
    .OpenXRSpatialComponentPolygon2DList = StringName({nil}),
    .OpenXRSpatialComponentPlaneAlignmentList = StringName({nil}),
    .OpenXRSpatialComponentMesh3DList = StringName({nil}),
    .OpenXRSpatialComponentMesh2DList = StringName({nil}),
    .OpenXRSpatialComponentParentList = StringName({nil}),
    .OpenXRSpatialComponentBounded3DList = StringName({nil}),
    .OpenXRSpatialComponentBounded2DList = StringName({nil}),
    .OpenXRSpatialComponentData = StringName({nil}),
    .OpenXRSpatialCapabilityConfigurationPlaneTracking = StringName({nil}),
    .OpenXRSpatialContextPersistenceConfig = StringName({nil}),
    .OpenXRSpatialCapabilityConfigurationAprilTag = StringName({nil}),
    .OpenXRSpatialCapabilityConfigurationAruco = StringName({nil}),
    .OpenXRSpatialCapabilityConfigurationMicroQrCode = StringName({nil}),
    .OpenXRSpatialCapabilityConfigurationQrCode = StringName({nil}),
    .OpenXRSpatialCapabilityConfigurationAnchor = StringName({nil}),
    .OpenXRSpatialCapabilityConfigurationBaseHeader = StringName({nil}),
    .OpenXRStructureBase = StringName({nil}),
    .OpenXRMarkerTracker = StringName({nil}),
    .OpenXRPlaneTracker = StringName({nil}),
    .OpenXRAnchorTracker = StringName({nil}),
    .OpenXRSpatialEntityTracker = StringName({nil}),
    .OpenXRSpatialEntityExtension = StringName({nil}),
    .OpenXRRenderModelManager = StringName({nil}),
    .OpenXRRenderModel = StringName({nil}),
    .OpenXRVisibilityMask = StringName({nil}),
    .OpenXRHand = StringName({nil}),
    .OpenXRCompositionLayerQuad = StringName({nil}),
    .OpenXRCompositionLayerCylinder = StringName({nil}),
    .OpenXRCompositionLayerEquirect = StringName({nil}),
    .OpenXRCompositionLayer = StringName({nil}),
    .OpenXRHapticVibration = StringName({nil}),
    .OpenXRDpadBindingModifier = StringName({nil}),
    .OpenXRHapticBase = StringName({nil}),
    .OpenXRAnalogThresholdModifier = StringName({nil}),
    .OpenXRBindingModifier = StringName({nil}),
    .OpenXRIPBindingModifier = StringName({nil}),
    .OpenXRActionBindingModifier = StringName({nil}),
    .OpenXRIPBinding = StringName({nil}),
    .OpenXRInteractionProfileMetadata = StringName({nil}),
    .OpenXRInteractionProfile = StringName({nil}),
    .OpenXRActionMap = StringName({nil}),
    .OpenXRActionSet = StringName({nil}),
    .OpenXRAction = StringName({nil}),
    .OpenXRInterface = StringName({nil}),
    .OggPacketSequencePlayback = StringName({nil}),
    .NoiseTexture2D = StringName({nil}),
    .NoiseTexture3D = StringName({nil}),
    .OfflineMultiplayerPeer = StringName({nil}),
    .MultiplayerSynchronizer = StringName({nil}),
    .MultiplayerSpawner = StringName({nil}),
    .AudioStreamMP3 = StringName({nil}),
    .MobileVRInterface = StringName({nil}),
    .LightmapperRD = StringName({nil}),
    .JSONRPC = StringName({nil}),
    .AudioStreamPlaybackSynchronized = StringName({nil}),
    .AudioStreamSynchronized = StringName({nil}),
    .AudioStreamPlaybackInteractive = StringName({nil}),
    .AudioStreamInteractive = StringName({nil}),
    .AudioStreamPlaybackPlaylist = StringName({nil}),
    .AudioStreamPlaylist = StringName({nil}),
    .GLTFTextureSampler = StringName({nil}),
    .GLTFSpecGloss = StringName({nil}),
    .GLTFSkin = StringName({nil}),
    .GLTFSkeleton = StringName({nil}),
    .Master = StringName({nil}),
}
